### ISSUE TITLE
Unable to exec into pod: 502 Bad Gateway. cgroupv2 skipping over unmappable

### ISSUE THREAD

**Issue by danielgelling** [k3s-io/k3s#10465]
**Environmental Info:**
- K3s Version: 
`k3s version v1.30.2+k3s2 (faeaf1b0)`
`go version go1.22.4`

- Node(s) CPU architecture, OS, and Version: 
`Linux k3s-node1 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux`

- Cluster Configuration:
Single node server on a  `Raspberry Pi 4 Model B Rev 1.2`

**Describe the bug:**
When trying to exec into any pod using `kubectl exec -it api-74fc4bfd74-t9gnz -- /bin/sh` the following error is returned:
```
error: Internal error occurred: error sending request: Post "https://192.168.0.6:10250/exec/clubrace-nl/api-74fc4bfd74-t9gnz/api?command=%!F(MISSING)bin%!F(MISSING)bash&input=1&output=1&tty=1": proxy error from 192.168.0.6:6443 while dialing 192.168.0.6:10250, code 502: 502 Bad Gateway
```

Additionally, running the k3s server with the `--debug` flag, the journalctl logs the following a lot. No other noticable errors/warnings are seen.

```
Jul 09 19:48:01 k3s-node1 k3s[22188]: time="2024-07-09T19:48:01+02:00" level=debug msg="cgroupv2 io stats: skipping over unmappable dbytes=0 entry"
Jul 09 19:48:01 k3s-node1 k3s[22188]: time="2024-07-09T19:48:01+02:00" level=debug msg="cgroupv2 io stats: skipping over unmappable dios=0 entry"
```

Except for being able to exec into the pod, the cluster functions fine.

**Steps To Reproduce:**
- Install `Raspbian Debian GNU/Linux 12 (bookworm)` on a `Raspberry Pi 4 Model B Rev 1.2`
- Enable cgroups in  `/boot/firmware/cmdline.txt` by appending `cgroup_memory=1 cgroup_enable=memory`
- Install K3s: 
```
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION='v1.30.2+k3s2' INSTALL_K3S_EXEC="server --flannel-backend=host-gw --tls-san=${SERVER_IP} --bind-address=${SERVER_IP} --advertise-address=${SERVER_IP} --node-ip=${SERVER_IP} --cluster-init" sh -s -
```
- Try to exec into a pod

**Expected behavior:**
Open a shell to a pod

**Actual behavior:**
Error 502 Bad Gateway

**Comment by brandond** [comment]
What is `${SERVER_IP}? Is this `192.168.0.6` or something else? Can you show the output of `kubectl get node -o yaml`?

**Comment by brandond** [comment]
Yeah I would try again, and don't set anything except for node-ip.

**Comment by danielgelling** [comment]
It all seemed to be working fine yesterday, however when I wanted to connect to the cluster just now, k3s is not responding. I tried restarting k3s.service, but to no avail.

It panics when starting.
```
Jul 10 22:07:06 k3s-node1 sh[1596]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Jul 10 22:07:06 k3s-node1 k3s[1600]: time="2024-07-10T22:07:06+02:00" level=info msg="Starting k3s v1.30.2+k3s2 (faeaf1b0)"
Jul 10 22:07:06 k3s-node1 k3s[1600]: time="2024-07-10T22:07:06+02:00" level=info msg="Managed etcd cluster bootstrap already complete and initialized"
Jul 10 22:07:06 k3s-node1 k3s[1600]: time="2024-07-10T22:07:06+02:00" level=info msg="Starting temporary etcd to reconcile with datastore"
Jul 10 22:07:20 k3s-node1 k3s[1600]: {"level":"info","ts":"2024-07-10T22:07:20.718759+0200","caller":"embed/etcd.go:127","msg":"configuring peer listeners","listen-peer-urls":["http://127.0.0.1:2400"]}
Jul 10 22:07:20 k3s-node1 k3s[1600]: {"level":"info","ts":"2024-07-10T22:07:20.720001+0200","caller":"embed/etcd.go:135","msg":"configuring client listeners","listen-client-urls":["http://127.0.0.1:2399"]}
Jul 10 22:07:20 k3s-node1 k3s[1600]: {"level":"info","ts":"2024-07-10T22:07:20.720391+0200","caller":"embed/etcd.go:308","msg":"starting an etcd server","etcd-version":"3.5.13","git-sha":"Not provided (use ./build instead of go build)","go-version":"go1.22.4","go-os":"linux","go-arch":"arm64","max-cpu-set":4,"max-cpu-available":4,"member-initialized":true,"name":"k3s-node1-64fd963a","data-dir":"/var/lib/rancher/k3s/server/db/etcd-tmp","wal-dir":"","wal-dir-dedicated":"","member-dir":"/var/lib/rancher/k3s/server/db/etcd-tmp/member","force-new-cluster":true,"heartbeat-interval":"500ms","election-timeout":"5s","initial-election-tick-advance":true,"snapshot-count":10000,"max-wals":0,"max-snapshots":0,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://127.0.0.1:2400"],"listen-peer-urls":["http://127.0.0.1:2400"],"advertise-client-urls":["http://127.0.0.1:2399"],"listen-client-urls":["http://127.0.0.1:2399"],"listen-metrics-urls":[],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"","initial-cluster-state":"new","initial-cluster-token":"","quota-backend-bytes":2147483648,"max-request-bytes":1572864,"max-concurrent-streams":4294967295,"pre-vote":true,"initial-corrupt-check":true,"corrupt-check-time-interval":"0s","compact-check-time-enabled":false,"compact-check-time-interval":"1m0s","auto-compaction-mode":"","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}
Jul 10 22:07:27 k3s-node1 k3s[1600]: panic: freepages: failed to get all reachable pages (key[0]=(hex)616c61726d on leaf page(9191) needs to be < than key of the next element in ancestor (hex)0000000001fe58315f0000000000000000. Pages stack: [520063 503235 11028 9191])
Jul 10 22:07:27 k3s-node1 k3s[1600]: goroutine 261 [running]:
Jul 10 22:07:27 k3s-node1 k3s[1600]: go.etcd.io/bbolt.(*DB).freepages.func2()
Jul 10 22:07:27 k3s-node1 k3s[1600]:         /go/pkg/mod/go.etcd.io/bbolt@v1.3.9/db.go:1202 +0x8c
Jul 10 22:07:27 k3s-node1 k3s[1600]: created by go.etcd.io/bbolt.(*DB).freepages in goroutine 49
Jul 10 22:07:27 k3s-node1 k3s[1600]:         /go/pkg/mod/go.etcd.io/bbolt@v1.3.9/db.go:1200 +0x13c
Jul 10 22:07:27 k3s-node1 systemd[1]: k3s.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by brandond** [comment]
Your etcd datastore is corrupted.... did this host experience an unxpected shutdown or power loss at some point? That's the only way I've ever seen the files get messed up, short of just having a bad disk (ie raspberry pi microsd failure).

This is not something that can be fixed by k3s, you'd need to restore from an etcd snapshot, or remove and rejoin the node if you have other etcd cluster members available.
