### ISSUE TITLE
Panic when attempt to use dqlite on Raspberry Pi

### ISSUE THREAD

**Issue by davidnuzik** [k3s-io/k3s#1115]
**Version:**
v1.0.0
master (d5929bc)

**Describe the bug**
On my Pi4 if I attempt to use the `--cluster-init` flag so as to set up dqlite as per https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/ K3s will fail to start and show a panic in logs.

Note: Pi3 also affected: https://github.com/rancher/k3s/issues/1155

**To Reproduce**
- Start K3s:
curl -sfL https://get.k3s.io | K3S_TOKEN=my-super-secret sh -s - --cluster-init

**Expected behavior**
K3s starts properly and the node comes up.

**Actual behavior**
K3s does not start properly and there are errors in the logs. There is a panic when check journalctl.

Here is output:
`from systemd`
```
Process: 8096 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
  Process: 8097 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 8098 ExecStart=/usr/local/bin/k3s server --cluster-init (code=exited, status=2)
 Main PID: 8098 (code=exited, status=2)
```
`from journalctl`
```
Nov 21 11:37:06 davidspi4 systemd[1]: Starting Lightweight Kubernetes...
Nov 21 11:37:07 davidspi4 k3s[8454]: time="2019-11-21T11:37:07.848274445-07:00" level=info msg="Starting k3s v1.0.0 (18bd921c)"
Nov 21 11:37:08 davidspi4 k3s[8454]: time="2019-11-21T11:37:08.353615969-07:00" level=info msg="Testing connection to peers [10.20.3.127:6443]"
Nov 21 11:37:08 davidspi4 k3s[8454]: panic: runtime error: makeslice: len out of range
Nov 21 11:37:08 davidspi4 k3s[8454]: goroutine 1 [running]:
Nov 21 11:37:08 davidspi4 k3s[8454]: github.com/rancher/k3s/vendor/github.com/canonical/go-dqlite/internal/protocol.(*Message).getBlob(0x61fc03c, 0x0, 0x585d720, 0x6239650)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/vendor/github.com/canonical/go-dqlite/internal/protocol/message.go:356 +0x3c
Nov 21 11:37:08 davidspi4 k3s[8454]: github.com/rancher/k3s/vendor/github.com/canonical/go-dqlite/internal/protocol.(*Rows).Next(0x6762284, 0x5ce8f00, 0xb, 0xb, 0x7bf5c, 0x978ca8)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/vendor/github.com/canonical/go-dqlite/internal/protocol/message.go:557 +0x2ec
Nov 21 11:37:08 davidspi4 k3s[8454]: github.com/rancher/k3s/vendor/github.com/canonical/go-dqlite/driver.(*Rows).Next(0x6762270, 0x5ce8f00, 0xb, 0xb, 0x0, 0x0)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/vendor/github.com/canonical/go-dqlite/driver/driver.go:585 +0x40
Nov 21 11:37:08 davidspi4 k3s[8454]: database/sql.(*Rows).nextLocked(0x5c55db0, 0x970000)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /usr/local/go/src/database/sql/sql.go:2767 +0xb4
Nov 21 11:37:08 davidspi4 k3s[8454]: database/sql.(*Rows).Next.func1()
Nov 21 11:37:08 davidspi4 k3s[8454]:         /usr/local/go/src/database/sql/sql.go:2745 +0x2c
Nov 21 11:37:08 davidspi4 k3s[8454]: database/sql.withLock(0x3795b80, 0x5c55dc8, 0x678f04c)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /usr/local/go/src/database/sql/sql.go:3184 +0x60
Nov 21 11:37:08 davidspi4 k3s[8454]: database/sql.(*Rows).Next(0x5c55db0, 0x6239610)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /usr/local/go/src/database/sql/sql.go:2744 +0x78
Nov 21 11:37:08 davidspi4 k3s[8454]: github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured/sqllog.RowsToEvents(0x5c55db0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured/sqllog/sql.go:221 +0xc8
Nov 21 11:37:08 davidspi4 k3s[8454]: github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured/sqllog.(*SQLLog).List(0x67ad320, 0x37bbe30, 0x5e6bc20, 0x2f04d89, 0x10, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured/sqllog/sql.go:188 +0xe0
Nov 21 11:37:08 davidspi4 k3s[8454]: github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured.(*LogStructured).get(0x5f801c0, 0x37bbe30, 0x5e6bc20, 0x2f04d89, 0x10, 0x0, 0x0, 0x6680001, 0x6118280, 0xa83bd4, ...)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured/logstructured.go:55 +0x80
Nov 21 11:37:08 davidspi4 k3s[8454]: github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured.(*LogStructured).Create(0x5f801c0, 0x37bbe30, 0x5e6bc20, 0x2f04d89, 0x10, 0x60fc340, 0x11, 0x11, 0x0, 0x0, ...)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured/logstructured.go:88 +0xfc
Nov 21 11:37:08 davidspi4 k3s[8454]: github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured.(*LogStructured).Start(0x5f801c0, 0x37bbe30, 0x5e6bc20, 0x6, 0x631eaa9)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured/logstructured.go:36 +0xd0
Nov 21 11:37:08 davidspi4 k3s[8454]: github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/endpoint.Listen(0x37bbe30, 0x5e6bc20, 0x0, 0x0, 0x0, 0x631eaa0, 0x48, 0x0, 0x0, 0x0, ...)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/endpoint/endpoint.go:58 +0xe4
Nov 21 11:37:08 davidspi4 k3s[8454]: github.com/rancher/k3s/pkg/cluster.(*Cluster).startStorage(0x64e5a40, 0x37bbe30, 0x5e6bc20, 0x0, 0x0)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/pkg/cluster/cluster.go:62 +0x60
Nov 21 11:37:08 davidspi4 k3s[8454]: github.com/rancher/k3s/pkg/cluster.(*Cluster).Start(0x64e5a40, 0x37bbe30, 0x5e6bc20, 0x0, 0x0)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/pkg/cluster/cluster.go:53 +0xa8
Nov 21 11:37:08 davidspi4 k3s[8454]: github.com/rancher/k3s/pkg/daemons/control.prepare(0x37bbe30, 0x5e6bc20, 0x6668b44, 0x5f34dc0, 0x5847fe8, 0x1a)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/pkg/daemons/control/server.go:337 +0xfa8
Nov 21 11:37:08 davidspi4 k3s[8454]: github.com/rancher/k3s/pkg/daemons/control.Server(0x37bbe30, 0x5e6bc20, 0x6668b44, 0x37bbe30, 0x5e6bc20)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/pkg/daemons/control/server.go:83 +0x168
Nov 21 11:37:08 davidspi4 k3s[8454]: github.com/rancher/k3s/pkg/server.StartServer(0x37bbe30, 0x5e6bc20, 0x6668b40, 0x5e6bc20, 0x2)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/pkg/server/server.go:51 +0x70
Nov 21 11:37:08 davidspi4 k3s[8454]: github.com/rancher/k3s/pkg/cli/server.run(0x5cc7ad0, 0x5848a48, 0x1786c8, 0x37b54f0)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/pkg/cli/server/server.go:173 +0xc58
Nov 21 11:37:08 davidspi4 k3s[8454]: github.com/rancher/k3s/pkg/cli/server.Run(0x5cc7ad0, 0x5604a10, 0x0)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/pkg/cli/server/server.go:35 +0x44
Nov 21 11:37:08 davidspi4 k3s[8454]: github.com/rancher/k3s/vendor/github.com/urfave/cli.HandleAction(0x29d5a00, 0x30a7b18, 0x5cc7ad0, 0x5cc7ad0, 0x0)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/vendor/github.com/urfave/cli/app.go:514 +0xac
Nov 21 11:37:08 davidspi4 k3s[8454]: github.com/rancher/k3s/vendor/github.com/urfave/cli.Command.Run(0x2eea1ba, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2f185d7, 0x15, 0x6482f60, ...)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/vendor/github.com/urfave/cli/command.go:171 +0x370
Nov 21 11:37:08 davidspi4 k3s[8454]: github.com/rancher/k3s/vendor/github.com/urfave/cli.(*App).Run(0x5f1b0a0, 0x5c0c0a0, 0x3, 0x4, 0x0, 0x0)
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/vendor/github.com/urfave/cli/app.go:265 +0x510
Nov 21 11:37:08 davidspi4 k3s[8454]: main.main()
Nov 21 11:37:08 davidspi4 k3s[8454]:         /go/src/github.com/rancher/k3s/cmd/server/main.go:46 +0x2ec
Nov 21 11:37:08 davidspi4 systemd[1]: k3s.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 21 11:37:08 davidspi4 systemd[1]: k3s.service: Failed with result 'exit-code'.
Nov 21 11:37:08 davidspi4 systemd[1]: Failed to start Lightweight Kubernetes.
```

**Additional context**
It looks like other panics happen as well (as systemd will keep trying to restart the k3s service) however the content of the panic dump appears the same with only very tiny changes in addresses for 
github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured.(*LogStructured).get()

**Pi3b and any other armhf likely also affected (but not tested).**

**Comment by davidnuzik** [comment]
https://github.com/rancher/k3s/pull/1158#issuecomment-561386174

**Comment by davidnuzik** [comment]
k3s (master) 12/6/19

The panic no longer occurs both on Raspi4 and Raspi3.

However, another issue happens and is tracked here: https://github.com/rancher/k3s/issues/1168 which prevents running master builds of k3s on armhf (or at least running the k3s server).

**Comment by davidnuzik** [comment]
k3s master (12/13/19) (d5929bc8)

Reopening. I'm seeing the issue again. FYI @ibuildthecloud 

```
time="2019-12-13T13:12:53-07:00" level=debug msg="Asset dir /var/lib/rancher/k3s/data/1f75915fd0461208fcebe8d416c12c7c03839d85ec7202caa00ce4787c97752f"
time="2019-12-13T13:12:53-07:00" level=debug msg="Running /var/lib/rancher/k3s/data/1f75915fd0461208fcebe8d416c12c7c03839d85ec7202caa00ce4787c97752f/bin/k3s-server [./k3s-armhf-12-13-19_make --debug server --cluster-init]"
time="2019-12-13T13:12:54.093775686-07:00" level=info msg="Starting k3s d5929bc8 (d5929bc8)"
time="2019-12-13T13:12:54.497589218-07:00" level=info msg="Testing connection to peers [10.20.3.127:6443]"
time="2019-12-13T13:12:54.498531237-07:00" level=debug msg="connected address=10.20.3.127:6443 attempt=0"
time="2019-12-13T13:12:54.500965023-07:00" level=debug msg="connected address=10.20.3.127:6443 attempt=0"
time="2019-12-13T13:12:54.533611986-07:00" level=debug msg="connected address=10.20.3.127:6443 attempt=0"
time="2019-12-13T13:12:54.537085160-07:00" level=debug msg="CREATE /registry/health, size=17, lease=0 => rev=98, err=<nil>"
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/rancher/k3s/vendor/github.com/canonical/go-dqlite/internal/protocol.(*Message).getBlob(0x66aa3bc, 0x0, 0x585d9b8, 0x65d3410)
        /go/src/github.com/rancher/k3s/vendor/github.com/canonical/go-dqlite/internal/protocol/message.go:356 +0x3c
github.com/rancher/k3s/vendor/github.com/canonical/go-dqlite/internal/protocol.(*Rows).Next(0x5f506d4, 0x5dbb140, 0xb, 0xb, 0x7bf5c, 0x978c8c)
        /go/src/github.com/rancher/k3s/vendor/github.com/canonical/go-dqlite/internal/protocol/message.go:557 +0x2ec
github.com/rancher/k3s/vendor/github.com/canonical/go-dqlite/driver.(*Rows).Next(0x5f506c0, 0x5dbb140, 0xb, 0xb, 0x0, 0x0)
        /go/src/github.com/rancher/k3s/vendor/github.com/canonical/go-dqlite/driver/driver.go:585 +0x40
database/sql.(*Rows).nextLocked(0x5e958b0, 0x970000)
        /usr/local/go/src/database/sql/sql.go:2767 +0xb4
database/sql.(*Rows).Next.func1()
        /usr/local/go/src/database/sql/sql.go:2745 +0x2c
database/sql.withLock(0x3795d60, 0x5e958c8, 0x67b704c)
        /usr/local/go/src/database/sql/sql.go:3184 +0x60
database/sql.(*Rows).Next(0x5e958b0, 0x65d3400)
        /usr/local/go/src/database/sql/sql.go:2744 +0x78
github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured/sqllog.RowsToEvents(0x5e958b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured/sqllog/sql.go:221 +0xc8
github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured/sqllog.(*SQLLog).List(0x6604240, 0x37bc010, 0x6287e60, 0x2f04eb9, 0x10, 0x0, 0x0, 0x1, 0x0, 0x0, ...)
        /go/src/github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured/sqllog/sql.go:188 +0xe0
github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured.(*LogStructured).get(0x62c6918, 0x37bc010, 0x6287e60, 0x2f04eb9, 0x10, 0x0, 0x0, 0x675a001, 0x66aa100, 0xa83bb8, ...)
        /go/src/github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured/logstructured.go:55 +0x80
github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured.(*LogStructured).Create(0x62c6918, 0x37bc010, 0x6287e60, 0x2f04eb9, 0x10, 0x643d140, 0x11, 0x11, 0x0, 0x0, ...)
        /go/src/github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured/logstructured.go:88 +0xfc
github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured.(*LogStructured).Start(0x62c6918, 0x37bc010, 0x6287e60, 0x6, 0x6586879)
        /go/src/github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/logstructured/logstructured.go:36 +0xd0
github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/endpoint.Listen(0x37bc010, 0x6287e60, 0x0, 0x0, 0x0, 0x6586870, 0x48, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/rancher/k3s/vendor/github.com/rancher/kine/pkg/endpoint/endpoint.go:58 +0xe4
github.com/rancher/k3s/pkg/cluster.(*Cluster).startStorage(0x64b4000, 0x37bc010, 0x6287e60, 0x0, 0x0)
        /go/src/github.com/rancher/k3s/pkg/cluster/cluster.go:62 +0x60
github.com/rancher/k3s/pkg/cluster.(*Cluster).Start(0x64b4000, 0x37bc010, 0x6287e60, 0x0, 0x0)
        /go/src/github.com/rancher/k3s/pkg/cluster/cluster.go:53 +0xa8
github.com/rancher/k3s/pkg/daemons/control.prepare(0x37bc010, 0x6287e60, 0x6627e64, 0x5f6e2c0, 0x5848280, 0x1a)
        /go/src/github.com/rancher/k3s/pkg/daemons/control/server.go:337 +0xfa8
github.com/rancher/k3s/pkg/daemons/control.Server(0x37bc010, 0x6287e60, 0x6627e64, 0x37bc010, 0x6287e60)
        /go/src/github.com/rancher/k3s/pkg/daemons/control/server.go:83 +0x168
github.com/rancher/k3s/pkg/server.StartServer(0x37bc010, 0x6287e60, 0x6627e60, 0x6287e60, 0x2)
        /go/src/github.com/rancher/k3s/pkg/server/server.go:51 +0x70
github.com/rancher/k3s/pkg/cli/server.run(0x6204d10, 0x5848ce0, 0x1786c8, 0x37b56d0)
        /go/src/github.com/rancher/k3s/pkg/cli/server/server.go:173 +0xc58
github.com/rancher/k3s/pkg/cli/server.Run(0x6204d10, 0x5604a10, 0x0)
        /go/src/github.com/rancher/k3s/pkg/cli/server/server.go:35 +0x44
github.com/rancher/k3s/vendor/github.com/urfave/cli.HandleAction(0x29d5b30, 0x30a7cb4, 0x6204d10, 0x6204d10, 0x0)
        /go/src/github.com/rancher/k3s/vendor/github.com/urfave/cli/app.go:514 +0xac
github.com/rancher/k3s/vendor/github.com/urfave/cli.Command.Run(0x2eea2ea, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2f18707, 0x15, 0x63f51d0, ...)
        /go/src/github.com/rancher/k3s/vendor/github.com/urfave/cli/command.go:171 +0x370
github.com/rancher/k3s/vendor/github.com/urfave/cli.(*App).Run(0x5f1a380, 0x5c0c0a0, 0x4, 0x4, 0x0, 0x0)
        /go/src/github.com/rancher/k3s/vendor/github.com/urfave/cli/app.go:265 +0x510
main.main()
        /go/src/github.com/rancher/k3s/cmd/server/main.go:46 +0x2ec
```

**Steps:**

`K3S_TOKEN=ninjasecret`
`./k3s-armhf-12-13-19_make --debug server --cluster-init 2>&1 | tee /root/debuglogs4_12-13-19_make_dqlite_server.txt`

Raspberry Pi 4 4GB
`uname -a`
`Linux davidspi4 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux`

**Comment by therealgambo** [comment]
I was having the same issue with `v1.0.1` - Rebuilt cluster using `v1.17.0-rc.4-k3s.1` which seems to have fixed it.

**Comment by alexellis** [comment]
Where are we with this @davidnuzik? I lost the thread and notifications since you closed my issue 🤔 

At least one person @therealgambo reported success and also one of the k3sup users on Twitter -> https://twitter.com/Strum355/status/1222326288024817665

I'd like to update my blog post, but don't have much spare time to test this specific setup. https://blog.alexellis.io/multi-master-ha-kubernetes-in-5-minutes/

**Comment by alexellis** [comment]
I'm getting this error consistently, but after several restarts of k3s, it eventually seems to come up.

```
Running: k3sup join
Server IP: 192.168.0.202
ssh -i /home/alex/.ssh/id_rsa -p 22 pi@192.168.0.202
ssh: sudo cat /var/lib/rancher/k3s/server/node-token

K1029f9492096427079d2885639593b562df4518fa9b9abeb1c9ed91f73b386bb08::server:2fef15d338d130f6d264d5bc3676caf7
ssh: curl -sfL https://get.k3s.io/ | K3S_URL='https://192.168.0.202:6443' INSTALL_K3S_EXEC='server --server https://192.168.0.202:6443' K3S_TOKEN='K1029f9492096427079d2885639593b562df4518fa9b9abeb1c9ed91f73b386bb08::server:2fef15d338d130f6d264d5bc3676caf7' INSTALL_K3S_VERSION='v1.17.2+k3s1' sh -s - 
[INFO]  Using v1.17.2+k3s1 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v1.17.2+k3s1/sha256sum-arm.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v1.17.2+k3s1/k3s-armhf
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
Job for k3s.service failed because the control process exited with error code.
See "systemctl status k3s.service" and "journalctl -xe" for details.
Error: unable to setup agent: Process exited with status 1
```

On the device:

```
pi@k5s-204:~ $ sudo journalctl -u k3s -f
-- Logs begin at Thu 2019-02-14 10:12:06 GMT. --
Jan 30 19:58:47 k5s-204 k3s[826]: time="2020-01-30T19:58:47Z" level=info msg="Preparing data dir /var/lib/rancher/k3s/data/39a08c3192d96b9e0e5f20e12690a943b118bfe386f1d3df65a573a7a317787d"
Jan 30 19:59:23 k5s-204 k3s[826]: time="2020-01-30T19:59:23.536582812Z" level=info msg="Starting k3s v1.17.2+k3s1 (cdab19b0)"
Jan 30 19:59:29 k5s-204 k3s[826]: time="2020-01-30T19:59:29.634740719Z" level=info msg="Active TLS secret  (ver=) (count 7): map[listener.cattle.io/cn-10.43.0.1:10.43.0.1 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-192.168.0.204:192.168.0.204 listener.cattle.io/cn-kubernetes:kubernetes listener.cattle.io/cn-kubernetes.default:kubernetes.default listener.cattle.io/cn-kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local listener.cattle.io/cn-localhost:localhost listener.cattle.io/hash:04de8f5174de63ad93152c5a83982a41fcfdcb2e3e79752c8373a0ff36262c74]"
Jan 30 19:59:29 k5s-204 k3s[826]: time="2020-01-30T19:59:29.936474822Z" level=info msg="Joining dqlite cluster as address=192.168.0.204:6443, id=893"
Jan 30 19:59:34 k5s-204 k3s[826]: time="2020-01-30T19:59:34.997874404Z" level=fatal msg="starting kubernetes: preparing server: post join: failed to receive response: failed to receive header: failed to receive header: read unix @00004->@: i/o timeout"
Jan 30 19:59:36 k5s-204 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Jan 30 19:59:36 k5s-204 systemd[1]: k3s.service: Failed with result 'exit-code'.
Jan 30 19:59:36 k5s-204 systemd[1]: Failed to start Lightweight Kubernetes.
Jan 30 19:59:41 k5s-204 systemd[1]: k3s.service: Service RestartSec=5s expired, scheduling restart.
Jan 30 19:59:41 k5s-204 systemd[1]: k3s.service: Scheduled restart job, restart counter is at 1.
Jan 30 19:59:41 k5s-204 systemd[1]: Stopped Lightweight Kubernetes.
Jan 30 19:59:41 k5s-204 systemd[1]: Starting Lightweight Kubernetes...
Jan 30 19:59:42 k5s-204 k3s[859]: time="2020-01-30T19:59:42.930556485Z" level=info msg="Starting k3s v1.17.2+k3s1 (cdab19b0)"
Jan 30 19:59:44 k5s-204 k3s[859]: time="2020-01-30T19:59:44.544875008Z" level=info msg="Testing connection to peers [192.168.0.202:6443 192.168.0.203:6443 192.168.0.204:6443]"
Jan 30 19:59:44 k5s-204 k3s[859]: time="2020-01-30T19:59:44.664263381Z" level=info msg="Connection OK to peers [192.168.0.202:6443 192.168.0.203:6443 192.168.0.204:6443]"
Jan 30 19:59:44 k5s-204 k3s[859]: time="2020-01-30T19:59:44.946021294Z" level=info msg="Kine listening on unix://kine.sock"
```

I wouldn't have expected the error?

**Comment by davidnuzik** [comment]
I will try to bump the priority a tad on this but we currently have numerous other high priority items on our plate. For now leaving this in our v1.17.x milestone which is basically next up when we get present high priority tasks done. This means we'll review the issue further and fix if have time but right now it's not on the immediate radar.

**Comment by dereknola** [comment]
Closing issue as dqlite has been removed from K3s, embedded etcd in now used.
