### ISSUE TITLE
nil pointer dereference in network policy controller

### ISSUE THREAD

**Issue by CertainLach** [k3s-io/k3s#1376]
**Version:**

k3s version v1.17.2+k3s1 (cdab19b0)

**Describe the bug**

```
Jan 31 20:25:23 alpha k3s[384443]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 31 20:25:23 alpha k3s[384443]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2a6b856]
Jan 31 20:25:23 alpha k3s[384443]: goroutine 1 [running]:
Jan 31 20:25:23 alpha k3s[384443]: github.com/rancher/k3s/pkg/agent/netpol.NewNetworkPolicyController(0xc001044f00, 0x486a660, 0xc00130ba20, 0xdf8475800, 0x7ffe697accff, 0x5, 0x0, 0xc001d126d8, 0x1595b0c)
Jan 31 20:25:23 alpha k3s[384443]:         /go/src/github.com/rancher/k3s/pkg/agent/netpol/network_policy_controller.go:1695 +0x266
Jan 31 20:25:23 alpha k3s[384443]: github.com/rancher/k3s/pkg/agent/netpol.Run(0x47bb880, 0xc0009dcd80, 0xc001144700, 0x481a580, 0xc00093ad30)
Jan 31 20:25:23 alpha k3s[384443]:         /go/src/github.com/rancher/k3s/pkg/agent/netpol/network_policy.go:29 +0x183
Jan 31 20:25:23 alpha k3s[384443]: github.com/rancher/k3s/pkg/agent.run(0x47bb880, 0xc0009dcd80, 0xc0009247e0, 0x8a, 0x0, 0x0, 0x0, 0x0, 0xc000e4da40, 0x17, ...)
Jan 31 20:25:23 alpha k3s[384443]:         /go/src/github.com/rancher/k3s/pkg/agent/run.go:79 +0x2b0
Jan 31 20:25:23 alpha k3s[384443]: github.com/rancher/k3s/pkg/agent.Run(0x47bb880, 0xc0009dcd80, 0xc0009247e0, 0x8a, 0x0, 0x0, 0x0, 0x0, 0xc000e4da40, 0x17, ...)
Jan 31 20:25:23 alpha k3s[384443]:         /go/src/github.com/rancher/k3s/pkg/agent/run.go:136 +0x3ef
Jan 31 20:25:23 alpha k3s[384443]: github.com/rancher/k3s/pkg/cli/agent.Run(0xc000ad0580, 0x0, 0xc0004396a0)
Jan 31 20:25:23 alpha k3s[384443]:         /go/src/github.com/rancher/k3s/pkg/cli/agent/agent.go:63 +0x2cc
Jan 31 20:25:23 alpha k3s[384443]: github.com/rancher/k3s/vendor/github.com/urfave/cli.HandleAction(0x37378c0, 0x3fe4478, 0xc000ad0580, 0xc000ad0580, 0x0)
Jan 31 20:25:23 alpha k3s[384443]:         /go/src/github.com/rancher/k3s/vendor/github.com/urfave/cli/app.go:523 +0xbe
Jan 31 20:25:23 alpha k3s[384443]: github.com/rancher/k3s/vendor/github.com/urfave/cli.Command.Run(0x3e1c6f3, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3e344d0, 0xe, 0xc000e4d840, ...)
Jan 31 20:25:23 alpha k3s[384443]:         /go/src/github.com/rancher/k3s/vendor/github.com/urfave/cli/command.go:174 +0x51c
Jan 31 20:25:23 alpha k3s[384443]: github.com/rancher/k3s/vendor/github.com/urfave/cli.(*App).Run(0xc0003c8540, 0xc0000700e0, 0xe, 0xe, 0x0, 0x0)
Jan 31 20:25:23 alpha k3s[384443]:         /go/src/github.com/rancher/k3s/vendor/github.com/urfave/cli/app.go:276 +0x725
Jan 31 20:25:23 alpha k3s[384443]: main.main()
Jan 31 20:25:23 alpha k3s[384443]:         /go/src/github.com/rancher/k3s/cmd/server/main.go:46 +0x56f
```

**To Reproduce**

Appeared on start, was ok after restart, but i think this is still not expected behavior?

**Expected behavior**

No panic

**Actual behavior**

**Additional context**

**Comment by davidnuzik** [comment]
@CertainLach I played around with v1.17.2+k3s1 some on a couple of different environments and don't appear to run into this issue. I'm curious, might you be able to provide a little more info?
For example, what CPU architecture and OS are you using?

What is the command used to run or install K3s?
Thanks!

**Comment by CertainLach** [comment]
@davidnuzik sorry for long answer time

x86_64, on Arch Linux in baremetal environment; Iptables is running in nftables backend mode (Probally this is the reason)
K3s is started pretty normal way, i think 
```sh
/usr/bin/k3s \
        server \
        --tls-san 127.0.0.1 \
        --tls-san 10.255.0.101 \
        --tls-san 10.255.0.102 \
        --tls-san 10.255.0.103 \
        --tls-san boxa \
        --tls-san boxb \
        --tls-san boxc \
        --advertise-address 10.255.0.102 \
        --bind-address 10.255.0.102 \
        --server https://boxa:6443 \
        --data-dir /var/lib/rancher/k3s \
        --node-name boxb \
        --node-ip 10.255.0.102 \
        --node-external-ip 10.255.0.102
```

This happened one time, but now it works for a month without this issue)
