### ISSUE TITLE
Jenkins CICD to K3S

### ISSUE THREAD

**Issue by sirtuxalot** [k3s-io/k3s#1570]
**Version:**

k3s version v1.17.0+k3s.1 (0f644650)

**K3s arguments:**

master: install.sh server
workers (3x): install.sh agent K3S_URL=https://master:6443 K3S_TOKEN="X"

**Describe the bug**

```
Starting Kubernetes deployment
ERROR: ERROR: java.lang.RuntimeException: java.security.cert.CertificateException: java.io.IOException: Incomplete data
hudson.remoting.ProxyException: java.lang.RuntimeException: java.security.cert.CertificateException: java.io.IOException: Incomplete data
	at io.kubernetes.client.openapi.ApiClient.applySslSettings(ApiClient.java:1306)
	at io.kubernetes.client.openapi.ApiClient.setSslCaCert(ApiClient.java:208)
	at io.kubernetes.client.util.ClientBuilder.build(ClientBuilder.java:320)
	at io.kubernetes.client.util.Config.fromConfig(Config.java:97)
	at com.microsoft.jenkins.kubernetes.wrapper.KubernetesClientWrapper.<init>(KubernetesClientWrapper.java:171)
	at com.microsoft.jenkins.kubernetes.KubernetesDeployContext$ClientWrapperFactoryImpl.buildClient(KubernetesDeployContext.java:482)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.doCall(DeploymentCommand.java:143)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.call(DeploymentCommand.java:124)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand$DeploymentTask.call(DeploymentCommand.java:106)
	at hudson.FilePath.act(FilePath.java:1162)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:68)
	at com.microsoft.jenkins.kubernetes.command.DeploymentCommand.execute(DeploymentCommand.java:45)
	at com.microsoft.jenkins.azurecommons.command.CommandService.runCommand(CommandService.java:88)
	at com.microsoft.jenkins.azurecommons.command.CommandService.execute(CommandService.java:96)
	at com.microsoft.jenkins.azurecommons.command.CommandService.executeCommands(CommandService.java:75)
	at com.microsoft.jenkins.azurecommons.command.BaseCommandContext.executeCommands(BaseCommandContext.java:77)
	at com.microsoft.jenkins.kubernetes.KubernetesDeploy.perform(KubernetesDeploy.java:42)
	at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:54)
	at com.microsoft.jenkins.azurecommons.command.SimpleBuildStepExecution.run(SimpleBuildStepExecution.java:35)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: hudson.remoting.ProxyException: java.security.cert.CertificateException: java.io.IOException: Incomplete data
	at java.base/sun.security.provider.X509Factory.engineGenerateCertificates(X509Factory.java:358)
	at java.base/java.security.cert.CertificateFactory.generateCertificates(CertificateFactory.java:478)
	at io.kubernetes.client.openapi.ApiClient.applySslSettings(ApiClient.java:1283)
	... 24 more
Caused by: hudson.remoting.ProxyException: java.io.IOException: Incomplete data
	at java.base/sun.security.provider.X509Factory.readOneBlock(X509Factory.java:614)
	at java.base/sun.security.provider.X509Factory.parseX509orPKCS7Cert(X509Factory.java:449)
	at java.base/sun.security.provider.X509Factory.engineGenerateCertificates(X509Factory.java:356)
	... 26 more
```

**To Reproduce**

1. Configure jenkins, Kubernetes Continuous Deploy Plugin
2. Add credentials to connect to cluster (/etc/rancher/k3s/k3s.yaml)
3. Add step in Jenkinsfile to deploy newly built container to k3s using previously mentioned credentials

**Expected behavior**

New container starts on k3s cluster

**Actual behavior**

Jenkins build errors out at k3s deployment stage with previously mentioned error

**Additional context / logs**

Manual use of kubectl with contents in .kube/config work fine when manually connecting to cluster.  Connection test within Kubernetes section of Jenkins configuration page works fine as well.  So far only when using build process in Jenkinsfile does connection fail.

**Comment by DrumSergio** [comment]
Similar problem here. I believe the plugin is expecting docker, not containerd. I was partly following the instructions here: https://medium.com/@otterwerks/scalable-jenkins-ci-cd-on-bare-metal-arm-kubernetes-c71dfe5645f8 and adapting it to K3s and containerd, but internally the plugin may expect docker instead of containerd. Anyway, I couldn't extract any log because containers inside the pod are in Creating status and the pod ends abruptly.

**Comment by brandond** [comment]
How did you provide the credentials/kubeconfig to the Jenkins plugin? Some light googling suggests that the certificate data isn't in the format that the plugin is expecting.

**Comment by DrumSergio** [comment]
When I test the credentials, it's working. I do not know how have you done it.
As per the blog post I shared earlier, I added a "Secret text" while configuring the cloud, and I pasted the name of the ServiceAccount I created as the "ID", and its secret as the "Secret".

**Comment by DrumSergio** [comment]
Anyway, I have just tried changing everything from containerd to docker inside K3s, changing the sock path too, and it still does not work as intended. The instantiation works, but then the agent pods outputs an error for a second and then fails. Yet I have not managed to get any useful log.

**Comment by sirtuxalot** [comment]
@brandond ,

When I had my cluster setup, I tried several things setup within the plugin from just the hash in the /etc/rancher/k3s/k3s.yaml config file, to the whole thing in clear text, to the whole think encoded, base64 I think, I don't remember its been a while since I last tested.  As I mentioned, I tested the config from my desktop and from my Jenkins VM so I know that the k3s.yaml file was correct.

I am not sure if it matters, but what @DrumSergio is trying to accomplish seems different that my issue.  I am trying to connect my functional Jenkins VM to a functional k3s cluster, while he is attempting to start a Jenkins container on a k3s cluster.  The rest of my container build process is working fine, my failure is deploying the actual created container.

If you could point me in the right direction I would appreciate it, none of my googling turn up anything of value, even when searching for several of the exact strings from my error posted above.  Unfortunately, further testing can be problematic as the cluster is no longer functional and the hardware has been repurposed.  I will try this again, so possible solutions would definitely be appreciated.

Thank you.
