### ISSUE TITLE
k3s unstable on raspberry pi 3b.

### ISSUE THREAD

**Issue by tehcyx** [k3s-io/k3s#1579]
Not sure this is actually considered a problem if pi 3b is not a target platform or if I'm installing it incorrectly by just using the installer script without any parameters but here goes:

**Version:**
```
$ k3s -v
k3s version v1.17.3+k3s1 (5b17a175)
```

**K3s arguments:**
`curl -sfL https://get.k3s.io | sh -`

**Describe the bug**
local-path-provisioner has way to many restarts (220):
```
$ k --kubeconfig=./k8sconfig/k3s.yaml get pods -n kube-system

NAME                                      READY   STATUS      RESTARTS   AGE
helm-install-traefik-6h8b6                0/1     Completed   1          46h
coredns-d798c9dd-l2tqd                    1/1     Running     1          46h
metrics-server-6d684c7b5-g89hn            1/1     Running     1          46h
svclb-traefik-t5qss                       2/2     Running     3          46h
traefik-6787cddb4b-rmqbd                  1/1     Running     19         46h
local-path-provisioner-58fb86bdfd-tljbj   0/1     Error       220        46h
```

**To Reproduce**
Install k3s on raspberry pi 3b

**Expected behavior**
k3s to run more stable

**Actual behavior**
restarts of components

**Additional context / logs**
Logs from local-path-provisioner
```
$ k --kubeconfig=./k8sconfig/k3s.yaml logs -n kube-system local-path-provisioner-58fb86bdfd-tljbj

ERROR: logging before flag.Parse: I0325 18:02:56.625387       1 leaderelection.go:187] attempting to acquire leader lease  kube-system/rancher.io-local-path...
ERROR: logging before flag.Parse: I0325 18:03:14.272888       1 leaderelection.go:196] successfully acquired lease kube-system/rancher.io-local-path
ERROR: logging before flag.Parse: I0325 18:03:14.273920       1 event.go:221] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"rancher.io-local-path", UID:"07fcbd3b-2ae8-4569-b229-9ed93d021eac", APIVersion:"v1", ResourceVersion:"169946", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' local-path-provisioner-58fb86bdfd-tljbj_db109e58-6ec2-11ea-acf6-ee55ca439c11 became leader
ERROR: logging before flag.Parse: I0325 18:03:14.275301       1 controller.go:572] Starting provisioner controller rancher.io/local-path_local-path-provisioner-58fb86bdfd-tljbj_db109e58-6ec2-11ea-acf6-ee55ca439c11!
ERROR: logging before flag.Parse: I0325 18:03:14.488172       1 controller.go:621] Started provisioner controller rancher.io/local-path_local-path-provisioner-58fb86bdfd-tljbj_db109e58-6ec2-11ea-acf6-ee55ca439c11!
ERROR: logging before flag.Parse: I0325 18:14:47.774160       1 leaderelection.go:231] failed to renew lease kube-system/rancher.io-local-path: failed to tryAcquireOrRenew context deadline exceeded
ERROR: logging before flag.Parse: I0325 18:14:47.774523       1 event.go:221] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"rancher.io-local-path", UID:"07fcbd3b-2ae8-4569-b229-9ed93d021eac", APIVersion:"v1", ResourceVersion:"170530", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' local-path-provisioner-58fb86bdfd-tljbj_db109e58-6ec2-11ea-acf6-ee55ca439c11 stopped leading
ERROR: logging before flag.Parse: F0325 18:14:47.774970       1 controller.go:647] leaderelection lost
goroutine 1 [running]:
github.com/rancher/local-path-provisioner/vendor/github.com/golang/glog.stacks(0x1950800, 0x0, 0x45, 0x103)
        /go/src/github.com/rancher/local-path-provisioner/vendor/github.com/golang/glog/glog.go:769 +0x94
github.com/rancher/local-path-provisioner/vendor/github.com/golang/glog.(*loggingT).output(0x19407d8, 0x3, 0x3a92c00, 0x18d2359, 0xd, 0x287, 0x0)
        /go/src/github.com/rancher/local-path-provisioner/vendor/github.com/golang/glog/glog.go:720 +0x2bc
github.com/rancher/local-path-provisioner/vendor/github.com/golang/glog.(*loggingT).printf(0x19407d8, 0x3, 0xd06ac1, 0x13, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/local-path-provisioner/vendor/github.com/golang/glog/glog.go:655 +0x110
github.com/rancher/local-path-provisioner/vendor/github.com/golang/glog.Fatalf(...)
        /go/src/github.com/rancher/local-path-provisioner/vendor/github.com/golang/glog/glog.go:1148
github.com/rancher/local-path-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller.(*ProvisionController).Run.func2()
        /go/src/github.com/rancher/local-path-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:647 +0x4c
github.com/rancher/local-path-provisioner/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run.func1(0x38a6980)
        /go/src/github.com/rancher/local-path-provisioner/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:148 +0x38
github.com/rancher/local-path-provisioner/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0x38a6980, 0xed7bb8, 0x3abff20)
        /go/src/github.com/rancher/local-path-provisioner/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:157 +0xe4
github.com/rancher/local-path-provisioner/vendor/k8s.io/client-go/tools/leaderelection.RunOrDie(0xed7bd8, 0x384003c, 0xedd738, 0x39f2a00, 0x7e11d600, 0x3, 0x540be400, 0x2, 0x77359400, 0x0, ...)
        /go/src/github.com/rancher/local-path-provisioner/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:166 +0x4c
github.com/rancher/local-path-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller.(*ProvisionController).Run(0x3a16700, 0x383edc0)
        /go/src/github.com/rancher/local-path-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:639 +0x264
main.startDaemon(0x38d9180, 0x0, 0x0)
        /go/src/github.com/rancher/local-path-provisioner/main.go:134 +0x5e0
main.StartCmd.func1(0x38d9180)
        /go/src/github.com/rancher/local-path-provisioner/main.go:80 +0x1c
github.com/rancher/local-path-provisioner/vendor/github.com/urfave/cli.HandleAction(0xb8e7d8, 0xd7ec34, 0x38d9180, 0x39b9000, 0x0)
        /go/src/github.com/rancher/local-path-provisioner/vendor/github.com/urfave/cli/app.go:487 +0x64
github.com/rancher/local-path-provisioner/vendor/github.com/urfave/cli.Command.Run(0xcfc4c8, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/rancher/local-path-provisioner/vendor/github.com/urfave/cli/command.go:193 +0x738
github.com/rancher/local-path-provisioner/vendor/github.com/urfave/cli.(*App).Run(0x38d7380, 0x380a140, 0x4, 0x4, 0x0, 0x0)
        /go/src/github.com/rancher/local-path-provisioner/vendor/github.com/urfave/cli/app.go:250 +0x5a4
main.main()
        /go/src/github.com/rancher/local-path-provisioner/main.go:166 +0x1e4
```

**Comment by martinohansen** [comment]
Having the exact same issue on same hardware and version. Let me know if I can help by provide any information.

**Comment by tehcyx** [comment]
@martinohansen which OS are you running? I installed raspbian lite:

```
$ uname -a
Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
```

**Comment by martinohansen** [comment]
> uname -a

```bash
$ uname -a
Linux node1 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
```

**Comment by sachaos** [comment]
I have same issue.

```
$ uname -a
Linux raspi0 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
```

**Comment by cjellick** [comment]
when you say "same issue", do you mean specifically you see the same lead election loss and stack trace for local-path-provisioner?

Is everything else in the cluster stable?

**Comment by sachaos** [comment]
I have the same leaderelection lost problem on the local-path-provisioner.

**Comment by brandond** [comment]
Is this a single-node cluster? What are you using for the datastore?

`leaderelection.go:231] failed to renew lease kube-system/rancher.io-local-path: failed to tryAcquireOrRenew context deadline exceeded`

Generally lease renewal timeouts indicate that the datastore is too slow to respond. What is the load (cpu/memory/disk) on the system when this occurs?

**Comment by sachaos** [comment]
@brandond 

It's single master node cluster with 3 worker nodes.
I'm using 32GB microSD for the datastore. (Is this correct answer as "the datastore"?)

And the load seems not too high for me.
If there is a more appropriate way to investigate, I'd be happy to hear about it.

The following are the results of vmstat and the process logs, and the events for which the local-path-provisioner is down.

## event

```
$ kubectl get pods -w -n kube-system -o wide | ts
...             NAME                                     READY   STATUS      RESTARTS   AGE    IP           NODE     NOMINATED NODE   READINESS GATES
Jul 15 17:31:45 local-path-provisioner-6d59f47c7-n79dp   1/1     Running     414        5d     10.42.0.11   raspi0   <none>           <none>
Jul 15 17:36:28 local-path-provisioner-6d59f47c7-n79dp   0/1     Error       414        5d     10.42.0.11   raspi0   <none>           <none>
Jul 15 17:36:28 local-path-provisioner-6d59f47c7-n79dp   0/1     CrashLoopBackOff   414        5d     10.42.0.11   raspi0   <none>           <none>
Jul 15 17:37:27 local-path-provisioner-6d59f47c7-n79dp   1/1     Running            415        5d     10.42.0.11   raspi0   <none>           <none>
```

## vmstat

```
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu----- -----timestamp-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st                 UTC
 1  0      0 2208180  55776 887660    0    0     0     0 2834 5615  3 12 84  0  0 2020-07-15 17:34:26
 1  0      0 2207912  55776 887660    0    0     0     0 2101 4121  0  3 97  0  0 2020-07-15 17:34:27
 0  0      0 2207928  55776 887656    0    0     0     8 2725 5643  4  5 91  0  0 2020-07-15 17:34:28
 0  0      0 2208180  55776 887656    0    0     0    44 3291 6500  6  4 90  0  0 2020-07-15 17:34:29
 0  0      0 2208204  55776 887656    0    0     0     0 2877 5822  5  3 92  0  0 2020-07-15 17:34:30
 0  0      0 2207920  55776 887656    0    0     0     0 2459 4985  5  2 94  0  0 2020-07-15 17:34:31
 0  0      0 2208172  55776 887656    0    0     0     0 3067 6171  2  3 95  0  0 2020-07-15 17:34:32
 0  0      0 2205896  55776 887656    0    0     0     0 2623 5430  3  2 95  0  0 2020-07-15 17:34:33
 0  0      0 2205904  55776 887656    0    0     0     0 2572 5183  2  2 97  0  0 2020-07-15 17:34:34
 0  0      0 2205652  55776 887660    0    0     0    44 2521 4915  6  3 92  0  0 2020-07-15 17:34:35
 1  0      0 2205316  55776 887660    0    0     0     0 3365 6678  5 16 80  0  0 2020-07-15 17:34:36
 0  0      0 2207448  55776 887664    0    0     0     0 2748 5334  1 23 76  0  0 2020-07-15 17:34:37
 7  0      0 2212584  55776 887548    0    0     0   712 3304 7029  5  2 91  2  0 2020-07-15 17:34:38
 1  0      0 2212616  55776 887480    0    0     0   104 5165 10270 16  4 79  1  0 2020-07-15 17:34:39
```

## process logs

```
$ kubectl logs -p local-path-provisioner-6d59f47c7-n79dp -n kube-system
ERROR: logging before flag.Parse: I0715 17:30:41.297462       1 leaderelection.go:187] attempting to acquire leader lease  kube-system/rancher.io-local-path...
ERROR: logging before flag.Parse: I0715 17:31:02.656925       1 leaderelection.go:196] successfully acquired lease kube-system/rancher.io-local-path
ERROR: logging before flag.Parse: I0715 17:31:02.658005       1 controller.go:572] Starting provisioner controller rancher.io/local-path_local-path-provisioner-6d59f47c7-n79dp_e7c9400c-c6c0-11ea-ba59-fab57a1da257!
ERROR: logging before flag.Parse: I0715 17:31:02.659660       1 event.go:221] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"rancher.io-local-path", UID:"becf6c71-b583-462b-b469-6c28a45a3bf1", APIVersion:"v1", ResourceVersion:"397674", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' local-path-provisioner-6d59f47c7-n79dp_e7c9400c-c6c0-11ea-ba59-fab57a1da257 became leader
ERROR: logging before flag.Parse: I0715 17:31:02.858327       1 controller.go:621] Started provisioner controller rancher.io/local-path_local-path-provisioner-6d59f47c7-n79dp_e7c9400c-c6c0-11ea-ba59-fab57a1da257!
ERROR: logging before flag.Parse: I0715 17:34:37.378175       1 leaderelection.go:231] failed to renew lease kube-system/rancher.io-local-path: failed to tryAcquireOrRenew context deadline exceeded
ERROR: logging before flag.Parse: F0715 17:34:37.378317       1 controller.go:647] leaderelection lost
goroutine 1 [running]:
github.com/rancher/local-path-provisioner/vendor/github.com/golang/glog.stacks(0x1950800, 0x0, 0x45, 0x101)
        /go/src/github.com/rancher/local-path-provisioner/vendor/github.com/golang/glog/glog.go:769 +0x94
github.com/rancher/local-path-provisioner/vendor/github.com/golang/glog.(*loggingT).output(0x19407d8, 0x3, 0x280a180, 0x18d2359, 0xd, 0x287, 0x0)
        /go/src/github.com/rancher/local-path-provisioner/vendor/github.com/golang/glog/glog.go:720 +0x2bc
github.com/rancher/local-path-provisioner/vendor/github.com/golang/glog.(*loggingT).printf(0x19407d8, 0x3, 0xd06ac1, 0x13, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/local-path-provisioner/vendor/github.com/golang/glog/glog.go:655 +0x110
github.com/rancher/local-path-provisioner/vendor/github.com/golang/glog.Fatalf(...)
        /go/src/github.com/rancher/local-path-provisioner/vendor/github.com/golang/glog/glog.go:1148
github.com/rancher/local-path-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller.(*ProvisionController).Run.func2()
        /go/src/github.com/rancher/local-path-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:647 +0x4c
github.com/rancher/local-path-provisioner/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run.func1(0x26ae200)
        /go/src/github.com/rancher/local-path-provisioner/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:148 +0x38
github.com/rancher/local-path-provisioner/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0x26ae200, 0xed7bb8, 0x27246c0)
        /go/src/github.com/rancher/local-path-provisioner/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:157 +0xe4
github.com/rancher/local-path-provisioner/vendor/k8s.io/client-go/tools/leaderelection.RunOrDie(0xed7bd8, 0x244003c, 0xedd738, 0x26d0320, 0x7e11d600, 0x3, 0x540be400, 0x2, 0x77359400, 0x0, ...)
        /go/src/github.com/rancher/local-path-provisioner/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:166 +0x4c
github.com/rancher/local-path-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller.(*ProvisionController).Run(0x24f0620, 0x2532a40)
        /go/src/github.com/rancher/local-path-provisioner/vendor/github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:639 +0x264
main.startDaemon(0x256b0e0, 0x0, 0x0)
        /go/src/github.com/rancher/local-path-provisioner/main.go:134 +0x5e0
main.StartCmd.func1(0x256b0e0)
        /go/src/github.com/rancher/local-path-provisioner/main.go:80 +0x1c
github.com/rancher/local-path-provisioner/vendor/github.com/urfave/cli.HandleAction(0xb8e7d8, 0xd7ec34, 0x256b0e0, 0x260ab00, 0x0)
        /go/src/github.com/rancher/local-path-provisioner/vendor/github.com/urfave/cli/app.go:487 +0x64
github.com/rancher/local-path-provisioner/vendor/github.com/urfave/cli.Command.Run(0xcfc4c8, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/rancher/local-path-provisioner/vendor/github.com/urfave/cli/command.go:193 +0x738
github.com/rancher/local-path-provisioner/vendor/github.com/urfave/cli.(*App).Run(0x2569040, 0x240a140, 0x4, 0x4, 0x0, 0x0)
        /go/src/github.com/rancher/local-path-provisioner/vendor/github.com/urfave/cli/app.go:250 +0x5a4
main.main()
        /go/src/github.com/rancher/local-path-provisioner/main.go:166 +0x1e4
```

**Comment by brandond** [comment]
@sachaos ok, so you're using the built-in sqlite datastore. SD cards vary widely in quality. You might install the sysstat package, and watch your IO statistics for a bit with `iostat -yx 5`.
