### ISSUE TITLE
kube-proxy: "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by amiga23** [k3s-io/k3s#2001]
**Environmental Info:**
K3s Version:

k3s version v1.17.7+k3s1 (b0260b33)
1.17.7 on k3os 0.10.3

Node(s) CPU architecture, OS, and Version: 

Linux node03-worker 5.0.0-43-generic #47~18.04.1 SMP Wed Apr 1 16:27:01 UTC 2020 x86_64 GNU/Linux
k3os Version 0.10.3
Running in KVM on RHEL 7.7
SandyBridge-IBRS
16GB RAM

Cluster Configuration:

- 5 Master / 5 Worker
Running in KVM on RHEL 7.7
SandyBridge-IBRS
16GB RAM

- IPVS enabled as kube-proxy args
```
  k3s_args:
  - agent
  - "--kube-proxy-arg"
  - "proxy-mode=ipvs"
```

**Describe the bug:**

On all master AND worker nodes I do get panics in kube-proxy. See log below.

**Steps To Reproduce:**

- Installed K3os with mariadb as database
- 5 Master / 5 Worker
- IPVS enabled as kube-proxy args
```
  k3s_args:
  - agent
  - "--kube-proxy-arg"
  - "proxy-mode=ipvs"
```

**Expected behavior:**

no panic

**Actual behavior:**

panic

**Additional context / logs:**

Maybe related to IPVS?

```
I0625 07:49:54.823327    2538 config.go:131] Starting endpoints config controller
I0625 07:49:54.823370    2538 shared_informer.go:197] Waiting for caches to sync for endpoints config
I0625 07:49:54.823398    2538 config.go:313] Starting service config controller
I0625 07:49:54.823405    2538 shared_informer.go:197] Waiting for caches to sync for service config
I0625 07:49:54.923660    2538 shared_informer.go:204] Caches are synced for service config 
I0625 07:49:54.923729    2538 shared_informer.go:204] Caches are synced for endpoints config 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x2ac9f38]

goroutine 720 [running]:
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/ipvs.(*Proxier).syncService(0xc00000c3c0, 0xc0011c84a0, 0x1c, 0xc000e18fa0, 0xc000e1e601, 0x7, 0xc000f93fb7)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go:1870 +0x48
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/ipvs.(*Proxier).syncProxyRules(0xc00000c3c0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go:1176 +0xc32
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/ipvs.(*Proxier).OnEndpointsSynced(0xc00000c3c0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go:863 +0x62
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/config.(*EndpointsConfig).Run(0xc001013540, 0xc0000d2840)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/config/config.go:139 +0x108
created by github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-proxy/app.(*ProxyServer).Run
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:688 +0xb78
```

**Comment by amiga23** [comment]
After removing
```
  - "--kube-proxy-arg"
  - "proxy-mode=ipvs"
```
from k3s_args, no panics anymore.

**Comment by brandond** [comment]
Did you get any error messages about ipvs prior to the crash? When enabling it on RHEL7 I see:

```
server_others.go:576] can't determine whether to use ipvs proxy, error: IPVS proxier will not be used because the following required kernel modules are not loaded: [ip_vs ip_vs_rr ip_vs_wrr ip_vs_sh]
```

After loading the required modules I get:

```
server_others.go:173] Using ipvs Proxier.
proxier.go:420] IPVS scheduler not specified, use rr by default
```

This is on a Centos 7 VM running in VirtualBox:
```
CentOS Linux release 7.8.2003 (Core)
Linux centos01.lan.khaus 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by brandond** [comment]
@dweomer I was able to replicate this on a clean install of k3os v0.10.3 running in VirtualBox. I am guessing this is an upstream bug though - it only crashes once, after k3s restarts once appears to stay up.

```
I0709 23:23:37.780831    2485 config.go:131] Starting endpoints config controller
I0709 23:23:37.780850    2485 shared_informer.go:197] Waiting for caches to sync for endpoints config
I0709 23:23:37.881246    2485 shared_informer.go:204] Caches are synced for service config
I0709 23:23:37.881257    2485 shared_informer.go:204] Caches are synced for endpoints config
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x2ac9f38]

goroutine 11108 [running]:
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/ipvs.(*Proxier).syncService(0xc00985c5a0, 0xc002b115e0, 0x19, 0xc00836eaa0, 0xc003b55401, 0x5, 0xc006a0a525)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go:1870 +0x48
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/ipvs.(*Proxier).syncProxyRules(0xc00985c5a0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go:1176 +0xc32
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/ipvs.(*Proxier).OnEndpointsSynced(0xc00985c5a0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go:863 +0x62
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/config.(*EndpointsConfig).Run(0xc00832a240, 0xc0000d2840)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/config/config.go:139 +0x108
created by github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-proxy/app.(*ProxyServer).Run
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:688 +0xb78
```

**Comment by brandond** [comment]
Same issue on v0.11.0-rc1 - crashes once then stays up.

```
I0710 00:12:02.523887    2500 shared_informer.go:230] Caches are synced for endpoints config
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x2bafa28]

goroutine 11600 [running]:
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/ipvs.(*Proxier).syncService(0xc00e8845a0, 0xc006809f20, 0x18, 0xc002b25590, 0xc0079f7701, 0x3, 0xc007c38d7b)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go:1903 +0x48
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/ipvs.(*Proxier).syncProxyRules(0xc00e8845a0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go:1186 +0xcdd
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/ipvs.(*Proxier).OnEndpointsSynced(0xc00e8845a0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go:890 +0x62
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/config.(*EndpointsConfig).Run(0xc00937dd80, 0xc0000c46c0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/proxy/config/config.go:141 +0x108
created by github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-proxy/app.(*ProxyServer).Run
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:701 +0xb7f
```
