### ISSUE TITLE
etcd quorum loss causes crashes with excessive stack trace

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#2309]
K3s Version: 
k3s version v1.19.2+k3s-f698c8e7 (f698c8e7)

Node(s) CPU architecture, OS, and Version: 
Linux centos01.lan.khaus 5.8.10-1.el7.elrepo.x86_64 rancher/k3s#1 SMP Thu Sep 17 10:40:48 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
2 node managed etcd cluster

**Describe the bug:**
Etcd qorum loss causes huge stack traces to be written to log.

**Steps To Reproduce:**
* Install k3s server with --cluster-init
* Join a second node with --server and --token
* Stop k3s on one node
* Other node crashes several seconds later, and prints thousands of lines of stack trace.

**Expected behavior:**
The error should be handled such that we don't dump several thousand lines of stack into the log. It makes it much harder for users to figure out what's actually gone wrong. A nice error message would be great, but we at least shouldn't dump stack.

Not sure this is actually achievable, since the kubernetes codebase calls klog.Fatalf() itself in a bunch of places.

Maybe we can watch etcd, catch the `stepped down to follower since quorum is not active` event, and shut down cleanly before requests time out and cause fatal errors in the Kubernetes code?

**Actual behavior:**
Thousands of lines of goroutine stack traces

**Additional context / logs:**
Whether or not you get a stack trace seems to depend on which controllers are running on the node that is not stopped, and which lease or lock fails to renew first. cloud-controller-manager in particular seems to handle it poorly.

```
2020-09-25 00:47:47.284134 W | rafthttp: lost the TCP streaming connection with peer c257497c9763a334 (stream MsgApp v2 writer)
INFO[2020-09-25T00:47:47.865423360-07:00] Connecting to proxy                           url="wss://10.0.1.170:6443/v1-k3s/connect"
ERRO[2020-09-25T00:47:47.866070606-07:00] Failed to connect to proxy                    error="dial tcp 10.0.1.170:6443: connect: connection refused"
ERRO[2020-09-25T00:47:47.866090593-07:00] Remotedialer proxy error                      error="dial tcp 10.0.1.170:6443: connect: connection refused"
raft2020/09/25 00:47:49 WARN: ad4df066938f2757 stepped down to follower since quorum is not active
raft2020/09/25 00:47:49 INFO: ad4df066938f2757 became follower at term 2
raft2020/09/25 00:47:49 INFO: raft.node: ad4df066938f2757 lost leader ad4df066938f2757 at term 2
DEBU[2020-09-25T00:47:50.805014697-07:00] Wrote ping
INFO[2020-09-25T00:47:52.866179976-07:00] Connecting to proxy                           url="wss://10.0.1.170:6443/v1-k3s/connect"
ERRO[2020-09-25T00:47:52.866865854-07:00] Failed to connect to proxy                    error="dial tcp 10.0.1.170:6443: connect: connection refused"
ERRO[2020-09-25T00:47:52.866883547-07:00] Remotedialer proxy error                      error="dial tcp 10.0.1.170:6443: connect: connection refused"
E0925 00:47:52.880755   12017 leaderelection.go:321] error retrieving resource lock kube-system/cloud-controller-manager: Get "https://127.0.0.1:6444/api/v1/namespaces/kube-system/endpoints/cloud-controller-manager": context deadline exceeded
E0925 00:47:52.880778   12017 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
I0925 00:47:52.880787   12017 leaderelection.go:278] failed to renew lease kube-system/cloud-controller-manager: timed out waiting for the condition
F0925 00:47:52.880798   12017 controllermanager.go:220] leaderelection lost
goroutine 4595 [running]:
github.com/rancher/k3s/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc010c0b040, 0x4c, 0x13d)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).output(0x6e9b300, 0xc000000003, 0x0, 0x0, 0xc018a12f50, 0x6b20244, 0x14, 0xdc, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:945 +0x191
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).printf(0x6e9b300, 0x3, 0x0, 0x0, 0x44ce9f1, 0x13, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:733 +0x17a
github.com/rancher/k3s/vendor/k8s.io/klog/v2.Fatalf(...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1456
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/cloud-controller-manager/app.Run.func2()
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/cloud-controller-manager/app/controllermanager.go:220 +0x73
github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run.func1(0xc0144f47e0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:200 +0x29
github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc0144f47e0, 0x4c27d60, 0xc00f70e040)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:210 +0x15d
github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection.RunOrDie(0x4c27da0, 0xc0000760e0, 0x4c48380, 0xc007afae60, 0x37e11d600, 0x2540be400, 0x77359400, 0xc007afae40, 0x46a4dd8, 0x0, ...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:222 +0x9c
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/cloud-controller-manager/app.Run(0xc01b671368, 0xc0000c6660, 0xc0150741d0, 0x4)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/cloud-controller-manager/app/controllermanager.go:212 +0xbf8
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/cloud-controller-manager/app.NewCloudControllerManagerCommand.func1(0xc007fd98c0, 0xc00a7aa3f0, 0x0, 0x9)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/cloud-controller-manager/app/controllermanager.go:77 +0x20a
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).execute(0xc007fd98c0, 0xc0014ec900, 0x9, 0x10, 0xc007fd98c0, 0xc0014ec900)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc007fd98c0, 0x4, 0x4523474, 0x23)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:887
github.com/rancher/k3s/pkg/daemons/control.cloudControllerManager.func1(0xc000f9c000, 0x4c27d60, 0xc0010fef40, 0xc0014ec900, 0x9, 0x10, 0xc007fd98c0)
	/go/src/github.com/rancher/k3s/pkg/daemons/control/server.go:945 +0x285
created by github.com/rancher/k3s/pkg/daemons/control.cloudControllerManager
	/go/src/github.com/rancher/k3s/pkg/daemons/control/server.go:930 +0x4f8
```

**Comment by ElisaMeng** [comment]
Any progress on this? I rebuild the latest master(including the temporary fix), install it. The first master was struggling a couple of minutes by flooding MBs of logs like this before it get up.  The following node behave the same, even they are new joining. 

Power off all nodes and power on again, all nodes are also flooding with logs like this.

**Comment by brandond** [comment]
You should not get stack traces during normal operation, or when bringing up k3s without quorum. You will definitely get a bunch of output from etcd while it waits for quorum, but the stack trace should only occur on nodes that are left running without quorum. Are you sure what you're seeing is the same?

**Comment by ElisaMeng** [comment]
@brandond Just made a double check, mine looks a little different: 
```
I1003 03:39:36.854997    2866 node_ipam_controller.go:91] Sending events to api server.
time="2020-10-03T03:39:37.680040788+08:00" level=info msg="Waiting for master node master-0 startup: nodes \"master-0\" not found"
time="2020-10-03T03:39:38.692320654+08:00" level=info msg="Waiting for master node master-0 startup: nodes \"master-0\" not found"
2020-10-03 03:39:39.297493 W | etcdserver: read-only range request "key:\"/registry/leases/kube-system/cloud-controller-manager\" " with result "range_response_count:1 size:489" 
took too long (164.592268ms) to execute
time="2020-10-03T03:39:39.695902914+08:00" level=info msg="Waiting for master node master-0 startup: nodes \"master-0\" not found"
E1003 03:39:50.861632    2866 leaderelection.go:321] error retrieving resource lock kube-system/kube-scheduler: Get "https://127.0.0.1:6444/api/v1/namespaces/kube-system/endpoint
s/kube-scheduler?timeout=10s": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
I1003 03:39:50.861757    2866 leaderelection.go:278] failed to renew lease kube-system/kube-scheduler: timed out waiting for the condition
F1003 03:39:50.861787    2866 server.go:199] leaderelection lost
goroutine 4616 [running]:
github.com/rancher/k3s/vendor/k8s.io/klog/v2.stacks(0xc000122001, 0xc0010101c0, 0x41, 0xd5)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).output(0x6e9b380, 0xc000000003, 0x0, 0x0, 0xc0096756c0, 0x6b26d47, 0x9, 0xc7, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:945 +0x191
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).printf(0x6e9b380, 0x3, 0x0, 0x0, 0x44ce9fc, 0x13, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:733 +0x17a
github.com/rancher/k3s/vendor/k8s.io/klog/v2.Fatalf(...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1456
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app.Run.func1()
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:199 +0x73
github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run.func1(0xc004bc78c0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:200 +0x29
github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc004bc78c0, 0x4c27f00, 0xc00f9d9a00)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:210 +0x15d
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app.Run(0x4c27f00, 0xc00abe3e80, 0xc00ba85428, 0xc003728a10, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:207 +0x55c
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app.runCommand(0xc009906840, 0xc0098ce340, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:140 +0x27a
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app.NewSchedulerCommand.func1(0xc009906840, 0xc0069406c0, 0x0, 0x6)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:81 +0x53
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).execute(0xc009906840, 0xc0098d3600, 0x6, 0x8, 0xc009906840, 0xc0098d3600)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc009906840, 0x0, 0xc0096ccea0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:887
github.com/rancher/k3s/pkg/daemons/executor.Embedded.Scheduler.func1(0xc0030fb680, 0xc009906840)
	/go/src/github.com/rancher/k3s/pkg/daemons/executor/embed.go:67 +0x46
created by github.com/rancher/k3s/pkg/daemons/executor.Embedded.Scheduler
	/go/src/github.com/rancher/k3s/pkg/daemons/executor/embed.go:65 +0x90

goroutine 1 [select]:
github.com/rancher/k3s/vendor/google.golang.org/grpc/internal/transport.(*recvBufferReader).readClient(0xc0036d7ae0, 0xc01542d330, 0x5, 0x5, 0x0, 0xc010b04d2a, 0x47)
	/go/src/github.com/rancher/k3s/vendor/google.golang.org/grpc/internal/transport/transport.go:186 +0xd3

```

**Comment by brandond** [comment]
How long after startup is this?

```
I1003 03:39:50.861757    2866 leaderelection.go:278] failed to renew lease kube-system/kube-scheduler: timed out waiting for the condition
F1003 03:39:50.861787    2866 server.go:199] leaderelection lost
```

The only time other than quorum loss that I have ever seen this is when the backing disk is so slow (overloaded) that kine or etcd cannot acknowledge changes in a timely manner. Are you using SSD or rotational storage?

**Comment by plsnotracking** [comment]
@brandond 

```
E1018 07:26:17.083490       1 leaderelection.go:357] Failed to update lock: Put "https://10.43.0.1:443/api/v1/namespaces/kube-system/configmaps/cert-manager-cainjector-leader-election": context deadline exceeded
I1018 07:26:17.083606       1 leaderelection.go:278] failed to renew lease kube-system/cert-manager-cainjector-leader-election: timed out waiting for the condition
E1018 07:26:17.083694       1 start.go:136] cert-manager/ca-injector "msg"="error running manager" "error"="leader election lost"  
```

Not sure but one of my cert managers failed and when I logged to figure out what happened, etcd leader election lost showed up.

Since then I've tried to reboot my pi and the k3s master, but the performance is really poor, even for simple commands like `htop` on the master.

Is there anyway I could help you debug anymore?

**Comment by brandond** [comment]
@plsnotracking can you open a new issue and fill out the issue template? This issue is specifically related to stack traces from multi-server clusters using etcd. That does not appear to describe your situration.

**Comment by hhcalder92** [comment]
@brandond, I am running into a similar stacktrace, perhaps my logs could help. We both seem to get the same `failed to renew lease kube-system/cloud-controller-manager` error. 

I agree an insightful error message and no dump would be great. At first I thought the problem was running embedded etcd on my arm cluster(this issue disproves that theory). Based on #1867,  external databases seem to be the safer router. I prefer not having external dependencies, but I might give it a try.

Let me know if you think this is something different, happy to open a new issue. Thanks in advance! Enjoying K3s thus far!

**Observed Behavior** 
- io wait peaks at ~50%(primarily 3-5 k3s-server processes)
- API crashes happen about every 2-30 minutes depending on the load
- lowering pod load on node-00 and kuberentes API polls help increase the crash interval, but I haven't completely made node-00 unscheduled(seems like it would defeat the purpose of running ha etcd) 
- only pods calling kuberenetes api have runtime issues(because of the timeout)
- trace is enabled so its bit nosier than above(was hoping debug/trace would reveal something obvious)
- had the issue with another minor release, but error still occurs on fresh install of v1.19.5+k3s2 


**Cluster details** 
```
NAME                  STATUS   ROLES         AGE     VERSION            OS-IMAGE                       KERNEL-VERSION   CONTAINER-RUNTIME
raspberrypi-node-00   Ready    etcd,master   4d22h   v1.19.5+k3s2      Raspbian GNU/Linux 10 (buster)   5.4.79-v7l+      containerd://1.4.3-k3s1
raspberrypi-node-01   Ready    etcd,master   4d22h   v1.19.5+k3s2      Raspbian GNU/Linux 10 (buster)   5.4.79-v7l+      containerd://1.4.3-k3s1
raspberrypi-node-02   Ready    etcd,master   4d22h   v1.19.5+k3s2      Raspbian GNU/Linux 10 (buster)   5.4.79-v7l+      containerd://1.4.3-k3s1

$ pdsh -l pi -w raspberrypi-node-0\[0-2\] "uptime"                                                                                                                                                  
raspberrypi-node-02:  21:33:54 up 4 days, 22:43,  0 users,  load average: 3.25, 3.45, 3.84
raspberrypi-node-00:  21:33:54 up 4 days, 22:40,  0 users,  load average: 3.20, 3.64, 4.07
raspberrypi-node-01:  21:33:54 up 4 days, 22:43,  0 users,  load average: 3.52, 4.01, 4.38

$ pdsh -l pi -w raspberrypi-node-0\[0-2\] "free -h"                                                                                                                                                
raspberrypi-node-02:               total        used        free      shared  buff/cache   available
raspberrypi-node-02: Mem:          3.7Gi       1.4Gi       1.0Gi       313Mi       1.4Gi       2.2Gi
raspberrypi-node-02: Swap:            0B          0B          0B
raspberrypi-node-00:               total        used        free      shared  buff/cache   available
raspberrypi-node-00: Mem:          3.7Gi       1.8Gi       345Mi       193Mi       1.6Gi       2.1Gi
raspberrypi-node-00: Swap:            0B          0B          0B
raspberrypi-node-01:               total        used        free      shared  buff/cache   available
raspberrypi-node-01: Mem:          3.7Gi       1.5Gi       1.2Gi       305Mi       1.0Gi       2.2Gi
raspberrypi-node-01: Swap:            0B          0B          0B
```

**logs**
```
Dec 26 20:58:32 raspberrypi-node-00 k3s[23410]: I1226 20:58:32.428361   23410 trace.go:205] Trace[1285872203]: "Get" url:/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cloud-controller-manager,user-agent:k3s/v1.19.5+k3s2 (linux/arm) kubernetes/746cf40/leader-election,client:127.0.0.1 (26-Dec-2020 20:58:30.738) (total time: 1689ms):
Dec 26 20:58:32 raspberrypi-node-00 k3s[23410]: Trace[1285872203]: ---"About to write a response" 1688ms (20:58:00.427)
Dec 26 20:58:32 raspberrypi-node-00 k3s[23410]: Trace[1285872203]: [1.689471189s] [1.689471189s] END
Dec 26 20:58:32 raspberrypi-node-00 k3s[23410]: I1226 20:58:32.432125   23410 trace.go:205] Trace[1893762052]: "Get" url:/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-scheduler,user-agent:k3s/v1.19.5+k3s2 (linux/arm) kubernetes/746cf40/leader-election,client:127.0.0.1 (26-Dec-2020 20:58:30.735) (total time: 1696ms):
Dec 26 20:58:32 raspberrypi-node-00 k3s[23410]: Trace[1893762052]: ---"About to write a response" 1696ms (20:58:00.431)
Dec 26 20:58:32 raspberrypi-node-00 k3s[23410]: Trace[1893762052]: [1.696589329s] [1.696589329s] END
Dec 26 20:58:32 raspberrypi-node-00 k3s[23410]: {"level":"warn","ts":"2020-12-26T20:58:32.769Z","caller":"etcdserver/util.go:163","msg":"apply request took too long","took":"708.754587ms","expected-duration":"100ms","prefix":"","request":"header:<ID:4067725321607973675 username:\"etcd-client\" auth_revision:1 > txn:<compare:<target:MOD key:\"/registry/services/endpoints/kube-system/rancher.io-local-path\" mod_revision:2735058 > success:<request_put:<key:\"/registry/services/endpoints/kube-system/rancher.io-local-path\" value_size:544 >> failure:<>>","response":"size:20"}
Dec 26 20:58:33 raspberrypi-node-00 k3s[23410]: E1226 20:58:33.606765   23410 leaderelection.go:361] Failed to update lock: Put "https://127.0.0.1:6444/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cloud-controller-manager": context deadline exceeded
Dec 26 20:58:33 raspberrypi-node-00 k3s[23410]: I1226 20:58:33.607378   23410 leaderelection.go:278] failed to renew lease kube-system/cloud-controller-manager: timed out waiting for the condition
Dec 26 20:58:33 raspberrypi-node-00 k3s[23410]: F1226 20:58:33.607814   23410 controllermanager.go:220] leaderelection lost
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]: goroutine 5844 [running]:
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.stacks(0x57e6801, 0x0, 0x4c, 0x121)
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:996 +0x94
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).output(0x57d1820, 0x3, 0x0, 0x0, 0x24ddf440, 0x54d9e7f, 0x14, 0xdc, 0x0)
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:945 +0x110
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).printf(0x57d1820, 0x3, 0x0, 0x0, 0x33a38a9, 0x13, 0x0, 0x0, 0x0)
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:733 +0x124
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.Fatalf(...)
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1456
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]: github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/cloud-controller-manager/app.Run.func2()
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/cloud-controller-manager/app/controllermanager.go:220 +0x60
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]: github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run.func1(0xeaa6c00)
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:200 +0x20
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]: github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xeaa6c00, 0x3a58288, 0x2818d8c0)
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:210 +0x11c
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]: github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection.RunOrDie(0x3a582a8, 0x651a014, 0x3a67b30, 0x162e9420, 0x7e11d600, 0x3, 0x540be400, 0x2, 0x77359400, 0x0, ...)
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:222 +0x58
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]: github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/cloud-controller-manager/app.Run(0x119fe248, 0x6501500, 0x11a14950, 0x4)
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/cloud-controller-manager/app/controllermanager.go:212 +0x940
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]: github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/cloud-controller-manager/app.NewCloudControllerManagerCommand.func1(0x1ba1f760, 0x1b2e2b90, 0x0, 0x9)
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/cloud-controller-manager/app/controllermanager.go:77 +0x1a0
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]: github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).execute(0x1ba1f760, 0x14cd5e80, 0x9, 0x10, 0x1ba1f760, 0x14cd5e80)
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]:         /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:846 +0x1e8
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]: github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1ba1f760, 0x4, 0x33f8654, 0x23)
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]:         /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:950 +0x274
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]: github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).Execute(...)
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]:         /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:887
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]: github.com/rancher/k3s/pkg/daemons/control.cloudControllerManager.func1(0x6668000, 0x3a58288, 0x68f7f00, 0x14cd5e80, 0x9, 0x10, 0x1ba1f760)
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]:         /go/src/github.com/rancher/k3s/pkg/daemons/control/server.go:945 +0x208
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]: created by github.com/rancher/k3s/pkg/daemons/control.cloudControllerManager
Dec 26 20:58:35 raspberrypi-node-00 k3s[23410]:         /go/src/github.com/rancher/k3s/pkg/daemons/control/server.go:930 +0x3f4
```

**Near the end** 
```
Dec 26 20:58:39 raspberrypi-node-00 k3s[23410]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/etcd3.(*watchChan).processEvent(0x16bf0310, 0x1783a100)
Dec 26 20:58:39 raspberrypi-node-00 k3s[23410]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.go:257 +0xcc
Dec 26 20:58:39 raspberrypi-node-00 k3s[23410]: created by github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/etcd3.(*watchChan).run
Dec 26 20:58:39 raspberrypi-node-00 k3s[23410]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.go:147 +0x98
Dec 26 20:58:39 raspberrypi-node-00 k3s[23410]: goroutine 4367 [IO wait]:
Dec 26 20:58:39 raspberrypi-node-00 k3s[23410]: internal/poll.runtime_pollWait(0xa260cac8, 0x72, 0x3a29d28)
Dec 26 20:58:39 raspberrypi-node-00 k3s[23410]:         /usr/local/go/src/runtime/netpoll.go:222 +0x44
Dec 26 20:58:39 raspberrypi-node-00 k3s[23410]: internal/poll.(*pollDesc).wait(0x1647dd74, 0x72, 0x3a29d00, 0x5595aa8, 0x0)
Dec 26 20:58:39 raspberrypi-node-00 k3s[23410]:         /usr/local/go/src/internal/poll/fd_
```

**Comment by brandond** [comment]
That's a great sd card test - where'd find that?

**Comment by hhcalder92** [comment]
Yes, specific for Raspberry pi. The test is courtesy of https://github.com/raspberrypi-ui/agnostics. heres how to setup https://gist.github.com/hhcalder92/6415f36ef4ae61dc2eec6e067a41813e

**Comment by caroline-suse-rancher** [comment]
Closing due to age
