### ISSUE TITLE
apiserver panic /api/v1/namespaces/kube-system/endpoints/kube-scheduler and /api/v1/namespaces/cattle-prometheus/events

### ISSUE THREAD

**Issue by dnoland1** [k3s-io/k3s#2709]
**Environmental Info:**
K3s Version: 

v1.18.12+k3s1

Node(s) CPU architecture, OS, and Version: 
2 k3s servers running on Ubuntu 20.04

**Describe the bug:**

Received the following two panics at about the same time:
```
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: E1208 00:18:12.055373  188665 writers.go:105] apiserver was unable to write a JSON response: http: Handler timeout
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: E1208 00:18:12.075291  188665 kuberuntime_sandbox.go:210] ListPodSandbox failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: E1208 00:18:12.082991  188665 generic.go:205] GenericPLEG: Unable to retrieve pods: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: E1208 00:18:12.117574  188665 runtime.go:78] Observed a panic: &errors.errorString{s:"killing connection/stream because serving request timed out and response had been started"} (killing connection/stream because serving request timed out and response had been started)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: goroutine 58387076 [running]:
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x38d2f20, 0xc000681b90)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc01b8f5c90, 0x1, 0x1)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: panic(0x38d2f20, 0xc000681b90)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /usr/local/go/src/runtime/panic.go:679 +0x1b2
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc0230cc7a0, 0xc0509f7e00)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:257 +0x1cf
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc00c869500, 0x48e9820, 0xc02c3ad1f0, 0xc053639a00)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:141 +0x310
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x48e9820, 0xc02c3ad1f0, 0xc053639900)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:59 +0x121
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: net/http.HandlerFunc.ServeHTTP(0xc00c87eb40, 0x48e9820, 0xc02c3ad1f0, 0xc053639900)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x48e9820, 0xc02c3ad1f0, 0xc053639800)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x274
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: net/http.HandlerFunc.ServeHTTP(0xc00c87eb70, 0x48e9820, 0xc02c3ad1f0, 0xc053639800)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithCacheControl.func1(0x48e9820, 0xc02c3ad1f0, 0xc053639800)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters/cachecontrol.go:31 +0xa8
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: net/http.HandlerFunc.ServeHTTP(0xc00c869520, 0x48e9820, 0xc02c3ad1f0, 0xc053639800)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x48dc2a0, 0xc035877cc8, 0xc053639700)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:89 +0x2ca
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: net/http.HandlerFunc.ServeHTTP(0xc00c869540, 0x48dc2a0, 0xc035877cc8, 0xc053639700)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x48dc2a0, 0xc035877cc8, 0xc053639700)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:51 +0x13e
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: net/http.HandlerFunc.ServeHTTP(0xc00c869560, 0x48dc2a0, 0xc035877cc8, 0xc053639700)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc00c87eba0, 0x48dc2a0, 0xc035877cc8, 0xc053639700)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: net/http.serverHandler.ServeHTTP(0xc0091e6620, 0x48dc2a0, 0xc035877cc8, 0xc053639700)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /usr/local/go/src/net/http/server.go:2831 +0xa4
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: net/http.initNPNRequest.ServeHTTP(0x490e7a0, 0xc009bd7440, 0xc01247e000, 0xc0091e6620, 0x48dc2a0, 0xc035877cc8, 0xc053639700)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /usr/local/go/src/net/http/server.go:3395 +0x8d
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc00770a600, 0xc035877cc8, 0xc053639700, 0xc0230cc6e0)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/golang.org/x/net/http2/server.go:2149 +0x9f
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: created by github.com/rancher/k3s/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/golang.org/x/net/http2/server.go:1883 +0x4eb
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: E1208 00:18:10.450130  188665 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, context canceled]
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: E1208 00:18:12.525142  188665 kubelet.go:2177] Container runtime sanity check failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: E1208 00:18:12.701324  188665 writers.go:105] apiserver was unable to write a JSON response: http: Handler timeout
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: E1208 00:18:12.701375  188665 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: I1208 00:18:12.777578  188665 trace.go:116] Trace[1745450598]: "Create" url:/api/v1/namespaces/cattle-prometheus/events,user-agent:k3s/v1.18.12+k3s1 (linux/amd64) kubernetes/56cd363,client:127.0.0.1 (started: 2020-12-08 00:15:16.502143393 +0000 UTC m=+605136.371253647) (total time: 2m56.271162206s):
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: Trace[1745450598]: [2m56.271162206s] [2m56.271052164s] END
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: E1208 00:18:12.777844  188665 runtime.go:78] Observed a panic: &errors.errorString{s:"killing connection/stream because serving request timed out and response had been started"} (killing connection/stream because serving request timed out and response had been started)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: goroutine 58373075 [running]:
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x38d2f20, 0xc000681b90)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc00a1015f8, 0x1, 0x1)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: panic(0x38d2f20, 0xc000681b90)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /usr/local/go/src/runtime/panic.go:679 +0x1b2
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc02f234280, 0xc0331d4dc0)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:257 +0x1cf
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc00c869500, 0x48e9820, 0xc02c3ac700, 0xc05169ee00)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:141 +0x310
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x48e9820, 0xc02c3ac700, 0xc05169ec00)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:59 +0x121
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: net/http.HandlerFunc.ServeHTTP(0xc00c87eb40, 0x48e9820, 0xc02c3ac700, 0xc05169ec00)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x48e9820, 0xc02c3ac700, 0xc05169eb00)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x274
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: net/http.HandlerFunc.ServeHTTP(0xc00c87eb70, 0x48e9820, 0xc02c3ac700, 0xc05169eb00)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithCacheControl.func1(0x48e9820, 0xc02c3ac700, 0xc05169eb00)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters/cachecontrol.go:31 +0xa8
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: net/http.HandlerFunc.ServeHTTP(0xc00c869520, 0x48e9820, 0xc02c3ac700, 0xc05169eb00)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x48ee9e0, 0xc03f841b20, 0xc05169ea00)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:89 +0x2ca
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: net/http.HandlerFunc.ServeHTTP(0xc00c869540, 0x48ee9e0, 0xc03f841b20, 0xc05169ea00)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x48ee9e0, 0xc03f841b20, 0xc05169ea00)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:51 +0x13e
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: net/http.HandlerFunc.ServeHTTP(0xc00c869560, 0x48ee9e0, 0xc03f841b20, 0xc05169ea00)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc00c87eba0, 0x48ee9e0, 0xc03f841b20, 0xc05169ea00)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00271ec00, 0x48ee9e0, 0xc03f841b20, 0xc05169e800)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00271f500, 0x48ee9e0, 0xc03f841b20, 0xc05169e600)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00271f8c0, 0x48ee9e0, 0xc03f841b20, 0xc05169e400)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc00271f980, 0x48ee9e0, 0xc03f841b20, 0xc05169e200)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/pkg/cluster.(*Cluster).router.func1(0x48ee9e0, 0xc03f841b20, 0xc05169e200)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/pkg/cluster/router.go:23 +0x64
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: net/http.HandlerFunc.ServeHTTP(0xc000567690, 0x48ee9e0, 0xc03f841b20, 0xc05169e200)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: github.com/rancher/k3s/pkg/cluster.(*Cluster).getHandler.func1(0x48ee9e0, 0xc03f841b20, 0xc05169e200)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /go/src/github.com/rancher/k3s/pkg/cluster/router.go:12 +0x95
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: net/http.HandlerFunc.ServeHTTP(0xc00076fec0, 0x48ee9e0, 0xc03f841b20, 0xc05169e200)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: net/http.serverHandler.ServeHTTP(0xc000dd20e0, 0x48ee9e0, 0xc03f841b20, 0xc05169e200)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /usr/local/go/src/net/http/server.go:2831 +0xa4
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: net/http.(*conn).serve(0xc052473cc0, 0x490e6e0, 0xc0196833c0)
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /usr/local/go/src/net/http/server.go:1919 +0x875
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: created by net/http.(*Server).Serve
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]:         /usr/local/go/src/net/http/server.go:2957 +0x384
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: E1208 00:18:12.813542  188665 container_log_manager.go:182] Failed to rotate container logs: failed to list containers: rpc error: code = DeadlineExceeded desc = context deadline exce
eded
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: E1208 00:18:12.989151  188665 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
Dec 08 00:18:12 ip-10-10-100-74 k3s[188665]: E1208 00:18:12.989223  188665 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: E1208 00:18:13.040899  188665 writers.go:118] apiserver was unable to write a fallback JSON response: http: Handler timeout
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: time="2020-12-08T00:18:07.938057959Z" level=error msg="WATCH Failed to send cancel response for watchID 328: rpc error: code = Unavailable desc = transport is closing"
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: E1208 00:18:13.250522  188665 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: E1208 00:18:13.255900  188665 wrap.go:39] apiserver panic'd on GET /api/v1/namespaces/kube-system/endpoints/kube-scheduler?timeout=10s
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: E1208 00:18:13.256584  188665 server.go:253] Unable to authenticate the request due to an error: context canceled
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: E1208 00:18:13.265672  188665 secret.go:195] Couldn't get secret cattle-prometheus/alertmanager-cluster-alerting: secret "alertmanager-cluster-alerting" not found
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: E1208 00:18:13.267666  188665 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/secret/427b247c-42b0-4526-bc3f-a16998b38b02-config-volume podName:427b247c-42b0-
4526-bc3f-a16998b38b02 nodeName:}" failed. No retries permitted until 2020-12-08 00:20:15.265831489 +0000 UTC m=+605435.134941733 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"config-volume\" (UniqueN
ame: \"kubernetes.io/secret/427b247c-42b0-4526-bc3f-a16998b38b02-config-volume\") pod \"alertmanager-cluster-alerting-0\" (UID: \"427b247c-42b0-4526-bc3f-a16998b38b02\") : secret \"alertmanager-cluster-alerting\" not found"
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: I1208 00:18:13.268077  188665 log.go:172] http: superfluous response.WriteHeader call from github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1 (w
rap.go:38)
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: E1208 00:18:13.268609  188665 wrap.go:39] apiserver panic'd on POST /api/v1/namespaces/cattle-prometheus/events
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: E1208 00:18:13.330559  188665 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: time="2020-12-08T00:18:07.938254071Z" level=error msg="WATCH Failed to send cancel response for watchID 344: rpc error: code = Unavailable desc = transport is closing"
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: E1208 00:18:13.376479  188665 controller.go:114] loading OpenAPI spec for "v1beta1.metrics.k8s.io" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: Error trying to reach service: 'EOF', Header: map[Content-Type:[text/plain; charset=utf-8] X-Content-Type-Options:[nosniff]]
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: E1208 00:18:13.377300  188665 server.go:253] Unable to authenticate the request due to an error: context canceled
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: I1208 00:18:13.417217  188665 trace.go:116] Trace[2015185551]: "Update" url:/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/external-attacher-leader-ebs-csi-aws-com,user-agent:csi-attacher/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.10.101.173 (started: 2020-12-08 00:15:17.000258567 +0000 UTC m=+605136.869368871) (total time: 2m56.416909472s):
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: Trace[2015185551]: [2m56.416909472s] [2m56.409563467s] END
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: E1208 00:18:13.420592  188665 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, context canceled]
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: E1208 00:18:13.424529  188665 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, context canceled]
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: E1208 00:18:13.436710  188665 authentication.go:53] Unable to authenticate the request due to an error: [invalid bearer token, context canceled]
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: I1208 00:18:13.472787  188665 log.go:172] http: TLS handshake error from 10.10.101.173:2257: EOF
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: time="2020-12-08T00:18:07.938497314Z" level=error msg="WATCH Failed to send cancel response for watchID 331: rpc error: code = Unavailable desc = transport is closing"
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: E1208 00:18:13.520396  188665 writers.go:105] apiserver was unable to write a JSON response: http: Handler timeout
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: time="2020-12-08T00:18:07.938760717Z" level=error msg="WATCH Failed to send cancel response for watchID 338: rpc error: code = Unavailable desc = transport is closing"
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: I1208 00:18:13.588577  188665 log.go:172] http: TLS handshake error from 172.16.2.4:57156: EOF
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: I1208 00:18:13.598881  188665 log.go:172] http: TLS handshake error from 172.16.2.30:57184: EOF
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: time="2020-12-08T00:18:07.939003990Z" level=error msg="WATCH Failed to send cancel response for watchID 335: rpc error: code = Unavailable desc = transport is closing"
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: time="2020-12-08T00:18:07.939444255Z" level=error msg="WATCH Failed to send cancel response for watchID 327: rpc error: code = Unavailable desc = transport is closing"
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: time="2020-12-08T00:18:07.992069361Z" level=info msg="error in remotedialer server [400]: read tcp 10.10.100.74:6443->10.10.101.173:51420: i/o timeout"
Dec 08 00:18:13 ip-10-10-100-74 k3s[188665]: time="2020-12-08T00:18:08.254864303Z" level=error msg="Remotedialer proxy error" error="read tcp 10.10.100.74:40842->10.10.100.74:6443: i/o timeout"
```

**Steps To Reproduce:**
unknown

**Expected behavior:**
no panics

**Actual behavior:**
panics

**Additional context / logs:**
DM me for full logs if needed.

gz#13984

**Comment by fapatel1** [comment]
@dnoland1 is this issue still reoccurring?

**Comment by dnoland1** [comment]
@fapatel1 haven't noticed a recent occurrence.

**Comment by fapatel1** [comment]
@dnoland1 Is it fair to close this issue out and if it reoccurs, we can open up another issue?

**Comment by dnoland1** [comment]
@fapatel1 Up to you. Panic usually indicates a bug where a code path was not correctly handled. Might be worth having the development team assess.

**Comment by brandond** [comment]
The panic was deep in the Kubernetes code and isn't one that I've seen anywhere else, so unless it's an ongoing problem with a non-EOL version I would probably recommend closing it out.

**Comment by cjellick** [comment]
> @fapatel1 Up to you. Panic usually indicates a bug where a code path was not correctly handled. Might be worth having the development team assess.

In this case, the panic is not an incorrectly handled code path, upstream k8s is using it as an escape hatch when a particular request is timed out. They took some care to explain why here: https://github.com/kubernetes/kubernetes/blob/release-1.19/staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go#L245-L257

**Comment by cjellick** [comment]
Per above comments, closing it out.
