### ISSUE TITLE
apiserver panic on /apis/management.cattle.io/v3/catalogs - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dnoland1** [k3s-io/k3s#2710]
**Environmental Info:**
K3s Version: 
v1.18.12+k3s2

Node(s) CPU architecture, OS, and Version: 
2 k3s servers running on Ubuntu 20.04

**Describe the bug:**
Panic observed in logs:
```
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: E1215 18:25:43.908603 1769072 runtime.go:76] Observed a panic: runtime error: invalid memory address or nil pointer dereference
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: goroutine 57116 [running]:
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1(0xc023469860)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:108 +0x107
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: panic(0x394c5c0, 0x6cfc370)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/runtime/panic.go:679 +0x1b2
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: compress/gzip.(*Writer).Write(0xc04e028210, 0x0, 0x0, 0x0, 0xc000185418, 0xc067931670, 0xac218e)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/compress/gzip/gzip.go:168 +0x237
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: compress/gzip.(*Writer).Close(0xc04e028210, 0xac1b56, 0x4853ba0)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/compress/gzip/gzip.go:237 +0x178
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.(*deferredResponseWriter).Close(0xc0651b80f0, 0xc0571caf90, 0xc067931738)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:213 +0x7e
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.SerializeObject(0x3f4bab6, 0x10, 0x7fb9be87a970, 0xc019ae3040, 0x48f0840, 0xc02c1e06c8, 0xc065198d00, 0xc8, 0x48b9a00, 0xc065163ea0)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:120 +0x417
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters.WriteObjectNegotiated(0x48f7740, 0xc012cc8780, 0x48f07c0, 0xc0104401a0, 0xc00aa919e0, 0x14, 0xc00cdc32b8, 0x2, 0x48f0840, 0xc02c1e06c8, ...)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers/responsewriters/writers.go:251 +0x555
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers.transformResponseObject(0x4915a40, 0xc065187230, 0xc0104401a0, 0xc043d1c240, 0xc065198d00, 0x48f0840, 0xc02c1e06c8, 0xc8, 0x0, 0x0, ...)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers/response.go:137 +0x353
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers.ListResource.func1(0x48f0840, 0xc02c1e06c8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/handlers/get.go:276 +0xdfc
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentHandlerFunc.func1(0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:345 +0x237
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: net/http.HandlerFunc.ServeHTTP(0xc06507d800, 0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:59 +0x121
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: net/http.HandlerFunc.ServeHTTP(0xc0651871d0, 0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver.(*crdHandler).ServeHTTP(0xc000709e00, 0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/customresource_handler.go:365 +0x726
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc00c9e6b80, 0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x38a
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc00045fab0, 0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x84
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x3f66a02, 0x17, 0xc001611560, 0xc00045fab0, 0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/handler.go:154 +0x6b1
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc0127bff40, 0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:254 +0x1f5
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc00084c7e0, 0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x84
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x3f457ad, 0xe, 0xc0015393b0, 0xc00084c7e0, 0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/handler.go:154 +0x6b1
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/kube-aggregator/pkg/apiserver.(*proxyHandler).ServeHTTP(0xc00252bab0, 0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go:121 +0x161
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc018508c80, 0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:248 +0x38a
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc00bec04d0, 0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x84
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x3f48e54, 0xf, 0xc00395def0, 0xc00bec04d0, 0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/handler.go:154 +0x6b1
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthorization.func1(0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters/authorization.go:64 +0x512
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: net/http.HandlerFunc.ServeHTTP(0xc0082d1fc0, 0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:160 +0x4de
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: net/http.HandlerFunc.ServeHTTP(0xc00bed1560, 0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithImpersonation.func1(0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters/impersonation.go:50 +0x229a
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: net/http.HandlerFunc.ServeHTTP(0xc008304240, 0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198d00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198b00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:70 +0x5ce
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: net/http.HandlerFunc.ServeHTTP(0xc00be879a0, 0x7fb9bd835d48, 0xc02c1e06b8, 0xc065198b00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc023469860, 0xc00beccae0, 0x4917080, 0xc02c1e06b8, 0xc065198b00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:113 +0xd0
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: created by github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:99 +0x1cb
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: goroutine 56744 [running]:
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x37d8700, 0xc04bbb9670)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc02302f5f8, 0x1, 0x1)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: panic(0x37d8700, 0xc04bbb9670)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/runtime/panic.go:679 +0x1b2
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc00beccae0, 0x48f0a40, 0xc064ffd110, 0xc065198b00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:119 +0x486
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x48f0a40, 0xc064ffd110, 0xc065198a00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:59 +0x121
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: net/http.HandlerFunc.ServeHTTP(0xc00bed1590, 0x48f0a40, 0xc064ffd110, 0xc065198a00)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x48f0a40, 0xc064ffd110, 0xc065198900)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x274
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: net/http.HandlerFunc.ServeHTTP(0xc00bed15c0, 0x48f0a40, 0xc064ffd110, 0xc065198900)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithCacheControl.func1(0x48f0a40, 0xc064ffd110, 0xc065198900)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/endpoints/filters/cachecontrol.go:31 +0xa8
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: net/http.HandlerFunc.ServeHTTP(0xc00beccb00, 0x48f0a40, 0xc064ffd110, 0xc065198900)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x48f5c00, 0xc064bcf960, 0xc065198800)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:89 +0x2ca
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: net/http.HandlerFunc.ServeHTTP(0xc00beccb20, 0x48f5c00, 0xc064bcf960, 0xc065198800)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x48f5c00, 0xc064bcf960, 0xc065198800)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:51 +0x13e
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: net/http.HandlerFunc.ServeHTTP(0xc00beccb40, 0x48f5c00, 0xc064bcf960, 0xc065198800)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc00bed15f0, 0x48f5c00, 0xc064bcf960, 0xc065198800)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc007369200, 0x48f5c00, 0xc064bcf960, 0xc065198600)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc007369500, 0x48f5c00, 0xc064bcf960, 0xc065198400)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0073520c0, 0x48f5c00, 0xc064bcf960, 0xc065198200)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc007352780, 0x48f5c00, 0xc064bcf960, 0xc065198000)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/pkg/cluster.(*Cluster).router.func1(0x48f5c00, 0xc064bcf960, 0xc065198000)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/pkg/cluster/router.go:23 +0x64
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: net/http.HandlerFunc.ServeHTTP(0xc000b48260, 0x48f5c00, 0xc064bcf960, 0xc065198000)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: github.com/rancher/k3s/pkg/cluster.(*Cluster).getHandler.func1(0x48f5c00, 0xc064bcf960, 0xc065198000)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /go/src/github.com/rancher/k3s/pkg/cluster/router.go:12 +0x95
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: net/http.HandlerFunc.ServeHTTP(0xc0007adce0, 0x48f5c00, 0xc064bcf960, 0xc065198000)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/net/http/server.go:2036 +0x44
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: net/http.serverHandler.ServeHTTP(0xc00016c700, 0x48f5c00, 0xc064bcf960, 0xc065198000)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/net/http/server.go:2831 +0xa4
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: net/http.(*conn).serve(0xc045279cc0, 0x4915980, 0xc0650d9380)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/net/http/server.go:1919 +0x875
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: created by net/http.(*Server).Serve
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]:         /usr/local/go/src/net/http/server.go:2957 +0x384
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: I1215 18:25:43.908678 1769072 log.go:172] http: superfluous response.WriteHeader call from github.com/rancher/k3s/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1 (wrap.go:38)
Dec 15 18:25:43 ip-10-10-100-74 k3s[1769072]: E1215 18:25:43.908690 1769072 wrap.go:39] apiserver panic'd on GET /apis/management.cattle.io/v3/catalogs?resourceVersion=165171368&timeout=15m0s
```

**Steps To Reproduce:**
unknown

**Expected behavior:**
no panic

**Actual behavior:**
panic

**Additional context / logs:**
DM me for full logs

gz#13984

**Comment by cjellick** [comment]
not stale. need to investigate

**Comment by brandond** [comment]
v1.18 is EOL

**Comment by cjellick** [comment]
roger that. its tied to a production issue, so i dont want it to auto-close

**Comment by cjellick** [comment]
Closing. This is expected behavior in upsread k8s when encountering a timeout.
