### ISSUE TITLE
DNS issues in 1.19 and 1.20 (regression from 1.18) while installing Sentry helm chart

### ISSUE THREAD

**Issue by jadbaz** [k3s-io/k3s#2766]
**Environmental Info:**
K3s Version: 
```
k3s version v1.20.0+k3s2 (2ea6b163)
go version go1.15.5
```

Node(s) CPU architecture, OS, and Version: 
- Machine: `Linux lsec5009wmsen01 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- OS: CentOS 8

Cluster Configuration:
Single node cluster

**Describe the bug:**
Deploying [Sentry helm chart 8.0.0](https://github.com/sentry-kubernetes/charts/tree/8.0.0) works on 1.18 but fails on 1.19 and 1.20 versions.
On k3s 1.18, the helm chart installs successfully
On 1.19 and 1.20, rabbitmq and kafka crash due to service name resolution issues.
I'm not sure if this is related to Sentry or not. But I think it makes more sense to post it here since the chart itself is working on 1.18.

**Steps To Reproduce:**

- Installed k3s 1.19 and 1.20 on a single node with airgap images. Mainly by placing k3s binary at /usr/bin/k3s, installing airgap images at /var/lib/rancher/k3s/agent/images, installing k3s systemd service and starting it
- Install [Sentry helm chart 8.0.0](https://github.com/sentry-kubernetes/charts/tree/8.0.0):
  - helm repo add sentry https://sentry-kubernetes.github.io/charts
  - helm install sentry/sentry --version 8.0.0

**Expected behavior:**
Helm chart installs successfully

**Actual behavior:**
```
NAMESPACE     NAME                                      READY   STATUS             RESTARTS   AGE
kube-system   local-path-provisioner-7c458769fb-2rb2d   1/1     Running            0          9m43s
kube-system   helm-install-traefik-ck7f2                0/1     Completed          0          9m43s
kube-system   coredns-854c77959c-q5wp5                  1/1     Running            0          9m43s
kube-system   svclb-traefik-g2frk                       2/2     Running            0          9m16s
kube-system   metrics-server-86cbb8457f-vlnxv           1/1     Running            0          9m43s
kube-system   traefik-6f9cbd9bd4-fg5jc                  1/1     Running            0          9m16s
sentry        sentry-snuba-api-78588cbf45-g7r5s         1/1     Running            0          4m35s
sentry        sentry-zookeeper-0                        1/1     Running            0          4m35s
sentry        sentry-sentry-postgresql-0                1/1     Running            0          4m35s
sentry        sentry-sentry-redis-master-0              1/1     Running            0          4m35s
sentry        sentry-clickhouse-0                       1/1     Running            0          4m35s
sentry        sentry-clickhouse-tabix-5564dc468-ppdgv   1/1     Running            0          4m35s
sentry        sentry-clickhouse-replica-2               1/1     Running            0          4m35s
sentry        sentry-clickhouse-replica-0               1/1     Running            0          4m35s
sentry        sentry-clickhouse-replica-1               1/1     Running            0          4m35s
sentry        sentry-clickhouse-1                       1/1     Running            0          4m35s
sentry        sentry-clickhouse-2                       1/1     Running            0          4m35s
sentry        sentry-nginx-79b8cf6989-l2xbt             0/1     CrashLoopBackOff   5          4m35s
sentry        sentry-kafka-0                            0/1     CrashLoopBackOff   4          4m35s
sentry        sentry-kafka-2                            0/1     CrashLoopBackOff   4          4m34s
sentry        sentry-sentry-redis-slave-0               0/1     Running            2          4m35s
sentry        sentry-kafka-1                            0/1     CrashLoopBackOff   4          4m34s
sentry        sentry-rabbitmq-0                         0/1     CrashLoopBackOff   4          4m35s
sentry        sentry-ingest-consumer-7c66c4bb95-m6x8q   0/1     CrashLoopBackOff   3          4m35s
sentry        sentry-cron-56c58d75b7-mj4bg              0/1     CrashLoopBackOff   3          4m35s
sentry        sentry-worker-b66bd8888-pcwj9             0/1     CrashLoopBackOff   3          4m35s
sentry        sentry-web-dcbdbd44b-t5wx8                0/1     CrashLoopBackOff   4          4m35s
```

**Additional context / logs:**
sentry-kafka-0 logs:
```
[2021-01-01 15:36:57,082] ERROR Unable to resolve address: sentry-zookeeper:2181 (org.apache.zookeeper.client.StaticHostProvider)
java.net.UnknownHostException: sentry-zookeeper
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
        at org.apache.zookeeper.client.StaticHostProvider$1.getAllByName(StaticHostProvider.java:92)
        at org.apache.zookeeper.client.StaticHostProvider.resolve(StaticHostProvider.java:147)
        at org.apache.zookeeper.client.StaticHostProvider.next(StaticHostProvider.java:375)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1137)
```

sentry-rabbitmq-0 logs:
```
2021-01-01 15:35:54.888 [info] <0.275.0> Failed to get nodes from k8s - {failed_connect,[{to_address,{"kubernetes.default.svc.cluster.local",443}},
                 {inet,[inet],nxdomain}]}
2021-01-01 15:35:54.889 [error] <0.274.0> CRASH REPORT Process <0.274.0> with 0 neighbours exited with reason: no case clause matching {error,"{failed_connect,[{to_address,{\"kubernetes.default.svc.cluster.local\",443}},\n                 {inet,[inet],nxdomain}]}"} in rabbit_mnesia:init_from_config/0 line 140 in application_master:init/4 line 138
```

**Comment by brandond** [comment]
K3s doesn't modify any of the upstream behavior around pod DNS. Does the chart work out of the box on other distributions of Kubernetes 1.19 or 1.20?

**Comment by jadbaz** [comment]
Ah, I see that 1.19 is not even supported on EKS and barely supported on GKE
So I expect the chart could very well not be supported on 1.19 at all
This makes sense

**Comment by jadbaz** [comment]
Closing this issue as this is probably an issue with the chart
