### ISSUE TITLE
Crash loop after upgrading server from v1.19.7+k3s1 to v1.20.4+k3s1

### ISSUE THREAD

**Issue by GJKrupa** [k3s-io/k3s#3112]
**Environmental Info:**
K3s Version: v1.20.4+k3s1

Node(s) CPU architecture, OS, and Version: 
Linux pi8s-1 5.4.0-1030-raspi #33-Ubuntu SMP PREEMPT Wed Feb 24 11:20:11 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

Cluster Configuration:
1 master, 3 workers

**Describe the bug:**
After starting the upgrade plan, the master node fails to become stable. It goes into a loop where it's Ready for a few seconds and then k3s crashes out.

**Steps To Reproduce:**
Run in the following plan:
```
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: In
      values:
      - "true"
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade:v1.20.4-k3s1-arm64
  version: v1.20.4+k3s
---
# Agent plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/master
      operator: DoesNotExist
  prepare:
    args:
    - prepare
    - server-plan
    image: rancher/k3s-upgrade:v1.20.4-k3s1-arm64
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade
  version: v1.20.4+k3s
```

**Expected behavior:**
The cluster upgrades successfully

**Actual behavior:**
The master node goes into a crash loop

**Additional context / logs:**
There's a huge golang stack trace in the journal log but this appears to be the root cause:
```
Mar 24 17:10:56 pi8s-1 k3s[7358]: F0324 17:10:56.260671    7358 controllermanager.go:168] error building controller context: failed to wait for apiserver being healthy: timed out waiting for the condition: failed to get apiserver /healthz status: an error on the server ("[+]ping ok\n[+]log ok\n[+]etcd ok\n[+]poststarthook/start-kube-apiserver-admission-initializer ok\n[+]poststarthook/generic-apiserver-start-informers ok\n[+]poststarthook/priority-and-fairness-config-consumer ok\n[+]poststarthook/priority-and-fairness-filter ok\n[+]poststarthook/start-apiextensions-informers ok\n[+]poststarthook/start-apiextensions-controllers ok\n[+]poststarthook/crd-informer-synced ok\n[+]poststarthook/bootstrap-controller ok\n[-]poststarthook/rbac/bootstrap-roles failed: reason withheld\n[+]poststarthook/scheduling/bootstrap-system-priority-classes ok\n[+]poststarthook/priority-and-fairness-config-producer ok\n[+]poststarthook/start-cluster-authentication-info-controller ok\n[+]poststarthook/aggregator-reload-proxy-client-cert ok\n[+]poststarthook/start-kube-aggregator-informers ok\n[-]poststarthook/apiservice-registration-controller failed: reason withheld\n[+]poststarthook/apiservice-status-available-controller ok\n[+]poststarthook/kube-apiserver-autoregistration ok\n[+]autoregister-completion ok\n[+]poststarthook/apiservice-openapi-controller ok\nhealthz check failed") has prevented the request from succeeding
Mar 24 17:10:56 pi8s-1 k3s[7358]: goroutine 19145 [running]:
Mar 24 17:10:56 pi8s-1 k3s[7358]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.stacks(0x40001a0001, 0x4018310600, 0x56d, 0x5b4)
Mar 24 17:10:56 pi8s-1 k3s[7358]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1026 +0xac
Mar 24 17:10:56 pi8s-1 k3s[7358]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).output(0x675bac0, 0x4000000003, 0x0, 0x0, 0x401830e230, 0x63d5e24, 0x14, 0xa8, 0x0)
Mar 24 17:10:56 pi8s-1 k3s[7358]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:975 +0x168
Mar 24 17:10:56 pi8s-1 k3s[7358]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).printf(0x675bac0, 0x4000000003, 0x0, 0x0, 0x0, 0x0, 0x3d573c8, 0x25, 0x40182ff4f0, 0x1, ...)
Mar 24 17:10:56 pi8s-1 k3s[7358]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:750 +0x12c
Mar 24 17:10:56 pi8s-1 k3s[7358]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.Fatalf(...)
```

**Comment by GJKrupa** [comment]
Looks like this might be the same as #2425

**Comment by brandond** [comment]
Yes, definitely the same. I haven't had a chance to dig into the upstream code to figure out why the rbac stuff fails on slow systems.

**Comment by GJKrupa** [comment]
OK, closing since it's a duplicate
