### ISSUE TITLE
armhf agent crash

### ISSUE THREAD

**Issue by paleozogt** [k3s-io/k3s#3249]
**Environmental Info:**
K3s Version: 
k3s version v1.20.6+k3s1 (8d043282)
go version go1.16.2

Node(s) CPU architecture, OS, and Version: 
Linux tk1-01 3.10.40-L4T-R21.8-overlayfs-g301ce39-dirty #0 SMP PREEMPT Tue Jun 16 09:05:58 MDT 2020 armv7l armv7l armv7l GNU/Linux

Cluster Configuration:
k3s HA

**Describe the bug:**
Running k3s in agent mode crashes.  This worked in `v1.19.10`.

**Steps To Reproduce:**

- Installed K3s: wget https://github.com/k3s-io/k3s/releases/download/v1.20.6%2Bk3s1/k3s-armhf

**Expected behavior:**
Be able to run k3s agent.

**Actual behavior:**
k3s agent crashes.

**Additional context / logs:**

```
$ sudo k3s-armhf agent --docker --server https://10.208.250.16:6443 --token-file $PWD/node-token
sudo: unable to resolve host apollo-tk1-01
INFO[2021-04-29T15:15:18.967036360-07:00] Starting k3s agent v1.20.6+k3s1 (8d043282)
WARN[2021-04-29T15:15:18.972187277-07:00] Failed to start overlay module
INFO[2021-04-29T15:15:18.972421360-07:00] Module nf_conntrack was already loaded
WARN[2021-04-29T15:15:18.976548943-07:00] Failed to start br_netfilter module
INFO[2021-04-29T15:15:18.981316110-07:00] Running load balancer 127.0.0.1:34517 -> [10.208.250.16:6443 10.208.250.18:6443 10.208.250.17:6443]
WARN[2021-04-29T15:15:19.173078777-07:00] Cluster CA certificate is not trusted by the host CA bundle, but the token does not include a CA hash. Use the full token from the server's node-token file to enable Cluster CA validation.
INFO[2021-04-29T15:15:20.914355526-07:00] Connecting to proxy                           url="wss://10.208.250.16:6443/v1-k3s/connect"
INFO[2021-04-29T15:15:20.915777360-07:00] Connecting to proxy                           url="wss://10.208.250.17:6443/v1-k3s/connect"
INFO[2021-04-29T15:15:20.916555860-07:00] Connecting to proxy                           url="wss://10.208.250.18:6443/v1-k3s/connect"
WARN[2021-04-29T15:15:20.981453360-07:00] Disabling pod PIDs limit feature due to missing cgroup pids support
INFO[2021-04-29T15:15:20.981974443-07:00] Running kubelet --address=0.0.0.0 --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=cgroupfs --cgroups-per-qos=false --client-ca-file=/var/lib/rancher/k3s/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.43.0.10 --cluster-domain=cluster.local --cni-bin-dir=/var/lib/rancher/k3s/data/b8d00507d192f77114eaadf1cd83a6f059572dccdec67315294d197e132b3045/bin --cni-conf-dir=/var/lib/rancher/k3s/agent/etc/cni/net.d --enforce-node-allocatable= --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --feature-gates=SupportPodPidsLimit=false --healthz-bind-address=127.0.0.1 --hostname-override=apollo-tk1-01 --kubeconfig=/var/lib/rancher/k3s/agent/kubelet.kubeconfig --network-plugin=cni --node-labels= --pod-infra-container-image=docker.io/rancher/pause:3.1 --pod-manifest-path=/var/lib/rancher/k3s/agent/pod-manifests --read-only-port=0 --resolv-conf=/etc/resolv.conf --tls-cert-file=/var/lib/rancher/k3s/agent/serving-kubelet.crt --tls-private-key-file=/var/lib/rancher/k3s/agent/serving-kubelet.key
INFO[2021-04-29T15:15:20.985016860-07:00] Running kube-proxy --cluster-cidr=10.42.0.0/16 --healthz-bind-address=127.0.0.1 --hostname-override=apollo-tk1-01 --kubeconfig=/var/lib/rancher/k3s/agent/kubeproxy.kubeconfig --proxy-mode=iptables
Flag --cloud-provider has been deprecated, will be removed in 1.23, in favor of removing cloud provider code from Kubelet.
W0429 15:15:20.995928   26455 server.go:226] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
F0429 15:15:20.997484   26455 server.go:181] cannot set feature gate SupportPodPidsLimit to false, feature is locked to true
goroutine 340 [running]:
github.com/rancher/k3s/vendor/k8s.io/klog/v2.stacks(0x5b0de01, 0x0, 0x7d, 0xcf)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1026 +0x94
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).output(0x5af9f40, 0x3, 0x0, 0x0, 0x6761080, 0x4999e8b, 0x9, 0xb5, 0x210ef00)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:975 +0x110
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x5af9f40, 0x3, 0x0, 0x0, 0x0, 0x0, 0x1, 0x6a11dd8, 0x1, 0x1)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:732 +0x120
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).print(...)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:714
github.com/rancher/k3s/vendor/k8s.io/klog/v2.Fatal(...)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1482
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kubelet/app.NewKubeletCommand.func1(0x614e2c0, 0x5d25a00, 0x1c, 0x20)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kubelet/app/server.go:181 +0x1a4
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).execute(0x614e2c0, 0x5d25a00, 0x1c, 0x20, 0x614e2c0, 0x5d25a00)
        /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:854 +0x1f4
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x614e2c0, 0x6a34420, 0x0, 0x0)
        /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:958 +0x274
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:895
github.com/rancher/k3s/pkg/daemons/executor.Embedded.Kubelet.func1(0x614e2c0)
        /go/src/github.com/rancher/k3s/pkg/daemons/executor/embed.go:31 +0x1c
created by github.com/rancher/k3s/pkg/daemons/executor.Embedded.Kubelet
        /go/src/github.com/rancher/k3s/pkg/daemons/executor/embed.go:30 +0x70

...
```

**Comment by brandond** [comment]
Your kernel appears to be missing some critical cgroups - please run `k3s check-config` and verify you have all the correct things enabled.

```
WARN[2021-04-29T15:15:20.981453360-07:00] Disabling pod PIDs limit feature due to missing cgroup pids support
```

**Comment by paleozogt** [comment]
The crashing is pretty surprising.  Earlier versions seemed to deal with it ok with a fallback:

```
time="2021-04-29T15:19:55.748287461-07:00" level=info msg="Starting k3s agent v1.19.10+k3s1 (72e8196c)"
time="2021-04-29T15:19:55.753073044-07:00" level=warning msg="Failed to start overlay module"
time="2021-04-29T15:19:55.753167627-07:00" level=info msg="Module nf_conntrack was already loaded"
time="2021-04-29T15:19:55.756934877-07:00" level=warning msg="Failed to start br_netfilter module"
time="2021-04-29T15:19:55.761593627-07:00" level=info msg="Running load balancer 127.0.0.1:33558 -> [10.208.250.18:6443 10.208.250.16:6443 10.208.250.17:6443]"
time="2021-04-29T15:19:57.534764044-07:00" level=info msg="Connecting to proxy" url="wss://10.208.250.16:6443/v1-k3s/connect"
time="2021-04-29T15:19:57.535261877-07:00" level=info msg="Connecting to proxy" url="wss://10.208.250.17:6443/v1-k3s/connect"
time="2021-04-29T15:19:57.535509794-07:00" level=info msg="Connecting to proxy" url="wss://10.208.250.18:6443/v1-k3s/connect"
time="2021-04-29T15:19:57.603490377-07:00" level=warning msg="Disabling pod PIDs limit feature due to missing cgroup pids support"
...
```

Since k3s has always worked on this platform, we never felt the need to run check-config.  Here it is:

```
Verifying binaries in /var/lib/rancher/k3s/data/b8d00507d192f77114eaadf1cd83a6f059572dccdec67315294d197e132b3045/bin:
- sha256sum: good
- links: good

System:
- /sbin iptables v1.4.21: older than v1.8
- swap: should be disabled
- routes: default CIDRs 10.42.0.0/16 or 10.43.0.0/16 already routed

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000

info: reading kernel config from /proc/config.gz ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: enabled
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled
- CONFIG_IP_NF_FILTER: enabled
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled
- CONFIG_NETFILTER_XT_MATCH_IPVS: enabled (as module)
- CONFIG_IP_NF_NAT: missing (fail)
- CONFIG_NF_NAT: enabled
- CONFIG_POSIX_MQUEUE: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled

Optional Features:
- CONFIG_USER_NS: missing
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: missing
- CONFIG_MEMCG_KMEM: enabled
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: missing
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_NETPRIO_CGROUP: enabled (as module)
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: enabled
- CONFIG_IP_NF_TARGET_REDIRECT: enabled (as module)
- CONFIG_IP_SET: enabled (as module)
- CONFIG_IP_VS: enabled (as module)
- CONFIG_IP_VS_NFCT: enabled
- CONFIG_IP_VS_PROTO_TCP: enabled
- CONFIG_IP_VS_PROTO_UDP: enabled
- CONFIG_IP_VS_RR: enabled (as module)
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled (as module)
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: enabled
      - CONFIG_CRYPTO_AEAD: enabled
      - CONFIG_CRYPTO_GCM: enabled (as module)
      - CONFIG_CRYPTO_SEQIV: enabled (as module)
      - CONFIG_CRYPTO_GHASH: enabled (as module)
      - CONFIG_XFRM: enabled
      - CONFIG_XFRM_USER: enabled (as module)
      - CONFIG_XFRM_ALGO: enabled
      - CONFIG_INET_ESP: enabled (as module)
      - CONFIG_INET_XFRM_MODE_TRANSPORT: enabled (as module)
- Storage Drivers:
  - "overlay":
    - CONFIG_OVERLAY_FS: missing

STATUS: 1 (fail)
```

**Comment by paleozogt** [comment]
btw, since I'm running with `--docker`, should k3s even care what kernel features are available as long as Docker is happy?

**Comment by brandond** [comment]
The issue is with the kubelet, not docker or contaienrd. Kubernetes 1.19 allowed the SupportPodPidsLimit FeatureGate to be disabled, as of 1.20 it is required to be enabled:

https://kubernetes.io/blog/2020/12/08/kubernetes-1-20-release-announcement/#ga-process-pid-limiting-for-stability
> After being enabled-by-default for a year, SIG Node graduates PID Limits to GA on both SupportNodePidsLimit (node-to-pod PID isolation) and SupportPodPidsLimit (ability to limit PIDs per pod).

The change to require these flags to be enabled was made in: 
https://github.com/kubernetes/kubernetes/pull/94140/files#diff-71e3b98f9a6bbf5b8421e26a7ba0c079f397cd8d49abacdad943c66a4f44f03dR685

**Comment by mcd1992** [comment]
```yaml
k3os:
  k3s_args:
    - agent
    - "--kubelet-arg=feature-gates=SupportPodPidsLimit=true"
```

Lazy workaround for now
