### ISSUE TITLE
Upgrade fails due to cloud-controller rbac resources renamed

### ISSUE THREAD

**Issue by rancher-max** [k3s-io/k3s#3467]
**Environmental Info:**
K3s Version: 

Upgrade from 1.21.1+k3s1 to commitid `8651d6af5feb291d6011b550e6c5a88e0e6f558a` and to commitid: `88f95ec409eeb6a2d1330a836b0d1b960a3b5c31`

Node(s) CPU architecture, OS, and Version: 

Ubuntu 20.04 LTS: `Linux ip-172-31-1-224 5.4.0-1009-aws #9-Ubuntu SMP Sun Apr 12 19:46:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Cluster Configuration:

1 server 1 agent

**Describe the bug:**

When performing a manual upgrade to a commitid with the k3s-cloud-controller-manager RBAC resource rename, pods can get stuck Pending with:
```
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  23m   default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.cloudprovider.kubernetes.io/uninitialized: true}, that the pod didn't tolerate.
  Warning  FailedScheduling  22m   default-scheduler  0/2 nodes are available: 2 node(s) had taint {node.cloudprovider.kubernetes.io/uninitialized: true}, that the pod didn't tolerate.
  Warning  FailedScheduling  23m   default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.cloudprovider.kubernetes.io/uninitialized: true}, that the pod didn't tolerate.
```

And constant repeating logs on the server node: `reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: nodes is forbidden: User "cloud-controller-manager" cannot list resource "nodes" in API group "" at the cluster scope`

**Steps To Reproduce:**

1. Install k3s with external db
2. Upgrade via curl

**Expected behavior:**

Upgrade completes and all pods are up and running

**Additional context / logs:**

Related to: https://github.com/k3s-io/k3s/issues/3308

**Comment by rancher-max** [comment]
Validated by upgrading to master commit `90960ebf4e7a08df075526f411e3afe06731b01e` performing the same steps

**Comment by rancher-max** [comment]
Reopening because actually the upgrade caused the node to go into a constant panic and the cloud-controller resources were not renamed:
```

Sep 10 19:40:44 ip-172-31-9-91 k3s[8526]: I0910 19:40:44.285820    8526 shared_informer.go:240] Waiting for caches to sync for stateful set
Sep 10 19:40:44 ip-172-31-9-91 k3s[8526]: W0910 19:40:44.359932    8526 garbagecollector.go:703] failed to discover some groups: map[admissionregistration.k8s.io/v1beta1:the server could not find the requested resource apiextensions.k8s.io/v1beta1:the server could not find the requested resource authentication.k8s.io/v1beta1:the server could not find the requested resource authorization.k8s.io/v1beta1:the server could not find the requested resource certificates.k8s.io/v1beta1:the server could not find the requested resource coordination.k8s.io/v1beta1:the server could not find the requested resource extensions/v1beta1:the server could not find the requested resource networking.k8s.io/v1beta1:the server could not find the requested resource rbac.authorization.k8s.io/v1beta1:the server could not find the requested resource scheduling.k8s.io/v1beta1:the server could not find the requested resource]
Sep 10 19:40:44 ip-172-31-9-91 k3s[8526]: I0910 19:40:44.386319    8526 node_ipam_controller.go:91] Sending events to api server.
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]: I0910 19:40:45.255834    8526 leaderelection.go:283] failed to renew lease kube-system/cloud-controller-manager: timed out waiting for the condition
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]: F0910 19:40:45.255874    8526 controllermanager.go:234] leaderelection lost
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]: goroutine 13459 [running]:
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.stacks(0xc000122001, 0xc0098cb8c0, 0x4c, 0xa4)
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).output(0x80c4260, 0xc000000003, 0x0, 0x0, 0xc0013a2af0, 0x0, 0x696c4e0, 0x14, 0xea, 0x0)
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:975 +0x1e5
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).printf(0x80c4260, 0x3, 0x0, 0x0, 0x0, 0x0, 0x4ee47b5, 0x13, 0x0, 0x0, ...)
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:753 +0x19a
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]: github.com/rancher/k3s/vendor/k8s.io/klog/v2.Fatalf(...)
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1514
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]: github.com/rancher/k3s/vendor/k8s.io/cloud-provider/app.Run.func3()
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/cloud-provider/app/controllermanager.go:234 +0x8f
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]: github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run.func1(0xc00f522d80)
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:203 +0x29
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]: github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc00f522d80, 0x58d7450, 0xc0170fe540)
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:213 +0x167
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]: github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection.RunOrDie(0x58d7450, 0xc00011e018, 0x58f6ff0, 0xc01231e780, 0x37e11d600, 0x2540be400, 0x77359400, 0xc0141f0280, 0x526d0a8, 0x0, ...)
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:226 +0x9f
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]: github.com/rancher/k3s/vendor/k8s.io/cloud-provider/app.leaderElectAndRun(0xc00cbf42e0, 0xc003850280, 0x33, 0xc01400dd70, 0x4eadde9, 0x6, 0x4efd546, 0x18, 0xc0141f0280, 0x526d0a8, ...)
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/cloud-provider/app/controllermanager.go:465 +0x345
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]: created by github.com/rancher/k3s/vendor/k8s.io/cloud-provider/app.Run
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]:         /go/src/github.com/rancher/k3s/vendor/k8s.io/cloud-provider/app/controllermanager.go:217 +0x8cb
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]: goroutine 1 [chan receive]:
Sep 10 19:40:45 ip-172-31-9-91 k3s[8526]: github.com/rancher/k3s/pkg/agent.run(0x58d7418, 0xc0012c2d80, 0xc009249a40, 0x4e, 0x0, 0x0, 0x0, 0x0, 0xc0077afba8, 0x16, ...)
```

```
# expected values are like 'k3s-cloud-controller-manager'
$ k get clusterroles,clusterrolebindings | grep -i cloud-controller
clusterrole.rbac.authorization.k8s.io/cloud-controller-manager                                               2021-09-10T19:47:16Z
clusterrolebinding.rbac.authorization.k8s.io/cloud-controller-manager                               ClusterRole/cloud-controller-manager                               6s
```

**Comment by rancher-max** [comment]
Above was seen in a two-server setup. After upgrading the second server, the errors were resolved.

However, there may be issues around upgrading to 1.22, so as part of the patch validations I plan on including a more robust set of tests around version upgrading and will open any new issues that arise from that at that time as they are not related to this.
