### ISSUE TITLE
service-cidr / cluster-cidr seems do not work.

### ISSUE THREAD

**Issue by kirbyzhou** [k3s-io/k3s#3489]
**Environmental Info:**
K3s Version: 

k3s version v1.21.1+k3s1 (75dba57f)
go version go1.16.4

Node(s) CPU architecture, OS, and Version: 

Linux centos8.kirbyzhou.hb.ted 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:

1 server

**Describe the bug:**

if I take service-cidr / cluster-cidr options, k3s server refused to work.

**Steps To Reproduce:**

- Installed K3s: 

- /usr/local/bin/k3s-killall.sh
- /usr/local/bin/k3s server --cluster-cidr 10.2.63.0/24 --service-cidr 10.2.63.80/28

**Expected behavior:**

k3s starts, nothing strage happen

**Actual behavior:**

k3s quits with a log of error log.

**Additional context / logs:**
```
E0622 17:31:08.099420 1125202 controller.go:156] Unable to remove old endpoints from kubernetes service: no master IPs were listed in storage, refusing to erase all endpoints for the kubernetes service
E0622 17:31:08.103656 1125202 repair.go:250] the cluster IP [IPv4]:10.43.0.1 for service kubernetes/default is not within the service CIDR 10.2.63.80/28; please recreate
E0622 17:31:08.103721 1125202 repair.go:250] the cluster IP [IPv4]:10.43.137.75 for service metrics-server/kube-system is not within the service CIDR 10.2.63.80/28; please recreate
....
E0622 17:31:08.120224 1125202 repair.go:250] the cluster IP [IPv4]:10.43.0.1 for service kubernetes/default is not within the service CIDR 10.2.63.80/28; please recreate
E0622 17:31:08.120257 1125202 repair.go:250] the cluster IP [IPv4]:10.43.137.75 for service metrics-server/kube-system is not within the service CIDR 10.2.63.80/28; please recreate
...
I0622 17:31:13.238836 1125202 node_ipam_controller.go:91] Sending events to api server.
E0622 17:31:13.719147 1125202 dns.go:126] "Search Line limits exceeded" err="Search Line limits were exceeded, some search paths have been omitted, the applied search line is: kube-system.svc.cluster.local svc.cluster.local cluster.local sogou-op.org nop.vm.sogou-op.org nop.sogou-op.org"
I0622 17:31:23.275809 1125202 range_allocator.go:82] Sending events to api server.
I0622 17:31:23.276230 1125202 range_allocator.go:110] No Service CIDR provided. Skipping filtering out service addresses.
I0622 17:31:23.276248 1125202 range_allocator.go:116] No Secondary Service CIDR provided. Skipping filtering out secondary service addresses.
E0622 17:31:23.276284 1125202 controllermanager.go:562] Error starting "nodeipam"
F0622 17:31:23.276300 1125202 controllermanager.go:223] error starting controllers: failed to mark cidr[10.42.0.0/24] at idx [0] as occupied for node: centos8.kirbyzhou.hb.ted: cidr 10.42.0.0/24 is out the range of cluster cidr 10.2.63.0/24
goroutine 9648 [running]:
github.com/rancher/k3s/vendor/k8s.io/klog/v2.stacks(0xc0001a0001, 0xc011b58000, 0xf1, 0x1e4)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1021 +0xb9
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).output(0x7c0d000, 0xc000000003, 0x0, 0x0, 0xc0006a1030, 0x6419ff0, 0x14, 0xdf, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:970 +0x191
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).printf(0x7c0d000, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x4c38f2a, 0x1e, 0xc0120de290, 0x1, ...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:751 +0x191
github.com/rancher/k3s/vendor/k8s.io/klog/v2.Fatalf(...)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1509
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func1(0x54253f0, 0xc00019c018, 0xc0034af230, 0x4dfcf30)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:223 +0x38c
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.Run(0xc00fb7a758, 0xc000180660, 0xc002021dc8, 0xc0070420a0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:235 +0xcff
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.NewControllerManagerCommand.func2(0xc00b298000, 0xc00ed14000, 0x0, 0x16)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:124 +0x29a
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).execute(0xc00b298000, 0xc00706a400, 0x16, 0x20, 0xc00b298000, 0xc00706a400)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00b298000, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:895
github.com/rancher/k3s/pkg/daemons/executor.Embedded.ControllerManager.func1(0xc003e7de60, 0xc00b298000)
	/go/src/github.com/rancher/k3s/pkg/daemons/executor/embed.go:85 +0x46
created by github.com/rancher/k3s/pkg/daemons/executor.Embedded.ControllerManager
	/go/src/github.com/rancher/k3s/pkg/daemons/executor/embed.go:83 +0x7f

```
[k3s.log](https://github.com/k3s-io/k3s/files/6693032/k3s.log)

**Comment by brandond** [comment]
It appears that you're trying to change the service and cluster CIDR ranges after the cluster has already been brought up once. You should set the cluster and service CIDR ranges on the first startup - if you attempt to change them after the fact, you will see errors like this as services have already been assigned addresses that are no longer within the configured ranges.

**Comment by kirbyzhou** [comment]
So, how can I reset my cluster?

**Comment by brandond** [comment]
It looks like you still have data left from a previous installation, although this should have been removed when you ran the uninstall. When running the install script, did you make sure to prevent it from starting the service before you could modify the configuration?

Also, the default cluster and service CIDRs are /16. If you are going to shrink these way down to /24 or smaller you will need to reduce the cidr masks as well.
