### ISSUE TITLE
K3s fails to start with a flannel crash when using a ppp0 modem interface.

### ISSUE THREAD

**Issue by jswantek** [k3s-io/k3s#3512]
**Environmental Info:**
K3s Version: v1.20.2+k3s1 (1d4adb03)
Go version: go1.15.5

Node(s) CPU architecture, OS, and Version:
`Linux ws-nxcore-000048B02D0766CD 4.9.140-tegra #1 SMP PREEMPT Thu Jun 17 21:46:37 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`

Cluster Configuration: 1 server

**Describe the bug:**
```
I0624 23:06:59.293981   24938 flannel.go:92] Determining IP address of default interface
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a31f90]

goroutine 20887 [running]:
github.com/rancher/k3s/vendor/github.com/vishvananda/netlink.parseAddr(0x400648bdec, 0x40, 0x40, 0x0, 0x400867a0a8, 0x4, 0x280, 0x0, 0x0, 0x400648be00, ...)
        /go/src/github.com/rancher/k3s/vendor/github.com/vishvananda/netlink/addr_linux.go:274 +0x170
github.com/rancher/k3s/vendor/github.com/vishvananda/netlink.(*Handle).AddrList(0x6721590, 0x43eff40, 0x400f0859e0, 0x2, 0x0, 0x4, 0x2bc, 0xfe, 0x1)
        /go/src/github.com/rancher/k3s/vendor/github.com/vishvananda/netlink/addr_linux.go:199 +0x180
github.com/rancher/k3s/vendor/github.com/vishvananda/netlink.AddrList(...)
        /go/src/github.com/rancher/k3s/vendor/github.com/vishvananda/netlink/addr_linux.go:174
github.com/rancher/k3s/vendor/github.com/coreos/flannel/pkg/ip.getIfaceAddrs(0x400e1e22c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/k3s/vendor/github.com/coreos/flannel/pkg/ip/iface.go:36 +0x68
github.com/rancher/k3s/vendor/github.com/coreos/flannel/pkg/ip.GetIfaceIP4Addr(0x400e1e22c0, 0x0, 0x0, 0x400775ee08, 0x1, 0x1)
        /go/src/github.com/rancher/k3s/vendor/github.com/coreos/flannel/pkg/ip/iface.go:40 +0x30
github.com/rancher/k3s/pkg/agent/flannel.LookupExtIface(0x400e1e22c0, 0x75ff34, 0x400cd82f08, 0x75f90c)
        /go/src/github.com/rancher/k3s/pkg/agent/flannel/flannel.go:100 +0xa8
github.com/rancher/k3s/pkg/agent/flannel.flannel(0x444d740, 0x4000e58c00, 0x0, 0x4006a5dd40, 0x34, 0x400b2e43f0, 0x2d, 0x1, 0x0)
        /go/src/github.com/rancher/k3s/pkg/agent/flannel/flannel.go:43 +0x28
github.com/rancher/k3s/pkg/agent/flannel.Run.func1(0x444d740, 0x4000e58c00, 0x4005df4380)
        /go/src/github.com/rancher/k3s/pkg/agent/flannel/setup.go:98 +0x5c
created by github.com/rancher/k3s/pkg/agent/flannel.Run
        /go/src/github.com/rancher/k3s/pkg/agent/flannel/setup.go:97 +0x290
```

The above panic occurs when starting k3s with a ppp0 interface modem connected to the system.

**Steps To Reproduce:**

- Installed K3s: `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.20.2+k3s1 INSTALL_K3S_SKIP_ENABLE=true K3S_CLUSTER_SECRET=<deprecated> sh -`

1. Attach modem to USB port and wait for it to enumerate (have no other internet uplink interfaces)
2. start k3s: `/usr/local/bin/k3s server --disable=traefik`

**Expected behavior:**
It is expected that flannel not panic and k3s to start.

**Actual behavior:**
Flannel panics causing k3s server to fail to start.

**Additional context / logs:**
Looking at the code (https://github.com/k3s-io/k3s/blob/v1.20.2+k3s1/vendor/github.com/vishvananda/netlink/addr_linux.go#L274) it looks as if `dst` is null due to the  `unix.IFA_ADDRESS` case (https://github.com/k3s-io/k3s/blob/v1.20.2+k3s1/vendor/github.com/vishvananda/netlink/addr_linux.go#L237) not being reached.

IP routing table information
```
# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         0.0.0.0         0.0.0.0         U     700    0        0 ppp0
10.31.81.0      0.0.0.0         255.255.255.0   U     101    0        0 lan0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
```

```
ip a
...
9: lan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 70:88:6b:82:d1:53 brd ff:ff:ff:ff:ff:ff
    inet 10.31.81.1/24 brd 10.31.81.255 scope global noprefixroute lan0
       valid_lft forever preferred_lft forever
32: ppp0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 3
    link/ppp
    inet 10.206.144.193/32 brd 10.206.144.193 scope global noprefixroute ppp0
       valid_lft forever preferred_lft foreve
```
^ filtered to only include the interfaces that matter

k3s log: [k3s_flannel_crash_min.txt](https://github.com/k3s-io/k3s/files/6712539/k3s_flannel_crash_min.txt)

**Comment by brandond** [comment]
It looks like this would require a fix upstream at https://github.com/vishvananda/netlink - are you able to open a PR?

**Comment by jswantek** [comment]
Hey @brandond.  Yes I can open an issue against https://github.com/vishvananda/netlink but wasn't exactly sure what you meant by open a PR (pull request)?  I assume that once the fix is issued in https://github.com/vishvananda/netlink to open a PR here to update the netlink module.

**Comment by jswantek** [comment]
I opened a PR for a proposed fix: https://github.com/vishvananda/netlink/pull/665

**Comment by jswantek** [comment]
The proposed solution https://github.com/vishvananda/netlink/pull/665 does address the immediate panic but it was later discovered that lacking an `IFA_ADDRESS` (which can be easily seen using https://github.com/Yourens/rtnetlinkexample/blob/master/if_show.c) results in other downstream problems.

```
Jun 29 21:16:36 ws-nxcore-000048B02D0766CD bash[4543]: E0629 21:16:36.736218    4543 remote_runtime.go:116] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to setup network for sandbox "c246d0f2899b3a6c0e83c2e03fafcebbd5ada9eb54f349c970142127624fb83a": netplugin failed with no error message
Jun 29 21:16:36 ws-nxcore-000048B02D0766CD bash[4543]: E0629 21:16:36.739284    4543 kuberuntime_sandbox.go:70] CreatePodSandbox for pod "coredns-854c77959c-8p7nv_kube-system(0295c50f-8c65-42ef-964e-b97cee322658)" failed: rpc error: code = Unknown desc = failed to setup network for sandbox "c246d0f2899b3a6c0e83c2e03fafcebbd5ada9eb54f349c970142127624fb83a": netplugin failed with no error message
Jun 29 21:16:36 ws-nxcore-000048B02D0766CD bash[4543]: E0629 21:16:36.739356    4543 kuberuntime_manager.go:755] createPodSandbox for pod "coredns-854c77959c-8p7nv_kube-system(0295c50f-8c65-42ef-964e-b97cee322658)" failed: rpc error: code = Unknown desc = failed to setup network for sandbox "c246d0f2899b3a6c0e83c2e03fafcebbd5ada9eb54f349c970142127624fb83a": netplugin failed with no error message
Jun 29 21:16:36 ws-nxcore-000048B02D0766CD bash[4543]: E0629 21:16:36.739554    4543 pod_workers.go:191] Error syncing pod 0295c50f-8c65-42ef-964e-b97cee322658 ("coredns-854c77959c-8p7nv_kube-system(0295c50f-8c65-42ef-964e-b97cee322658)"), skipping: failed to "CreatePodSandbox" for "coredns-854c77959c-8p7nv_kube-system(0295c50f-8c65-42ef-964e-b97cee322658)" with CreatePodSandboxError: "CreatePodSandbox for pod \"coredns-854c77959c-8p7nv_kube-system(0295c50f-8c65-42ef-964e-b97cee322658)\" failed: rpc error: code = Unknown desc = failed to setup network for sandbox \"c246d0f2899b3a6c0e83c2e03fafcebbd5ada9eb54f349c970142127624fb83a\": netplugin failed with no error message"
```

**Comment by brandond** [comment]
Can you work around this by adding a dummy ethernet interface with a static IP?

**Comment by jswantek** [comment]
If the `ppp` interface exists in the system at all the issue persists.  The only way I was able to work-around this issue was with the following:

`/etc/ppp/ip-up.d/01ipfix`
```
#!/bin/bash

PATH=/sbin:/bin:/usr/sbin:/usr/bin
METRIC=700

ip addr del $4 dev $1
ip addr add $4 broadcast $4 dev $1
route add default gw $4 metric $METRIC
```

**Comment by caroline-suse-rancher** [comment]
Closing due to age
