### ISSUE TITLE
Cluster crashed and cannot be restarted

### ISSUE THREAD

**Issue by acherifi** [k3s-io/k3s#3814]
Hi,

Our cluster was running fine until it suddenly crashed and could not get back up. 
The logs mentionned a lot of TLS certificate errors but forcing the renewal didn't do anything. 
Moreover, the cluster can display the pods for 1 seconds before crashing

Changing the --data-dir option makes the cluster operational again however all our pods and PVC don't appear. 

**Environmental Info:**
K3s Version: 
Latest available 

Node(s) CPU architecture, OS, and Version: 
Linux NLAE403PRFDBX01 5.2.21-050221-generic #201910111731 SMP Fri Oct 11 17:34:34 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 18.04

Cluster Configuration:
1 master node

Here is the ouput of journalctl
```
Aug 10 14:00:19 NLAE403PRFDBX01 k3s[23216]: time="2021-08-10T14:00:19.957656676+02:00" level=info msg="Waiting for API server to become available"
Aug 10 14:00:19 NLAE403PRFDBX01 k3s[23216]: time="2021-08-10T14:00:19.958755230+02:00" level=info msg="Running kube-controller-manager --address=127.0.0.1 --allocate-node-cidrs=true --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-kube-apiserver-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --cluster-signing-kube-apiserver-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --cluster-signing-kubelet-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-serving-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --cluster-signing-kubelet-serving-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --cluster-signing-legacy-unknown-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --cluster-signing-legacy-unknown-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --configure-cloud-routes=false --controllers=*,-service,-route,-cloud-node-lifecycle --kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --leader-elect=false --port=10252 --profiling=false --root-ca-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --secure-port=0 --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.key --use-service-account-credentials=true"
Aug 10 14:00:19 NLAE403PRFDBX01 k3s[23216]: time="2021-08-10T14:00:19.960426537+02:00" level=info msg="Running cloud-controller-manager --allocate-node-cidrs=true --bind-address=127.0.0.1 --cloud-provider=k3s --cluster-cidr=10.42.0.0/16 --configure-cloud-routes=false --kubeconfig=/var/lib/rancher/k3s/server/cred/cloud-controller.kubeconfig --leader-elect=false --node-status-update-frequency=1m0s --port=0 --profiling=false"
Aug 10 14:00:19 NLAE403PRFDBX01 k3s[23216]: time="2021-08-10T14:00:19.962864558+02:00" level=info msg="Node token is available at /var/lib/rancher/k3s/server/token"
Aug 10 14:00:19 NLAE403PRFDBX01 k3s[23216]: time="2021-08-10T14:00:19.962931914+02:00" level=info msg="To join node to cluster: k3s agent -s https://XX.XX.XXX:6443 -t ${NODE_TOKEN}"
Aug 10 14:00:19 NLAE403PRFDBX01 k3s[23216]: time="2021-08-10T14:00:19.965019044+02:00" level=info msg="Wrote kubeconfig /etc/rancher/k3s/k3s.yaml"
Aug 10 14:00:19 NLAE403PRFDBX01 k3s[23216]: time="2021-08-10T14:00:19.965068041+02:00" level=info msg="Run: k3s kubectl"
Aug 10 14:00:20 NLAE403PRFDBX01 k3s[23216]: time="2021-08-10T14:00:20.023708534+02:00" level=info msg="Cluster-Http-Server 2021/08/10 14:00:20 http: TLS handshake error from 127.0.0.1:50478: remote error: tls: bad certificate"
Aug 10 14:00:20 NLAE403PRFDBX01 k3s[23216]: time="2021-08-10T14:00:20.030859531+02:00" level=info msg="Cluster-Http-Server 2021/08/10 14:00:20 http: TLS handshake error from 127.0.0.1:50484: remote error: tls: bad certificate"
Aug 10 14:00:20 NLAE403PRFDBX01 k3s[23216]: time="2021-08-10T14:00:20.044953740+02:00" level=info msg="certificate CN=nlae403prfdbx01 signed by CN=k3s-server-ca@1628587583: notBefore=2021-08-10 09:26:23 +0000 UTC notAfter=2022-08-10 12:00:20 +0000 UTC"
Aug 10 14:00:20 NLAE403PRFDBX01 k3s[23216]: time="2021-08-10T14:00:20.049614158+02:00" level=info msg="certificate CN=system:node:nlae403prfdbx01,O=system:nodes signed by CN=k3s-client-ca@1628587583: notBefore=2021-08-10 09:26:23 +0000 UTC notAfter=2022-08-10 12:00:20 +0000 UTC"
Aug 10 14:00:20 NLAE403PRFDBX01 k3s[23216]: time="2021-08-10T14:00:20.198177463+02:00" level=info msg="Module overlay was already loaded"
Aug 10 14:00:20 NLAE403PRFDBX01 k3s[23216]: time="2021-08-10T14:00:20.198240109+02:00" level=info msg="Module nf_conntrack was already loaded"
Aug 10 14:00:20 NLAE403PRFDBX01 k3s[23216]: time="2021-08-10T14:00:20.198276332+02:00" level=info msg="Module br_netfilter was already loaded"
Aug 10 14:00:20 NLAE403PRFDBX01 k3s[23216]: time="2021-08-10T14:00:20.198308290+02:00" level=info msg="Module iptable_nat was already loaded"
Aug 10 14:00:20 NLAE403PRFDBX01 k3s[23216]: time="2021-08-10T14:00:20.219495312+02:00" level=info msg="Logging containerd to /var/lib/rancher/k3s/agent/containerd/containerd.log"
Aug 10 14:00:20 NLAE403PRFDBX01 k3s[23216]: time="2021-08-10T14:00:20.219701850+02:00" level=info msg="Running containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd"
Aug 10 14:00:20 NLAE403PRFDBX01 k3s[23216]: containerd: exit status 2
Aug 10 14:00:20 NLAE403PRFDBX01 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Aug 10 14:00:20 NLAE403PRFDBX01 systemd[1]: k3s.service: Failed with result 'exit-code'.
```
And the output of containerd.log
```
time="2021-08-10T14:09:09.831615082+02:00" level=info msg="Start cri plugin with config {PluginConfig:{ContainerdConfig:{Snapshotter:overlayfs DefaultRuntimeName:runc DefaultRuntime:{Type: Engine: PodAnnotations:[] ContainerAnnotations:[] Root: Options:<nil> PrivilegedWithoutHostDevices:false BaseRuntimeSpec:} UntrustedWorkloadRuntime:{Type: Engine: PodAnnotations:[] ContainerAnnotations:[] Root: Options:<nil> PrivilegedWithoutHostDevices:false BaseRuntimeSpec:} Runtimes:map[runc:{Type:io.containerd.runc.v2 Engine: PodAnnotations:[] ContainerAnnotations:[] Root: Options:<nil> PrivilegedWithoutHostDevices:false BaseRuntimeSpec:}] NoPivot:false DisableSnapshotAnnotations:true DiscardUnpackedLayers:false} CniConfig:{NetworkPluginBinDir:/var/lib/rancher/k3s/data/9df574741d2573cbbe6616e8624488b36b3340d077bc50da7cb167f1b08a64d1/bin NetworkPluginConfDir:/var/lib/rancher/k3s/agent/etc/cni/net.d NetworkPluginMaxConfNum:1 NetworkPluginConfTemplate:} Registry:{Mirrors:map[docker.io:{Endpoints:[https://registry-1.docker.io] Rewrites:map[]}] Configs:map[] Auths:map[] Headers:map[]} ImageDecryption:{KeyModel:} DisableTCPService:true StreamServerAddress:127.0.0.1 StreamServerPort:10010 StreamIdleTimeout:4h0m0s EnableSelinux:false SelinuxCategoryRange:1024 SandboxImage:rancher/pause:3.1 StatsCollectPeriod:10 SystemdCgroup:false EnableTLSStreaming:false X509KeyPairStreaming:{TLSCertFile: TLSKeyFile:} MaxContainerLogLineSize:16384 DisableCgroup:false DisableApparmor:false RestrictOOMScoreAdj:false MaxConcurrentDownloads:3 DisableProcMount:false UnsetSeccompProfile: TolerateMissingHugetlbController:true DisableHugetlbController:true IgnoreImageDefinedVolumes:false} ContainerdRootDir:/var/lib/rancher/k3s/agent/containerd ContainerdEndpoint:/run/k3s/containerd/containerd.sock RootDir:/var/lib/rancher/k3s/agent/containerd/io.containerd.grpc.v1.cri StateDir:/run/k3s/containerd/io.containerd.grpc.v1.cri}"
time="2021-08-10T14:09:09.831699665+02:00" level=info msg="Connect containerd service"
time="2021-08-10T14:09:09.831778011+02:00" level=info msg="Get image filesystem path \"/var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs\""
time="2021-08-10T14:09:09.832541490+02:00" level=info msg="loading plugin \"io.containerd.grpc.v1.introspection\"..." type=io.containerd.grpc.v1
time="2021-08-10T14:09:09.832625505+02:00" level=info msg="Start subscribing containerd event"
time="2021-08-10T14:09:09.832717241+02:00" level=info msg="Start recovering state"
time="2021-08-10T14:09:09.832984710+02:00" level=info msg=serving... address=/run/k3s/containerd/containerd.sock.ttrpc
time="2021-08-10T14:09:09.833118859+02:00" level=info msg=serving... address=/run/k3s/containerd/containerd.sock
time="2021-08-10T14:09:09.833170187+02:00" level=info msg="containerd successfully booted in 0.031944s"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1a0ff37]

goroutine 205 [running]:
github.com/rancher/k3s/vendor/go.etcd.io/bbolt.(*Bucket).Bucket(0x0, 0x797461c, 0x6, 0x6, 0xc0017e0378)
	/go/src/github.com/rancher/k3s/vendor/go.etcd.io/bbolt/bucket.go:97 +0x37
github.com/rancher/k3s/vendor/github.com/containerd/containerd/metadata.isRootRef(0x0, 0x7f740e6c91a7)
	/go/src/github.com/rancher/k3s/vendor/github.com/containerd/containerd/metadata/gc.go:496 +0x53
github.com/rancher/k3s/vendor/github.com/containerd/containerd/metadata.scanRoots.func7.1(0x7f740e6c91a7, 0x3dc, 0x3dc, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/github.com/containerd/containerd/metadata/gc.go:267 +0xa5
github.com/rancher/k3s/vendor/go.etcd.io/bbolt.(*Bucket).ForEach(0xc001f5e900, 0xc001c01490, 0x9, 0x9)
	/go/src/github.com/rancher/k3s/vendor/go.etcd.io/bbolt/bucket.go:390 +0x103
github.com/rancher/k3s/vendor/github.com/containerd/containerd/metadata.scanRoots.func7(0x7f740e6cb020, 0x9, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/github.com/containerd/containerd/metadata/gc.go:263 +0x12b
github.com/rancher/k3s/vendor/go.etcd.io/bbolt.(*Bucket).ForEach(0xc001f5e880, 0xc001c01630, 0x9, 0x9)
	/go/src/github.com/rancher/k3s/vendor/go.etcd.io/bbolt/bucket.go:390 +0x103
github.com/rancher/k3s/vendor/github.com/containerd/containerd/metadata.scanRoots(0x547acd8, 0xc001c66000, 0xc0008d0000, 0xc00159a000, 0xc000d5c000, 0x0)
	/go/src/github.com/rancher/k3s/vendor/github.com/containerd/containerd/metadata/gc.go:257 +0x3ff
github.com/rancher/k3s/vendor/github.com/containerd/containerd/metadata.(*DB).getMarked.func1(0xc0008d0000, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/github.com/containerd/containerd/metadata/db.go:384 +0x16e
github.com/rancher/k3s/vendor/go.etcd.io/bbolt.(*DB).View(0xc001a26400, 0xc001c0e890, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/go.etcd.io/bbolt/db.go:725 +0x93
github.com/rancher/k3s/vendor/github.com/containerd/containerd/metadata.(*DB).getMarked(0xc0002dae00, 0x547ad10, 0xc000124010, 0x203000, 0x203000, 0x7f74107c7f60)
	/go/src/github.com/rancher/k3s/vendor/github.com/containerd/containerd/metadata/db.go:367 +0x7c
github.com/rancher/k3s/vendor/github.com/containerd/containerd/metadata.(*DB).GarbageCollect(0xc0002dae00, 0x547ad10, 0xc000124010, 0x0, 0x3, 0x1, 0x2)
	/go/src/github.com/rancher/k3s/vendor/github.com/containerd/containerd/metadata/db.go:284 +0xa5
github.com/rancher/k3s/vendor/github.com/containerd/containerd/gc/scheduler.(*gcScheduler).run(0xc000b36900, 0x547ad10, 0xc000124010)
	/go/src/github.com/rancher/k3s/vendor/github.com/containerd/containerd/gc/scheduler/scheduler.go:310 +0x4bf
created by github.com/rancher/k3s/vendor/github.com/containerd/containerd/gc/scheduler.init.0.func1
	/go/src/github.com/rancher/k3s/vendor/github.com/containerd/containerd/gc/scheduler/scheduler.go:132 +0x445
```

**Comment by brandond** [comment]
It looks like your containerd metadata store has been corrupted. You'll might be able to get up and running again by stopping K3s, running k3s-killall.sh, and deleting `/var/lib/rancher/rke2/agent/containerd/` - but you will definitely lose any running pods.

**Comment by acherifi** [comment]
Thank you for the answer. We restored a snapshot of the machine so everyhting is good now. I will keep the solution in my bookmarks just in case.
