### ISSUE TITLE
Containerd crashes when built with Kubernetes 1.22 libraries

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3895]
Kubernetes 1.22 requires grpc 1.32.0 or newer due to the addition of opentelemetry support. Containerd uses ttrpc which in turn requires grpc 1.27.0 due to its use of gogo/protobuf. This is explored in more depth  at https://github.com/containerd/ttrpc/issues/62#issuecomment-686768932.

The takeaway is that it doesn't appear to be possible to successfully run both containerd and kubernetes out of the same binary until containerd/ttrpc is updated to use modern grpc versions. https://github.com/containerd/containerd/pull/5613 updates the module versions in containerd, but ttrpc itself still uses the deprecated libraries.

I have a [fork of containerd 1.5](https://github.com/brandond/containerd/commits/k3s-release/1.5) that I am working on, with some module updates backported from main to improve Kubernetes 1.22 compatibility, but the underlying ttrpc issue remains.

```console
panic: protobuf tag not enough fields in Status.state:

goroutine 2822 [running]:
github.com/rancher/k3s/vendor/github.com/gogo/protobuf/proto.(*unmarshalInfo).computeUnmarshalInfo(0xc000525540)
        /go/src/github.com/rancher/k3s/vendor/github.com/gogo/protobuf/proto/table_unmarshal.go:341 +0x1897
github.com/rancher/k3s/vendor/github.com/gogo/protobuf/proto.(*unmarshalInfo).unmarshal(0xc000525540, 0xc002cc9680, 0xc002574002, 0x27, 0x753, 0xc0027f2180, 0xc002574002)
        /go/src/github.com/rancher/k3s/vendor/github.com/gogo/protobuf/proto/table_unmarshal.go:138 +0xf65
github.com/rancher/k3s/vendor/github.com/gogo/protobuf/proto.makeUnmarshalMessagePtr.func1(0xc002574002, 0x27, 0x754, 0xc003ce55e0, 0x2, 0xc002574010, 0x0, 0x745, 0x0, 0x0)
        /go/src/github.com/rancher/k3s/vendor/github.com/gogo/protobuf/proto/table_unmarshal.go:1826 +0x12b
github.com/rancher/k3s/vendor/github.com/gogo/protobuf/proto.(*unmarshalInfo).unmarshal(0xc0005254a0, 0xc003ce55e0, 0xc002574000, 0x29, 0x755, 0x40fb98, 0x20)
        /go/src/github.com/rancher/k3s/vendor/github.com/gogo/protobuf/proto/table_unmarshal.go:175 +0x8b9
github.com/rancher/k3s/vendor/github.com/gogo/protobuf/proto.(*InternalMessageInfo).Unmarshal(0xc002f60740, 0x57e0a98, 0xc003ce55e0, 0xc002574000, 0x29, 0x755, 0x10100000001, 0x0)
        /go/src/github.com/rancher/k3s/vendor/github.com/gogo/protobuf/proto/table_unmarshal.go:63 +0x66
github.com/rancher/k3s/vendor/github.com/gogo/protobuf/proto.(*Buffer).Unmarshal(0xc0017b1d48, 0x57e0a98, 0xc003ce55e0, 0x0, 0x0)
        /go/src/github.com/rancher/k3s/vendor/github.com/gogo/protobuf/proto/decode.go:424 +0x1f5
github.com/rancher/k3s/vendor/github.com/gogo/protobuf/proto.Unmarshal(0xc002574000, 0x29, 0x755, 0x57e0a98, 0xc003ce55e0, 0xc00420a010, 0xc000b63e50)
        /go/src/github.com/rancher/k3s/vendor/github.com/gogo/protobuf/proto/decode.go:342 +0x15e
github.com/rancher/k3s/vendor/github.com/containerd/ttrpc.(*Client).recv(0xc000b14900, 0xc003ce55e0, 0xc001b22640, 0x0, 0x0)
        /go/src/github.com/rancher/k3s/vendor/github.com/containerd/ttrpc/client.go:337 +0x14d
github.com/rancher/k3s/vendor/github.com/containerd/ttrpc.(*Client).run(0xc000b14900)
        /go/src/github.com/rancher/k3s/vendor/github.com/containerd/ttrpc/client.go:287 +0x4e5
created by github.com/rancher/k3s/vendor/github.com/containerd/ttrpc.NewClient
        /go/src/github.com/rancher/k3s/vendor/github.com/containerd/ttrpc/client.go:94 +0x1c5
containerd: exit status 2
```

A CI log containing this crash is available here: 
* https://storage.googleapis.com/k3s-ci-logs/k3s-log-1629458328-amd64-eb956d5bc-pmO4By.tgz

**Comment by brandond** [comment]
It appears that downgrading the replacement google.golang.org/genproto to `v0.0.0-20200224152610-e50cd9704f63` as suggested at https://github.com/containerd/ttrpc/pull/89 has worked around this issue.

**Comment by brandond** [comment]
Fixed with some careful module pinning.
