### ISSUE TITLE
K3s exits with lengthy stack trace when kube-proxy cannot parse args

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#3977]
**Environmental Info:**
K3s Version: 
1.21 or newer

Node(s) CPU architecture, OS, and Version: 
N/A

Cluster Configuration:
N/A

**Describe the bug:**
If started with args that kube-proxy does not like, kube-proxy will throw a fatal error that causes a lengthy stack trace to obscure the error message.

**Steps To Reproduce:**
`k3s server --cluster-cidr=10.41.0.0/16,10.42.0.0/26`

**Expected behavior:**
Simple error message about cluster cidr values

**Actual behavior:**
Big stack trace

**Additional context / logs:**
```console
INFO[2021-09-08T22:37:47.737118444Z] Running kube-proxy --cluster-cidr=10.41.0.0/16,10.42.0.0/26 --conntrack-max-per-core=0 --conntrack-tcp-timeout-close-wait=0s -->
Flag --cloud-provider has been deprecated, will be removed in 1.23, in favor of removing cloud provider code from Kubelet.
Flag --cni-bin-dir has been deprecated, will be removed along with dockershim.
Flag --cni-conf-dir has been deprecated, will be removed along with dockershim.
Flag --containerd has been deprecated, This is a cadvisor flag that was mistakenly registered with the Kubelet. Due to legacy concerns, it will follow the standard >
W0908 22:37:47.737394       1 server.go:220] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config fi>
F0908 22:37:47.737811       1 server.go:485] failed validate: KubeProxyConfiguration.ClusterCIDR: Invalid value: "10.41.0.0/16,10.42.0.0/26": must be a valid DualSt>
goroutine 4071 [running]:
github.com/rancher/k3s/vendor/k8s.io/klog/v2.stacks(0xc00019e001, 0xc0069ec500, 0xd6, 0xff)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1021 +0xb9
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).output(0x7c7d8a0, 0xc000000003, 0x0, 0x0, 0xc00042e150, 0x647c071, 0x9, 0x1e5, 0x0)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:970 +0x191
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).printf(0x7c7d8a0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x4c4ba9f, 0x13, 0xc006af6140, 0x1, ...)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:751 +0x191
github.com/rancher/k3s/vendor/k8s.io/klog/v2.Fatalf(...)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1509
github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-proxy/app.NewProxyCommand.func1(0xc00ae642c0, 0xc008b16000, 0x0, 0x8)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:485 +0x215
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).execute(0xc00ae642c0, 0xc0097cbd00, 0x8, 0x8, 0xc00ae642c0, 0xc0097cbd00)
        /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:854 +0x2c2
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00ae642c0, 0x0, 0xc005aa8f60, 0x0)
        /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:958 +0x375
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:895
github.com/rancher/k3s/pkg/daemons/executor.Embedded.KubeProxy.func1(0xc00ae642c0)
        /go/src/github.com/rancher/k3s/pkg/daemons/executor/embed.go:57 +0x2f
created by github.com/rancher/k3s/pkg/daemons/executor.Embedded.KubeProxy
        /go/src/github.com/rancher/k3s/pkg/daemons/executor/embed.go:56 +0x75
        
goroutine 1 [runnable]:
fmt.(*pp).doPrintf(0xc0036612b0, 0x4c11b6b, 0x5, 0xc001d40f40, 0x2, 0x2)
        /usr/local/go/src/fmt/print.go:983 +0x6b
```
and so on

**Comment by bmdepesa** [comment]
Tested on `master` branch commit `28be0de4e81a20608f9dbb5729543a89aa936711` 

First reproduced on v1.21.4 and saw the large stacktrace in the failure. 
```
F0921 20:29:32.133121   22143 server.go:485] failed validate: KubeProxyConfiguration.ClusterCIDR: Invalid value: "10.41.0.0/16,10.42.0.0/26": must be a valid DualStack CIDR (e.g. 10.100.0.0/16,fde4:8dba:82e1::/48)
goroutine 4978 [running]:
github.com/rancher/k3s/vendor/k8s.io/klog/v2.stacks(0xc000122001, 0xc00aee0000, 0xd6, 0x206)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1021 +0xb9
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).output(0x7c7d8a0, 0xc000000003, 0x0, 0x0, 0xc000023420, 0x647c071, 0x9, 0x1e5, 0x0)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:970 +0x191
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).printf(0x7c7d8a0, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x4c4ba9f, 0x13, 0xc00ae93470, 0x1, ...)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:751 +0x191
github.com/rancher/k3s/vendor/k8s.io/klog/v2.Fatalf(...)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1509
        ... on and on  ...
```

In master, the failure now happens gracefully without a stacktrace:
```
FATA[0009] controller-manager panic: F0921 20:32:15.245273   22592 controllermanager.go:226] error starting controllers: len of ClusterCIDRs==2 and they are not configured as dual stack (at least one from each IPFamily)
```
