### ISSUE TITLE
[release-1.21] Panic checking name of uninitialized etcd member

### ISSUE THREAD

**Issue by Type1J** [k3s-io/k3s#4785]
**Environmental Info:**
K3s Version: 
k3s version v1.21.7+k3s1 (ac705709)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: 
Raspberry Pi
Linux k8smaster1 5.10.83-1-MANJARO-ARM-RPI #1 SMP PREEMPT Tue Dec 7 08:43:25 CST 2021 aarch64 GNU/Linux
(They all have the same image, but with different static IPs and hostnames: k8smaster0, k8smaster1, k8sworker0, k8sworker1.

Cluster Configuration:
1 server, 2 agents
The server had `--cluster-init` passed to it, and it has etcd.

**Describe the bug:**
I attempted to add a second master and got a strange error. The first master was given `--cluster-init`, so etcd was in its roles.
Here's the end of the log if I try to start it manually on the command line with `k3s server`:
```
INFO[2021-12-17T19:52:17.353594206-05:00] Containerd is now running                    
INFO[2021-12-17T19:52:17.384384680-05:00] Connecting to proxy                           url="wss://127.0.0.1:6443/v1-k3s/connect"
ERRO[2021-12-17T19:52:17.394193344-05:00] Failed to connect to proxy                    error="websocket: bad handshake"
ERRO[2021-12-17T19:52:17.394287287-05:00] Remotedialer proxy error                      error="websocket: bad handshake"
panic: runtime error: slice bounds out of range [:-1]

goroutine 232 [running]:
github.com/rancher/k3s/pkg/etcd.(*ETCD).join(0x4000e2f770, 0x4b02318, 0x4001151c80, 0x4001342000, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/pkg/etcd/etcd.go:350 +0xfd8
github.com/rancher/k3s/pkg/etcd.(*ETCD).Start.func1(0x4000e2f770, 0x4b02318, 0x4001151c80, 0x4001342000)
	/go/src/github.com/rancher/k3s/pkg/etcd/etcd.go:307 +0x58
created by github.com/rancher/k3s/pkg/etcd.(*ETCD).Start
	/go/src/github.com/rancher/k3s/pkg/etcd/etcd.go:305 +0xe0
```
It may be worth noting that I was able to join 2 worker nodes without a problem.

**Comment by Type1J** [comment]
The second server was configured by `/etc/rancher/k3s/config.yaml` with the contents:
```yaml
token: the-token-text-from-the-first-server
server: https://ip-to-first-server:6443
```

**Comment by brandond** [comment]
Hmm, it appears the exiting etcd cluster member name doesn't match the pattern we're expecting. Can you post the results of `kubectl get nodes -o yaml` ?

**Comment by Type1J** [comment]
Sure, thanks for looking at this issue!

`# kubectl get nodes -o yaml`
```yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      etcd.k3s.cattle.io/node-address: 192.168.1.150
      etcd.k3s.cattle.io/node-name: k8smaster0-47c280f9
      flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"56:94:5a:cb:6b:d3"}'
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ip: 192.168.1.150
      k3s.io/hostname: k8smaster0
      k3s.io/internal-ip: 192.168.1.150
      k3s.io/node-args: '["server","--cluster-init"]'
      k3s.io/node-config-hash: 54RMPRWC5HMF745UCOIIOGCS5TVXSCHG7OVA7CSRC5IB5ZVW35ZA====
      k3s.io/node-env: '{"K3S_DATA_DIR":"/var/lib/rancher/k3s/data/8ba10e6674ad2dd3b3ac1d08a029eecd6609e2c058d8e7dc7c6d7b959d1da765","K3S_KUBECONFIG_MODE":"644"}'
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: "2021-12-17T05:43:05Z"
    finalizers:
    - wrangler.cattle.io/node
    - wrangler.cattle.io/managed-etcd-controller
    labels:
      beta.kubernetes.io/arch: arm64
      beta.kubernetes.io/instance-type: k3s
      beta.kubernetes.io/os: linux
      kubernetes.io/arch: arm64
      kubernetes.io/hostname: k8smaster0
      kubernetes.io/os: linux
      node-role.kubernetes.io/control-plane: "true"
      node-role.kubernetes.io/etcd: "true"
      node-role.kubernetes.io/master: "true"
      node.kubernetes.io/instance-type: k3s
    name: k8smaster0
    resourceVersion: "205331"
    uid: 4a29f905-2c7f-49b7-9ffb-a828c908c344
  spec:
    podCIDR: 10.42.0.0/24
    podCIDRs:
    - 10.42.0.0/24
    providerID: k3s://k8smaster0
  status:
    addresses:
    - address: 192.168.1.150
      type: InternalIP
    - address: k8smaster0
      type: Hostname
    allocatable:
      cpu: "4"
      ephemeral-storage: "59640087711"
      memory: 7999224Ki
      pods: "110"
    capacity:
      cpu: "4"
      ephemeral-storage: 61307656Ki
      memory: 7999224Ki
      pods: "110"
    conditions:
    - lastHeartbeatTime: "2021-12-18T01:51:09Z"
      lastTransitionTime: "2021-12-17T05:43:03Z"
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: "2021-12-18T01:51:09Z"
      lastTransitionTime: "2021-12-17T05:43:03Z"
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure
      status: "False"
      type: DiskPressure
    - lastHeartbeatTime: "2021-12-18T01:51:09Z"
      lastTransitionTime: "2021-12-17T05:43:03Z"
      message: kubelet has sufficient PID available
      reason: KubeletHasSufficientPID
      status: "False"
      type: PIDPressure
    - lastHeartbeatTime: "2021-12-18T01:51:09Z"
      lastTransitionTime: "2021-12-17T05:43:15Z"
      message: kubelet is posting ready status
      reason: KubeletReady
      status: "True"
      type: Ready
    daemonEndpoints:
      kubeletEndpoint:
        Port: 10250
    images:
    - names:
      - docker.io/rancher/klipper-helm@sha256:961459b8641aa77dae39c96ba8efba88805a8949dcaafa131d1aecc1510128bf
      - docker.io/rancher/klipper-helm:v0.6.6-build20211022
      sizeBytes: 78105850
    - names:
      - docker.io/rancher/library-traefik@sha256:343de3610780fc88b04eeb2145cbf8189e8f6278c2061de4a1e10de31711c252
      - docker.io/rancher/library-traefik:2.4.8
      sizeBytes: 25483119
    - names:
      - docker.io/rancher/local-path-provisioner@sha256:9666b1635fec95d4e2251661e135c90678b8f45fd0f8324c55db99c80e2a958c
      - docker.io/rancher/local-path-provisioner:v0.0.19
      sizeBytes: 12523337
    - names:
      - docker.io/rancher/coredns-coredns@sha256:9d4f5d7968c432fbd4123f397a2d6ab666fd63d13d510d9728d717c3e002dc72
      - docker.io/rancher/coredns-coredns:1.8.3
      sizeBytes: 11526164
    - names:
      - docker.io/rancher/metrics-server@sha256:b85628b103169d7db52a32a48b46d8942accb7bde3709c0a4888a23d035f9f1e
      - docker.io/rancher/metrics-server:v0.3.6
      sizeBytes: 9866023
    - names:
      - docker.io/rancher/klipper-lb@sha256:d5ec8350ee1a80ec783effe95a2fefae371d1498ac04865cb6024499882f291c
      - docker.io/rancher/klipper-lb:v0.3.4
      sizeBytes: 3230910
    - names:
      - docker.io/rancher/pause@sha256:d22591b61e9c2b52aecbf07106d5db313c4f178e404d660b32517b18fcbf0144
      - docker.io/rancher/pause:3.1
      sizeBytes: 274812
    nodeInfo:
      architecture: arm64
      bootID: cc8ed4b7-2519-466a-88d5-776434701e27
      containerRuntimeVersion: containerd://1.4.12-k3s1
      kernelVersion: 5.10.83-1-MANJARO-ARM-RPI
      kubeProxyVersion: v1.21.7+k3s1
      kubeletVersion: v1.21.7+k3s1
      machineID: b7462bb9d2874e61a4e2a97ba1260d28
      operatingSystem: linux
      osImage: Manjaro ARM
      systemUUID: b7462bb9d2874e61a4e2a97ba1260d28
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"de:62:09:7e:a0:fe"}'
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ip: 192.168.1.152
      k3s.io/hostname: k8sworker0
      k3s.io/internal-ip: 192.168.1.152
      k3s.io/node-args: '["agent"]'
      k3s.io/node-config-hash: YH4XDEZBGRBKRC6I42PABK2QZAD7JNNA7YD3QK7GHTAG3QJBQ7LA====
      k3s.io/node-env: '{"K3S_DATA_DIR":"/var/lib/rancher/k3s/data/8ba10e6674ad2dd3b3ac1d08a029eecd6609e2c058d8e7dc7c6d7b959d1da765","K3S_KUBECONFIG_MODE":"644","K3S_TOKEN":"********","K3S_URL":"https://192.168.1.150:6443"}'
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: "2021-12-17T06:46:09Z"
    finalizers:
    - wrangler.cattle.io/node
    - wrangler.cattle.io/managed-etcd-controller
    labels:
      beta.kubernetes.io/arch: arm64
      beta.kubernetes.io/instance-type: k3s
      beta.kubernetes.io/os: linux
      kubernetes.io/arch: arm64
      kubernetes.io/hostname: k8sworker0
      kubernetes.io/os: linux
      node.kubernetes.io/instance-type: k3s
    name: k8sworker0
    resourceVersion: "205771"
    uid: 6d827198-a13f-4748-a3dc-87a0266e152b
  spec:
    podCIDR: 10.42.2.0/24
    podCIDRs:
    - 10.42.2.0/24
    providerID: k3s://k8sworker0
  status:
    addresses:
    - address: 192.168.1.152
      type: InternalIP
    - address: k8sworker0
      type: Hostname
    allocatable:
      cpu: "4"
      ephemeral-storage: "59640087711"
      memory: 7999224Ki
      pods: "110"
    capacity:
      cpu: "4"
      ephemeral-storage: 61307656Ki
      memory: 7999224Ki
      pods: "110"
    conditions:
    - lastHeartbeatTime: "2021-12-18T01:53:41Z"
      lastTransitionTime: "2021-12-17T06:46:09Z"
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: "2021-12-18T01:53:41Z"
      lastTransitionTime: "2021-12-17T06:46:09Z"
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure
      status: "False"
      type: DiskPressure
    - lastHeartbeatTime: "2021-12-18T01:53:41Z"
      lastTransitionTime: "2021-12-17T06:46:09Z"
      message: kubelet has sufficient PID available
      reason: KubeletHasSufficientPID
      status: "False"
      type: PIDPressure
    - lastHeartbeatTime: "2021-12-18T01:53:41Z"
      lastTransitionTime: "2021-12-17T06:46:19Z"
      message: kubelet is posting ready status
      reason: KubeletReady
      status: "True"
      type: Ready
    daemonEndpoints:
      kubeletEndpoint:
        Port: 10250
    images:
    - names:
      - docker.io/rancher/klipper-lb@sha256:d5ec8350ee1a80ec783effe95a2fefae371d1498ac04865cb6024499882f291c
      - docker.io/rancher/klipper-lb:v0.3.4
      sizeBytes: 3230910
    - names:
      - docker.io/rancher/pause@sha256:d22591b61e9c2b52aecbf07106d5db313c4f178e404d660b32517b18fcbf0144
      - docker.io/rancher/pause:3.1
      sizeBytes: 274812
    nodeInfo:
      architecture: arm64
      bootID: baca4302-a6b5-41e3-8fe2-6b06037c35ad
      containerRuntimeVersion: containerd://1.4.12-k3s1
      kernelVersion: 5.10.83-1-MANJARO-ARM-RPI
      kubeProxyVersion: v1.21.7+k3s1
      kubeletVersion: v1.21.7+k3s1
      machineID: 194da398296c4b51b37cfaa7fc83fddc
      operatingSystem: linux
      osImage: Manjaro ARM
      systemUUID: 194da398296c4b51b37cfaa7fc83fddc
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      flannel.alpha.coreos.com/backend-data: '{"VNI":1,"VtepMAC":"aa:17:57:52:d0:06"}'
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ip: 192.168.1.153
      k3s.io/hostname: k8sworker1
      k3s.io/internal-ip: 192.168.1.153
      k3s.io/node-args: '["agent"]'
      k3s.io/node-config-hash: YH4XDEZBGRBKRC6I42PABK2QZAD7JNNA7YD3QK7GHTAG3QJBQ7LA====
      k3s.io/node-env: '{"K3S_DATA_DIR":"/var/lib/rancher/k3s/data/8ba10e6674ad2dd3b3ac1d08a029eecd6609e2c058d8e7dc7c6d7b959d1da765","K3S_KUBECONFIG_MODE":"644","K3S_TOKEN":"********","K3S_URL":"https://192.168.1.150:6443"}'
      node.alpha.kubernetes.io/ttl: "0"
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: "2021-12-17T06:46:31Z"
    finalizers:
    - wrangler.cattle.io/node
    - wrangler.cattle.io/managed-etcd-controller
    labels:
      beta.kubernetes.io/arch: arm64
      beta.kubernetes.io/instance-type: k3s
      beta.kubernetes.io/os: linux
      kubernetes.io/arch: arm64
      kubernetes.io/hostname: k8sworker1
      kubernetes.io/os: linux
      node.kubernetes.io/instance-type: k3s
    name: k8sworker1
    resourceVersion: "205717"
    uid: 34f2c0a1-51e9-48d4-95bb-3c6e417e66e4
  spec:
    podCIDR: 10.42.3.0/24
    podCIDRs:
    - 10.42.3.0/24
    providerID: k3s://k8sworker1
  status:
    addresses:
    - address: 192.168.1.153
      type: InternalIP
    - address: k8sworker1
      type: Hostname
    allocatable:
      cpu: "4"
      ephemeral-storage: "59640087711"
      memory: 7999224Ki
      pods: "110"
    capacity:
      cpu: "4"
      ephemeral-storage: 61307656Ki
      memory: 7999224Ki
      pods: "110"
    conditions:
    - lastHeartbeatTime: "2021-12-18T01:53:22Z"
      lastTransitionTime: "2021-12-17T06:46:31Z"
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: "2021-12-18T01:53:22Z"
      lastTransitionTime: "2021-12-17T06:46:31Z"
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure
      status: "False"
      type: DiskPressure
    - lastHeartbeatTime: "2021-12-18T01:53:22Z"
      lastTransitionTime: "2021-12-17T06:46:31Z"
      message: kubelet has sufficient PID available
      reason: KubeletHasSufficientPID
      status: "False"
      type: PIDPressure
    - lastHeartbeatTime: "2021-12-18T01:53:22Z"
      lastTransitionTime: "2021-12-17T06:46:41Z"
      message: kubelet is posting ready status
      reason: KubeletReady
      status: "True"
      type: Ready
    daemonEndpoints:
      kubeletEndpoint:
        Port: 10250
    images:
    - names:
      - docker.io/rancher/klipper-lb@sha256:d5ec8350ee1a80ec783effe95a2fefae371d1498ac04865cb6024499882f291c
      - docker.io/rancher/klipper-lb:v0.3.4
      sizeBytes: 3230910
    - names:
      - docker.io/rancher/pause@sha256:d22591b61e9c2b52aecbf07106d5db313c4f178e404d660b32517b18fcbf0144
      - docker.io/rancher/pause:3.1
      sizeBytes: 274812
    nodeInfo:
      architecture: arm64
      bootID: 20399474-6b91-4def-a796-35a88d088e21
      containerRuntimeVersion: containerd://1.4.12-k3s1
      kernelVersion: 5.10.83-1-MANJARO-ARM-RPI
      kubeProxyVersion: v1.21.7+k3s1
      kubeletVersion: v1.21.7+k3s1
      machineID: 63e0875687f94fd0bfc6fa2b91e8d73c
      operatingSystem: linux
      osImage: Manjaro ARM
      systemUUID: 63e0875687f94fd0bfc6fa2b91e8d73c
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

`cat /var/lib/rancher/k3s/server/db/etcd/name`
```
k8smaster0-47c280f9
```

**Comment by brandond** [comment]
Hmm, that all looks correct. Just to confirm, you're using `server: https://192.168.1.150:6443` on the second node?

**Comment by Type1J** [comment]
Yes

**Comment by brandond** [comment]
Can you try reinstalling your second node with:
```bash
curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=3f45fc1a13d4ad32abe2c09ffc2e13e124cd3fce INSTALL_K3S_EXEC=server sh -
```

You can just re-run the install; don't uninstall or remove your current config file.

**Comment by Type1J** [comment]
I used Manjaro because I'd been using it on a Pinebook Pro, but should I use the image on Raspberry Pi's stie instead? I wouldn't think that it would make a difference.

**Comment by Type1J** [comment]
From your install command above, I got the following:
```

```

**Comment by Type1J** [comment]
From your install command above, I got the following:
```
INFO[2021-12-18T09:00:46.860301397-05:00] Containerd is now running                    
INFO[2021-12-18T09:00:46.893987122-05:00] Connecting to proxy                           url="wss://127.0.0.1:6443/v1-k3s/connect"
ERRO[2021-12-18T09:00:46.902890023-05:00] Failed to connect to proxy                    error="websocket: bad handshake"
ERRO[2021-12-18T09:00:46.902993262-05:00] Remotedialer proxy error                      error="websocket: bad handshake"
INFO[2021-12-18T09:00:46.905970272-05:00] Starting etcd for cluster [k8smaster1-e77303c3=https://192.168.1.151:2380 k8smaster0-47c280f9=https://192.168.1.150:2380] 
{"level":"info","ts":"2021-12-18T09:00:46.910-0500","caller":"embed/etcd.go:117","msg":"configuring peer listeners","listen-peer-urls":["https://192.168.1.151:2380"]}
{"level":"info","ts":"2021-12-18T09:00:46.910-0500","caller":"embed/etcd.go:468","msg":"starting with peer TLS","tls-info":"cert = /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.crt, key = /var/lib/rancher/k3s/server/tls/etcd/peer-server-client.key, trusted-ca = /var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt, client-cert-auth = true, crl-file = ","cipher-suites":[]}
{"level":"info","ts":"2021-12-18T09:00:46.911-0500","caller":"embed/etcd.go:127","msg":"configuring client listeners","listen-client-urls":["https://127.0.0.1:2379","https://192.168.1.151:2379"]}
{"level":"info","ts":"2021-12-18T09:00:46.912-0500","caller":"embed/etcd.go:302","msg":"starting an etcd server","etcd-version":"3.4.13","git-sha":"Not provided (use ./build instead of go build)","go-version":"go1.16.10","go-os":"linux","go-arch":"arm64","max-cpu-set":4,"max-cpu-available":4,"member-initialized":false,"name":"k8smaster1-e77303c3","data-dir":"/var/lib/rancher/k3s/server/db/etcd","wal-dir":"","wal-dir-dedicated":"","member-dir":"/var/lib/rancher/k3s/server/db/etcd/member","force-new-cluster":false,"heartbeat-interval":"500ms","election-timeout":"5s","initial-election-tick-advance":true,"snapshot-count":100000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://localhost:2380"],"listen-peer-urls":["https://192.168.1.151:2380"],"advertise-client-urls":["https://192.168.1.151:2379"],"listen-client-urls":["https://127.0.0.1:2379","https://192.168.1.151:2379"],"listen-metrics-urls":["http://127.0.0.1:2381"],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"k8smaster0-47c280f9=https://192.168.1.150:2380,k8smaster1-e77303c3=https://192.168.1.151:2380","initial-cluster-state":"existing","initial-cluster-token":"etcd-cluster","quota-size-bytes":2147483648,"pre-vote":false,"initial-corrupt-check":false,"corrupt-check-time-interval":"0s","auto-compaction-mode":"","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":""}
{"level":"info","ts":"2021-12-18T09:00:46.913-0500","caller":"etcdserver/backend.go:80","msg":"opened backend db","path":"/var/lib/rancher/k3s/server/db/etcd/member/snap/db","took":"489.844µs"}
{"level":"warn","ts":"2021-12-18T09:00:46.954-0500","caller":"etcdserver/cluster_util.go:76","msg":"failed to get cluster response","address":"https://192.168.1.150:2380/members","error":"Get \"https://192.168.1.150:2380/members\": EOF"}
{"level":"info","ts":"2021-12-18T09:00:46.956-0500","caller":"embed/etcd.go:363","msg":"closing etcd server","name":"k8smaster1-e77303c3","data-dir":"/var/lib/rancher/k3s/server/db/etcd","advertise-peer-urls":["http://localhost:2380"],"advertise-client-urls":["https://192.168.1.151:2379"]}
{"level":"warn","ts":"2021-12-18T09:00:46.957-0500","caller":"embed/config_logging.go:279","msg":"rejected connection","remote-addr":"192.168.1.24:46778","server-name":"","error":"read tcp 192.168.1.151:2380->192.168.1.24:46778: use of closed network connection"}
{"level":"warn","ts":"2021-12-18T09:00:46.961-0500","caller":"embed/config_logging.go:270","msg":"rejected connection","remote-addr":"192.168.1.24:46776","server-name":"","ip-addresses":["127.0.0.1","192.168.1.150","10.43.0.1"],"dns-names":["localhost","k8smaster0"],"error":"tls: \"192.168.1.24\" does not match any of DNSNames [\"localhost\" \"k8smaster0\"] (lookup k8smaster0 on [2601:cf:8100:7b:ea9f:80ff:fe4d:24f3]:53: dial udp [2601:cf:8100:7b:ea9f:80ff:fe4d:24f3]:53: operation was canceled)"}
{"level":"info","ts":"2021-12-18T09:00:46.962-0500","caller":"embed/etcd.go:367","msg":"closed etcd server","name":"k8smaster1-e77303c3","data-dir":"/var/lib/rancher/k3s/server/db/etcd","advertise-peer-urls":["http://localhost:2380"],"advertise-client-urls":["https://192.168.1.151:2379"]}
FATA[2021-12-18T09:00:46.962347113-05:00] ETCD join failed: cannot fetch cluster info from peer urls: could not retrieve cluster information from the given URLs
```

**Comment by Type1J** [comment]
That output above is actually the last few lines of `k3s server`, not the install command. The install command said this:
```
# curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=3f45fc1a13d4ad32abe2c09ffc2e13e124cd3fce INSTALL_K3S_EXEC=server sh -
[INFO]  Using commit 3f45fc1a13d4ad32abe2c09ffc2e13e124cd3fce as release
[INFO]  Downloading hash https://storage.googleapis.com/k3s-ci-builds/k3s-arm64-3f45fc1a13d4ad32abe2c09ffc2e13e124cd3fce.sha256sum
[INFO]  Downloading binary https://storage.googleapis.com/k3s-ci-builds/k3s-arm64-3f45fc1a13d4ad32abe2c09ffc2e13e124cd3fce
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Skipping /usr/local/bin/kubectl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/crictl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, command exists in PATH at /usr/bin/ctr
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
Job for k3s.service failed because the control process exited with error code.
See "systemctl status k3s.service" and "journalctl -xeu k3s.service" for details.
```
I figured that the `k3s server` command's output was probably more helpful.

**Comment by brandond** [comment]
The logs there are very odd.

```
{"level":"warn","ts":"2021-12-18T09:00:46.957-0500","caller":"embed/config_logging.go:279","msg":"rejected connection","remote-addr":"192.168.1.24:46778","server-name":"","error":"read tcp 192.168.1.151:2380->192.168.1.24:46778: use of closed network connection"}
{"level":"warn","ts":"2021-12-18T09:00:46.961-0500","caller":"embed/config_logging.go:270","msg":"rejected connection","remote-addr":"192.168.1.24:46776","server-name":"","ip-addresses":["127.0.0.1","192.168.1.150","10.43.0.1"],"dns-names":["localhost","k8smaster0"],"error":"tls: \"192.168.1.24\" does not match any of DNSNames [\"localhost\" \"k8smaster0\"] (lookup k8smaster0 on [2601:cf:8100:7b:ea9f:80ff:fe4d:24f3]:53: dial udp [2601:cf:8100:7b:ea9f:80ff:fe4d:24f3]:53: operation was canceled)"}
```

Do you have multiple 192.168.1.x addresses configured on either of the servers?

**Comment by Type1J** [comment]
I saw that IP. It's not on my network. The Raspberry Pis are connected through a PoE switch, and even though they have WiFi, it's not used, nor is it even configured.

**Comment by Type1J** [comment]
Ok, I'm not sure what caused it, but this is on the 1st server (k8smaster0)
```
$ ip address | grep 192.168
    inet 192.168.1.150/24 brd 192.168.1.255 scope global eth0
    inet 192.168.1.24/24 brd 192.168.1.255 scope global secondary dynamic noprefixroute eth0
```
Maybe I need to remove it, but I'm not sure how it got there. I have DHCP, but I assigned a static IP in `cmdline.txt`.

**Comment by Type1J** [comment]
Here's `/boot/cmdline.txt`
```
root=PARTUUID=0900f2c7-02 rw rootwait console=serial0,115200 console=tty3 selinux=0 quiet splash plymouth.ignore-serial-consoles smsc95xx.turbo_mode=N dwc_otg.lpm_enable=0 kgdboc=serial0,115200 usbhid.mousepoll=8 audit=0 cgroup_memory=1 cgroup_enable=memory ip=192.168.1.150::192.168.1.1:255.255.255.0:k8smaster0:eth0:off
```

**Comment by brandond** [comment]
You probably need to configure that same static address in your netplan or whatever Manjaro is using.

**Comment by Type1J** [comment]
I'll attempt to do so.

**Comment by Type1J** [comment]
@brandond Thanks for the help!

It seems that `dhcpcd` was still getting an IP because I passed the kernel the `ip=...` option instead of configuring `dhcpcd`. I configured it this way because I didn't have a terminal connected to the Raspberry Pi directly, and I was using macOS to write the image to the SD, so I only had control over what went on the boot drive (`cmdline.txt` in the `/boot` drive specifically, since the volume mounted at `/boot` it's FAT, not ext4, like the rest of the image).

After a
```
systemctl stop dhcpcd
systemctl disable dhcpcd
reboot
```

I looked at the nodes, and the 2nd master appeared.
`$ kubectl get nodes`
```
NAME         STATUS   ROLES                       AGE     VERSION
k8smaster0   Ready    control-plane,etcd,master   2d16h   v1.21.7+k3s1
k8smaster1   Ready    control-plane,etcd,master   3m18s   v1.21.8+k3s-3f45fc1a
k8sworker0   Ready    <none>                      2d15h   v1.21.7+k3s1
k8sworker1   Ready    <none>                      2d15h   v1.21.7+k3s1
```

It must have been telling the second master about the second IP during the join, which caused it to fail. Your patch did print out useful information (the IP) where before, `k3s server` was crashing, so I'd recommend the merge of #4786, but I'm closing this issue, since it is solved as it's worded.

I'm sure that error messages could be generated if multiple IPs are detected for a single network interface where 1 is dynamic and the other is static, since that seems to cause a problem, and is most likely not something done intentionally.

Thanks, again, for the help!

**Comment by Type1J** [comment]
For clarity, I did
```
systemctl stop dhcpcd
systemctl disable dhcpcd
reboot
```
on all 4 nodes. They only have the static IP that was given in `cmdline.txt`, now.

**Comment by brandond** [comment]
I'm going to reopen this so that we can fix the panic.

**Comment by ShylajaDevadiga** [comment]
While attempting to reproduce this issue using v1.21.7+k3s1 as below, noticed second node fails to join the first node using secondary IP. 
1. Created a node with two static ips set on the same interface. 
Node1
```
$ kubectl get nodes -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      etcd.k3s.cattle.io/node-address: 10.0.0.130
```
2. Joined second server node using secondary IP of first node
Node2
```
$ curl -fL https://get.k3s.io | INSTALL_K3S_VERSION=v1.21.7+k3s1 sh -s - server --token <TOKEN> --server https://10.0.0.131:6443
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27318  100 27318    0     0  25131      0  0:00:01  0:00:01 --:--:-- 25154
[INFO]  Using v1.21.7+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.21.7+k3s1/sha256sum-arm64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.21.7+k3s1/k3s-arm64
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
Job for k3s.service failed because the control process exited with error code.
See "systemctl status k3s.service" and "journalctl -xe" for details.
```
From the log:
```
Dec 15 18:08:16 ubuntu k3s[1194]: panic(0x3521980, 0x400052b570)
Dec 15 18:08:16 ubuntu k3s[1194]:         /usr/local/go/src/runtime/panic.go:969 +0x15c
Dec 15 18:08:16 ubuntu k3s[1194]: E1215 18:08:16.751828    1194 wrap.go:39] apiserver panic'd on PATCH /api/v1/nodes/ubuntu/status
```

On v1.21.8-rc1+k3s2, on the same configuration, logs show the below message 
```
Jan 11 05:13:33 rpi2 k3s[8546]: time="2022-01-11T05:13:33.091162357Z" level=error msg="Remotedialer proxy error" error="websocket: bad handshake"
Jan 11 05:13:35 rpi2 k3s[8546]: time="2022-01-11T05:13:35.253671402Z" level=info msg="Waiting for etcd server to become available"
Jan 11 05:13:35 rpi2 k3s[8546]: time="2022-01-11T05:13:35.257830827Z" level=info msg="Waiting for API server to become available"
Jan 11 05:13:38 rpi2 k3s[8546]: {"level":"warn","ts":"2022-01-11T05:13:38.036Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-97651fbd-04bc-4721-ad6b-fb3b700c2420/10.0.0.130:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.0.0.130:2379: connect: no route to host\""}
Jan 11 05:13:38 rpi2 k3s[8546]: time="2022-01-11T05:13:38.036556696Z" level=error msg="Failed to get member list from etcd cluster. Will assume this member is already added"
Jan 11 05:13:38 rpi2 k3s[8546]: time="2022-01-11T05:13:38.036901878Z" level=fatal msg="ETCD join failed: duplicate node name found, please use a unique name for this node"
```

**Comment by ShylajaDevadiga** [comment]
Also validated passing duplicate node name on second node failed to join the cluster
