### ISSUE TITLE
k3s-server take too mush cpu on SONiC system

### ISSUE THREAD

**Issue by u0u0** [k3s-io/k3s#5082]
The OS is SONiC run on qemu, [SONiC-on-virtual-machine-for-Windows](https://github.com/Azure/SONiC/wiki/SONiC-on-virtual-machine-for-Windows).

Install k3s server by below commod:
```
curl -sfL http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -s - --docker
```

After install, the k3s-server was started,  but it take too mush cpu times.  The top info showing below:
![sonic](https://user-images.githubusercontent.com/4597563/152639823-5cf01e71-19f1-4305-a8ed-74118f83bb9d.png)

Is there any tools to find the problem?

**Environmental Info:**
K3s Version: 
k3s version v1.22.6+k3s1 (3228d9cb)
go version go1.16.10

Node(s) CPU architecture, OS, and Version: 
 Linux sonic 5.10.0-8-2-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux

**Comment by u0u0** [comment]
I try `sudo kubectl get nodes --v=8`, log info show below

```
centec@localhost:~$ sudo kubectl get nodes --v=8
I0205 20:23:33.686562    3963 loader.go:372] Config loaded from file:  /etc/rancher/k3s/k3s.yaml
I0205 20:23:33.887532    3963 round_trippers.go:432] GET https://127.0.0.1:6443/api?timeout=32s
I0205 20:23:33.887653    3963 round_trippers.go:438] Request Headers:
I0205 20:23:33.887695    3963 round_trippers.go:442]     Accept: application/json, */*
I0205 20:23:33.887729    3963 round_trippers.go:442]     User-Agent: kubectl/v1.22.5+k3s1 (linux/arm64) kubernetes/405bf79
I0205 20:23:33.899713    3963 round_trippers.go:457] Response Status:  in 11 milliseconds
I0205 20:23:33.899846    3963 round_trippers.go:460] Response Headers:
I0205 20:23:33.900327    3963 cached_discovery.go:121] skipped caching discovery info due to Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused
I0205 20:23:33.907565    3963 round_trippers.go:432] GET https://127.0.0.1:6443/api?timeout=32s
I0205 20:23:33.907677    3963 round_trippers.go:438] Request Headers:
I0205 20:23:33.907715    3963 round_trippers.go:442]     Accept: application/json, */*
I0205 20:23:33.907747    3963 round_trippers.go:442]     User-Agent: kubectl/v1.22.5+k3s1 (linux/arm64) kubernetes/405bf79
I0205 20:23:33.915542    3963 round_trippers.go:457] Response Status:  in 7 milliseconds
I0205 20:23:33.915811    3963 round_trippers.go:460] Response Headers:
I0205 20:23:33.916129    3963 cached_discovery.go:121] skipped caching discovery info due to Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused
I0205 20:23:33.916246    3963 shortcut.go:89] Error loading discovery information: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused
I0205 20:23:33.916833    3963 round_trippers.go:432] GET https://127.0.0.1:6443/api?timeout=32s
I0205 20:23:33.916928    3963 round_trippers.go:438] Request Headers:
I0205 20:23:33.916966    3963 round_trippers.go:442]     Accept: application/json, */*
I0205 20:23:33.916997    3963 round_trippers.go:442]     User-Agent: kubectl/v1.22.5+k3s1 (linux/arm64) kubernetes/405bf79
I0205 20:23:33.918226    3963 round_trippers.go:457] Response Status:  in 1 milliseconds
I0205 20:23:33.918331    3963 round_trippers.go:460] Response Headers:
I0205 20:23:33.918581    3963 cached_discovery.go:121] skipped caching discovery info due to Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused
I0205 20:23:33.919176    3963 round_trippers.go:432] GET https://127.0.0.1:6443/api?timeout=32s
I0205 20:23:33.919270    3963 round_trippers.go:438] Request Headers:
I0205 20:23:33.919308    3963 round_trippers.go:442]     Accept: application/json, */*
I0205 20:23:33.919339    3963 round_trippers.go:442]     User-Agent: kubectl/v1.22.5+k3s1 (linux/arm64) kubernetes/405bf79
I0205 20:23:33.925470    3963 round_trippers.go:457] Response Status:  in 6 milliseconds
I0205 20:23:33.925595    3963 round_trippers.go:460] Response Headers:
I0205 20:23:33.925962    3963 cached_discovery.go:121] skipped caching discovery info due to Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused
I0205 20:23:33.929439    3963 round_trippers.go:432] GET https://127.0.0.1:6443/api?timeout=32s
I0205 20:23:33.929551    3963 round_trippers.go:438] Request Headers:
I0205 20:23:33.929588    3963 round_trippers.go:442]     User-Agent: kubectl/v1.22.5+k3s1 (linux/arm64) kubernetes/405bf79
I0205 20:23:33.929620    3963 round_trippers.go:442]     Accept: application/json, */*
I0205 20:23:33.930950    3963 round_trippers.go:457] Response Status:  in 1 milliseconds
I0205 20:23:33.931068    3963 round_trippers.go:460] Response Headers:
I0205 20:23:33.931343    3963 cached_discovery.go:121] skipped caching discovery info due to Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused
I0205 20:23:33.931606    3963 helpers.go:235] Connection error: Get https://127.0.0.1:6443/api?timeout=32s: dial tcp 127.0.0.1:6443: connect: connection refused
F0205 20:23:33.931761    3963 helpers.go:116] The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
panic: F0205 20:23:33.931761    3963 helpers.go:116] The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?


goroutine 1 [running]:
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).output(0x7770580, 0x4000000003, 0x0, 0x0, 0x4000740540, 0x2, 0x6021d21, 0xa, 0x74, 0x36a2800)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:970 +0x780
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).printDepth(0x7770580, 0x4000000003, 0x0, 0x0, 0x0, 0x0, 0x2, 0x40014b0570, 0x1, 0x1)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:735 +0x128
github.com/rancher/k3s/vendor/k8s.io/klog/v2.FatalDepth(...)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1481
github.com/rancher/k3s/vendor/k8s.io/kubectl/pkg/cmd/util.fatal(0x40013b8700, 0x61, 0x1)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:94 +0x22c
github.com/rancher/k3s/vendor/k8s.io/kubectl/pkg/cmd/util.checkErr(0x4e8fad0, 0x40014c9f20, 0x48d1c90)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:189 +0x75c
github.com/rancher/k3s/vendor/k8s.io/kubectl/pkg/cmd/util.CheckErr(...)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/kubectl/pkg/cmd/util/helpers.go:116
github.com/rancher/k3s/vendor/k8s.io/kubectl/pkg/cmd/get.NewCmdGet.func2(0x400076ef00, 0x40014921e0, 0x1, 0x2)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/kubectl/pkg/cmd/get/get.go:180 +0x120
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).execute(0x400076ef00, 0x40014921a0, 0x2, 0x2, 0x400076ef00, 0x40014921a0)
        /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:860 +0x1d0
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x400109d900, 0x4000124180, 0x40003f9d00, 0x4)
        /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:974 +0x274
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:902
github.com/rancher/k3s/pkg/kubectl.main()
        /go/src/github.com/rancher/k3s/pkg/kubectl/main.go:47 +0x20c
github.com/rancher/k3s/pkg/kubectl.Main()
        /go/src/github.com/rancher/k3s/pkg/kubectl/main.go:30 +0x40
github.com/rancher/k3s/vendor/github.com/docker/docker/pkg/reexec.Init(...)
        /go/src/github.com/rancher/k3s/vendor/github.com/docker/docker/pkg/reexec/reexec.go:26
main.main()
        /go/src/github.com/rancher/k3s/cmd/server/main.go:38 +0xec4
```

it look like k3s 6443 port not started!

**Comment by u0u0** [comment]
`docker ps -a` show that "entry" can not started,  where to find the error log? 

```
centec@localhost:~$ sudo docker ps -a
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                      PORTS               NAMES
97b6d7c15750        3b7ad2a8ddb9                         "entry install --set…"   8 minutes ago       Exited (1) 7 minutes ago                        k8s_helm_helm-install-traefik--1-qmc9c_kube-system_5a6bf238-e410-4f94-b069-8cff5224c870_5
3430f9c48548        3b7ad2a8ddb9                         "entry install"          10 minutes ago      Exited (0) 9 minutes ago                        k8s_helm_helm-install-traefik-crd--1-rvp7b_kube-system_f115c289-2e6e-4f06-a212-ec7d5d0f355b_4
852d7466d4c2        1d64d3e888a2                         "/metrics-server --c…"   10 minutes ago      Up 10 minutes                                   k8s_metrics-server_metrics-server-ff9dbcb6c-2n8d9_kube-system_8e3bb1d0-03e0-4af7-bb8a-fa7ae9249c5b_3
0b312571da3b        fe8bc53de6e4                         "local-path-provisio…"   11 minutes ago      Up 11 minutes                                   k8s_local-path-provisioner_local-path-provisioner-84bb864455-tsmq4_kube-system_fe0ef303-b068-40fb-aa9a-7e6e4b9572be_2
160556ff7dfb        1d64d3e888a2                         "/metrics-server --c…"   12 minutes ago      Exited (0) 10 minutes ago                       k8s_metrics-server_metrics-server-ff9dbcb6c-2n8d9_kube-system_8e3bb1d0-03e0-4af7-bb8a-fa7ae9249c5b_2
938c7f9372db        fe8bc53de6e4                         "local-path-provisio…"   12 minutes ago      Exited (1) 12 minutes ago                       k8s_local-path-provisioner_local-path-provisioner-84bb864455-tsmq4_kube-system_fe0ef303-b068-40fb-aa9a-7e6e4b9572be_1
9cf63abc27bf        rancher/mirrored-coredns-coredns     "/coredns -conf /etc…"   17 minutes ago      Up 16 minutes                                   k8s_coredns_coredns-96cc4f57d-lnqjg_kube-system_eaccf83a-8719-4bbf-b904-13a16de08e12_0
5007a2312cc5        rancher/mirrored-pause:3.6           "/pause"                 20 minutes ago      Exited (0) 9 minutes ago                        k8s_POD_helm-install-traefik-crd--1-rvp7b_kube-system_f115c289-2e6e-4f06-a212-ec7d5d0f355b_1
c034f466072f        rancher/mirrored-pause:3.6           "/pause"                 20 minutes ago      Up 20 minutes                                   k8s_POD_metrics-server-ff9dbcb6c-2n8d9_kube-system_8e3bb1d0-03e0-4af7-bb8a-fa7ae9249c5b_1
000f08ef505e        rancher/mirrored-pause:3.6           "/pause"                 20 minutes ago      Up 20 minutes                                   k8s_POD_local-path-provisioner-84bb864455-tsmq4_kube-system_fe0ef303-b068-40fb-aa9a-7e6e4b9572be_1
b38305173eb2        rancher/mirrored-pause:3.6           "/pause"                 20 minutes ago      Up 20 minutes                                   k8s_POD_coredns-96cc4f57d-lnqjg_kube-system_eaccf83a-8719-4bbf-b904-13a16de08e12_1
05f36a61c79c        rancher/mirrored-pause:3.6           "/pause"                 20 minutes ago      Up 20 minutes                                   k8s_POD_helm-install-traefik--1-qmc9c_kube-system_5a6bf238-e410-4f94-b069-8cff5224c870_1
```
