### ISSUE TITLE
k3s server can't start after reboot machine

### ISSUE THREAD

**Issue by boot-vue** [k3s-io/k3s#5146]
**Environmental Info:**
K3s Version: 
```
k3s version v1.23.3+k3s1 (5fb370e5)
go version go1.17.5
```

Node(s) CPU architecture, OS, and Version: 
```
Linux node2 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
```
1 server, 0 agent
```

**Describe the bug:**
after reboot os , k3s-server service can't start

**Steps To Reproduce:**
- Installed K3s: 
   ```
     curl -sfL http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn  sh -s - server --token=123456 --cluster-init
   ```

**Additional context / logs:**

[k3s.log](https://github.com/k3s-io/k3s/files/8104116/k3s.log)

```log
Feb 20 15:49:07 node2 k3s[25386]: containerd: signal: killed
-- Reboot --
Feb 20 21:13:28 node2 systemd[1]: Starting Lightweight Kubernetes...
Feb 20 21:13:43 node2 k3s[932]: time="2022-02-20T21:13:43+08:00" level=info msg="Starting k3s v1.23.3+k3s1 (5fb370e5)"
Feb 20 21:13:43 node2 k3s[932]: time="2022-02-20T21:13:43+08:00" level=info msg="Managed etcd cluster bootstrap already complete and initialized"
Feb 20 21:13:43 node2 k3s[932]: time="2022-02-20T21:13:43+08:00" level=info msg="Starting local etcd to reconcile with datastore"
Feb 20 21:13:50 node2 k3s[932]: {"level":"info","ts":"2022-02-20T21:13:50.136+0800","caller":"embed/etcd.go:131","msg":"configuring peer listeners","listen-peer-urls":["http://localhost:2380"]}
Feb 20 21:13:50 node2 k3s[932]: {"level":"info","ts":"2022-02-20T21:13:50.185+0800","caller":"embed/etcd.go:139","msg":"configuring client listeners","listen-client-urls":["http://127.0.0.1:2399"]}
Feb 20 21:13:50 node2 k3s[932]: {"level":"info","ts":"2022-02-20T21:13:50.185+0800","caller":"embed/etcd.go:307","msg":"starting an etcd server","etcd-version":"3.5.1","git-sha":"Not provided (use ./build instead of go build)","go-version":"go1.17.5","go-os":"linux","go-arch":"amd64","max-cpu-set":4,"max-cpu-available":4,"member-initialized":true,"name":"default","data-dir":"/var/lib/rancher/k3s/server/db/tmp-etcd","wal-dir":"","wal-dir-dedicated":"","member-dir":"/var/lib/rancher/k3s/server/db/tmp-etcd/member","force-new-cluster":true,"heartbeat-interval":"500ms","election-timeout":"5s","initial-election-tick-advance":true,"snapshot-count":100000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://localhost:2380"],"listen-peer-urls":["http://localhost:2380"],"advertise-client-urls":["http://localhost:2379"],"listen-client-urls":["http://127.0.0.1:2399"],"listen-metrics-urls":[],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"","initial-cluster-state":"new","initial-cluster-token":"","quota-size-bytes":2147483648,"pre-vote":true,"initial-corrupt-check":false,"corrupt-check-time-interval":"0s","auto-compaction-mode":"","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}
Feb 20 21:13:50 node2 k3s[932]: panic: freepages: failed to get all reachable pages (page 4143: multiple references)
Feb 20 21:13:50 node2 k3s[932]: goroutine 186 [running]:
Feb 20 21:13:50 node2 k3s[932]: go.etcd.io/bbolt.(*DB).freepages.func2()
Feb 20 21:13:50 node2 k3s[932]:         /go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1056 +0x99
Feb 20 21:13:50 node2 k3s[932]: created by go.etcd.io/bbolt.(*DB).freepages
Feb 20 21:13:50 node2 k3s[932]:         /go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1054 +0x1f6
Feb 20 21:13:50 node2 systemd[1]: k3s.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 20 21:13:50 node2 systemd[1]: k3s.service: Failed with result 'exit-code'.
Feb 20 21:13:50 node2 systemd[1]: Failed to start Lightweight Kubernetes.
Feb 20 21:13:56 node2 systemd[1]: k3s.service: Scheduled restart job, restart counter is at 1.
Feb 20 21:13:56 node2 systemd[1]: Stopped Lightweight Kubernetes.
```

**Comment by boot-vue** [comment]
looks like `etcd` error

**Comment by boot-vue** [comment]
same with [etcd #10722](https://github.com/etcd-io/etcd/issues/10722)
