### ISSUE TITLE
Panic in servicelb.filterByIPFamily

### ISSUE THREAD

**Issue by greerga** [k3s-io/k3s#5744]
**Environmental Info:**
K3s Version: 
k3s version v1.24.1+k3s1 (0581808f)
go version go1.18.1
(or v1.23.6+k3s1)

Node(s) CPU architecture, OS, and Version: 
Linux rpi4b-{serial} 5.10.63-v8+ #1496 SMP PREEMPT Wed Dec 1 15:59:46 GMT 2021 aarch64 GNU/Linux

Cluster Configuration:
1 server, 3 agents

**Describe the bug:**
(The `pkg/servicelb/controller.go` line number is the same between between v1.23.6+k3s1 and v1.24.1+k3s1.)
```
k3s[7159]: E0619 01:03:39.704887    7159 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
k3s[7159]: goroutine 76588 [running]:
k3s[7159]: k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3f55400, 0x7713c60})
k3s[7159]: #011/go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.23.6-k3s1/pkg/util/runtime/runtime.go:74 +0xa0
k3s[7159]: k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0})
k3s[7159]: #011/go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.23.6-k3s1/pkg/util/runtime/runtime.go:48 +0x90
k3s[7159]: panic({0x3f55400, 0x7713c60})
k3s[7159]: #011/usr/local/go/src/runtime/panic.go:1038 +0x224
k3s[7159]: github.com/k3s-io/k3s/pkg/servicelb.filterByIPFamily({0x403f69a8c0, 0x4, 0x4}, 0x401c5af900)
k3s[7159]: #011/go/src/github.com/k3s-io/k3s/pkg/servicelb/controller.go:298 +0x78
k3s[7159]: github.com/k3s-io/k3s/pkg/servicelb.(*handler).podIPs(0x4004be00a0, {0x403d680b00, 0x4, 0x4}, 0x401c5af900)
k3s[7159]: #011/go/src/github.com/k3s-io/k3s/pkg/servicelb/controller.go:271 +0x274
k3s[7159]: github.com/k3s-io/k3s/pkg/servicelb.(*handler).updateService(0x4004be00a0, 0x401c5af900)
k3s[7159]: #011/go/src/github.com/k3s-io/k3s/pkg/servicelb/controller.go:187 +0x1ac
k3s[7159]: github.com/k3s-io/k3s/pkg/servicelb.(*handler).onChangeService(0x4004be00a0, {0x403a1f4b10, 0x10}, 0x401c5af900)
k3s[7159]: #011/go/src/github.com/k3s-io/k3s/pkg/servicelb/controller.go:150 +0x110
k3s[7159]: github.com/rancher/wrangler/pkg/generated/controllers/core/v1.FromServiceHandlerToHandler.func1({0x403a1f4b10, 0x10}, {0x4f6b3d8, 0x401c5af900})
k3s[7159]: #011/go/pkg/mod/github.com/rancher/wrangler@v0.8.11-0.20220211163748-d5a8ee98be5f/pkg/generated/controllers/core/v1/service.go:105 +0x5c
k3s[7159]: github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x400d747260, {0x403a1f4b10, 0x10}, {0x4f6b3d8, 0x401c5af900})
k3s[7159]: #011/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedcontroller.go:29 +0x48
k3s[7159]: github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0x4012641b40, {0x403a1f4b10, 0x10}, {0x4f6b3d8, 0x401c5af900})
k3s[7159]: #011/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedhandler.go:69 +0x208
k3s[7159]: github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0x40120dd4a0, {0x403a1f4b10, 0x10})
k3s[7159]: #011/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:215 +0xc8
k3s[7159]: github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0x40120dd4a0, {0x3d90000, 0x4041072900})
k3s[7159]: #011/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:197 +0xbc
k3s[7159]: github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0x40120dd4a0)
k3s[7159]: #011/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:174 +0x48
k3s[7159]: github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
k3s[7159]: #011/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:163
k3s[7159]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x401b2c4d90)
k3s[7159]: #011/go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.23.6-k3s1/pkg/util/wait/wait.go:155 +0x64
k3s[7159]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x401b2c4d90, {0x4f1d440, 0x401b67e660}, 0x1, 0x40017300c0)
k3s[7159]: #011/go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.23.6-k3s1/pkg/util/wait/wait.go:156 +0x94
k3s[7159]: k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x401b2c4d90, 0x3b9aca00, 0x0, 0x1, 0x40017300c0)
k3s[7159]: #011/go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.23.6-k3s1/pkg/util/wait/wait.go:133 +0x88
k3s[7159]: k8s.io/apimachinery/pkg/util/wait.Until(0x401b2c4d90, 0x3b9aca00, 0x40017300c0)
k3s[7159]: #011/go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.23.6-k3s1/pkg/util/wait/wait.go:90 +0x48
k3s[7159]: created by github.com/rancher/lasso/pkg/controller.(*controller).run
k3s[7159]: #011/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:134 +0x338
```

**Steps To Reproduce:**
- Upgraded K3s from v1.21.7+k3s1 to v1.23.6+k3s1 (stable) or v1.24.1+k3s1 (latest).
- No special installation parameters, although the automatic Traefik v1->v2 upgrade (this cluster has been around a while) failed (and continues to fail in jobs that get auto-created) so had to do that manually.

**Expected behavior:**
API server doesn't crash.

**Actual behavior:**
API server continually crashes.

**Additional context / logs:**
Worked fine in v1.21.7+k3s1 and before (don't think the cluster ever ran v1.22.x), but not v1.23.6+k3s1 and later.  Hosts do have IPv6 configured and usable although cluster itself started out IPv4-only.

**Backporting**
- [ ] Needs backporting to older releases

Edit: Fixed some version numbers because I had confused which upgrade caused it.

**Comment by greerga** [comment]
This is likely a (retroactive) duplicate of https://github.com/k3s-io/k3s/issues/5762 and possibly fixed in https://github.com/k3s-io/k3s/pull/5771.
