### ISSUE TITLE
Observed a panic: "invalid memory address or nil pointer dereference" repeated in syslog

### ISSUE THREAD

**Issue by hibby50** [k3s-io/k3s#5762]
I apologize for the sparse information. I am happy to provide anything asked for.

**Environmental Info:**
K3s Version: 
k3s version v1.23.6+k3s1 (418c3fa8)
go version go1.17.5

Node(s) CPU architecture, OS, and Version: 
Linux hibsrv 5.14.21-150400.22-default #1 SMP PREEMPT_DYNAMIC Wed May 11 06:57:18 UTC 2022 (49db222) x86_64 x86_64 x86_64 GNU/Linux

Cluster Configuration:
Single Node

**Describe the bug:**
I keep getting panics in syslog

**Steps To Reproduce:**
Unknown

- Installed K3s: 

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**
```
Jun 24 09:35:57 hibsrv k3s[7213]: E0624 09:35:57.219367    7213 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Jun 24 09:35:57 hibsrv k3s[7213]: goroutine 23246 [running]:
Jun 24 09:35:57 hibsrv k3s[7213]: k8s.io/apimachinery/pkg/util/runtime.logPanic({0x413c6e0, 0x7a1ac70})
Jun 24 09:35:57 hibsrv k3s[7213]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.23.6-k3s1/pkg/util/runtime/runtime.go:74 +0x7d
Jun 24 09:35:57 hibsrv k3s[7213]: k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc01a0b69c0})
Jun 24 09:35:57 hibsrv k3s[7213]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.23.6-k3s1/pkg/util/runtime/runtime.go:48 +0x75
Jun 24 09:35:57 hibsrv k3s[7213]: panic({0x413c6e0, 0x7a1ac70})
Jun 24 09:35:57 hibsrv k3s[7213]:         /usr/local/go/src/runtime/panic.go:1038 +0x215
Jun 24 09:35:57 hibsrv k3s[7213]: github.com/k3s-io/k3s/pkg/servicelb.filterByIPFamily({0x0, 0x4794c60, 0x40e601}, 0x0)
Jun 24 09:35:57 hibsrv k3s[7213]:         /go/src/github.com/k3s-io/k3s/pkg/servicelb/controller.go:298 +0x70
Jun 24 09:35:57 hibsrv k3s[7213]: github.com/k3s-io/k3s/pkg/servicelb.(*handler).podIPs(0xc011523540, {0xc01000a380, 0x1, 0x5238650}, 0xc00a2ab3c8)
Jun 24 09:35:57 hibsrv k3s[7213]:         /go/src/github.com/k3s-io/k3s/pkg/servicelb/controller.go:271 +0x293
Jun 24 09:35:57 hibsrv k3s[7213]: github.com/k3s-io/k3s/pkg/servicelb.(*handler).updateService(0xc011523540, 0xc00d58a000)
Jun 24 09:35:57 hibsrv k3s[7213]:         /go/src/github.com/k3s-io/k3s/pkg/servicelb/controller.go:187 +0x1da
Jun 24 09:35:57 hibsrv k3s[7213]: github.com/k3s-io/k3s/pkg/servicelb.(*handler).onChangeService(0x3, {0x10, 0xc00e733cca}, 0xc00d58a000)
Jun 24 09:35:57 hibsrv k3s[7213]:         /go/src/github.com/k3s-io/k3s/pkg/servicelb/controller.go:150 +0xd0
Jun 24 09:35:57 hibsrv k3s[7213]: github.com/rancher/wrangler/pkg/generated/controllers/core/v1.FromServiceHandlerToHandler.func1({0xc00d7f6f10, 0xffffffffffffffff}, {0x5186918, 0xc00d58a000})
Jun 24 09:35:57 hibsrv k3s[7213]:         /go/pkg/mod/github.com/rancher/wrangler@v0.8.11-0.20220211163748-d5a8ee98be5f/pkg/generated/controllers/core/v1/service.go:105 +0x44
Jun 24 09:35:57 hibsrv k3s[7213]: github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x4193ea0, {0xc00d7f6f10, 0xc00d7ea0c0}, {0x5186918, 0xc00d58a000})
Jun 24 09:35:57 hibsrv k3s[7213]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedcontroller.go:29 +0x38
Jun 24 09:35:57 hibsrv k3s[7213]: github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc0048f0a98, {0xc00d7f6f10, 0xe}, {0x5186918, 0xc00d58a000})
Jun 24 09:35:57 hibsrv k3s[7213]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/sharedhandler.go:69 +0x203
Jun 24 09:35:57 hibsrv k3s[7213]: github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0018df760, {0xc00d7f6f10, 0xe})
Jun 24 09:35:57 hibsrv k3s[7213]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:215 +0x93
Jun 24 09:35:57 hibsrv k3s[7213]: github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0018df760, {0x3f70c00, 0xc01a0b69c0})
Jun 24 09:35:57 hibsrv k3s[7213]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:197 +0x10e
Jun 24 09:35:57 hibsrv k3s[7213]: github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0018df760)
Jun 24 09:35:57 hibsrv k3s[7213]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:174 +0x46
Jun 24 09:35:57 hibsrv k3s[7213]: github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
Jun 24 09:35:57 hibsrv k3s[7213]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:163
Jun 24 09:35:57 hibsrv k3s[7213]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00c94ff00)
Jun 24 09:35:57 hibsrv k3s[7213]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.23.6-k3s1/pkg/util/wait/wait.go:155 +0x67
Jun 24 09:35:57 hibsrv k3s[7213]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x3effb00, {0x51345c0, 0xc00d8b3440}, 0x1, 0xc001920300)
Jun 24 09:35:57 hibsrv k3s[7213]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.23.6-k3s1/pkg/util/wait/wait.go:156 +0xb6
Jun 24 09:35:57 hibsrv k3s[7213]: k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0, 0x3b9aca00, 0x0, 0x1, 0x442325)
Jun 24 09:35:57 hibsrv k3s[7213]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.23.6-k3s1/pkg/util/wait/wait.go:133 +0x89
Jun 24 09:35:57 hibsrv k3s[7213]: k8s.io/apimachinery/pkg/util/wait.Until(0x0, 0xc001920300, 0x0)
Jun 24 09:35:57 hibsrv k3s[7213]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.23.6-k3s1/pkg/util/wait/wait.go:90 +0x25
Jun 24 09:35:57 hibsrv k3s[7213]: created by github.com/rancher/lasso/pkg/controller.(*controller).run
Jun 24 09:35:57 hibsrv k3s[7213]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20210616224652-fc3ebd901c08/pkg/controller/controller.go:134 +0x2c6
```

**Backporting**
Unknown

- [ ] Needs backporting to older releases

**Comment by hibby50** [comment]
I ended up just doing a clean install, my installation was over 2 years old so something probably got messed up along the way.

**Comment by brandond** [comment]
Reopening to fix

**Comment by ygelfand** [comment]
fyi ran into this after a v1.24.1 -> v1.24.2 upgrade.  appears to be triggered because I have `Service` w/ `type: ExternalName` which cannot have a `ipFamilyPolicy`.    kubelet would periodically crash on each node as a result.  crashing seems to have stopped when I removed those objects (though would obviously like some way to be able to put them back).

**Comment by brandond** [comment]
Ahh, that's interesting. I'm not sure why we'd even be processing services of any type other than LoadBalancer to begin with.

**Comment by ygelfand** [comment]
looks like this was introduced https://github.com/k3s-io/k3s/commit/f4cc1b8788f#diff-4d789e1722f0b3051229e8c34d4bd27a325ba3410d1e8b4c45104720f2bba218L139-L144 , the check is now in `deployPod`, but assuming applying empty set of objects returns w/o error, and proceeds on to `updateService` for all service types.

**Comment by ShylajaDevadiga** [comment]
Validated on v1.24.2-rc1+k3s2
## Environment Details 
*Infrastructure*
[ *] Cloud

*Node(s) CPU architecture, OS, and Version:*

Ubuntu 20:.04

 
*Cluster Configuration:*

Single node

## Replication Steps
 ```
curl -fL https://get.k3s.io | INSTALL_K3S_VERSION=v1.24.1+k3s1 sh -s - server
```
Apply the test service provided in the verification steps in the PR
```
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
spec:
  type: ExternalName
  externalName: test.example.com
```
Upgrade to 
```
curl -fL https://get.k3s.io | INSTALL_K3S_VERSION=v1.24.2+k3s1 sh -s - server
```
Check the logs
```
ubuntu@ip-172-31-0-32:~$ journalctl -u k3s |grep panic
Jul 05 21:55:23 ip-172-31-0-32 k3s[35343]: E0705 21:55:23.566165   35343 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
Jul 05 21:55:23 ip-172-31-0-32 k3s[35343]: panic({0x43dd000, 0x7b71d00})
Jul 05 21:55:23 ip-172-31-0-32 k3s[35343]:         /usr/local/go/src/runtime/panic.go:838 +0x207
Jul 05 21:55:23 ip-172-31-0-32 k3s[35343]: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
```

**Validated on-**
k3s v1.24.2-rc1+k3s2

 
## Validation Steps
 
```
curl -fL https://get.k3s.io | INSTALL_K3S_VERSION=v1.24.1+k3s1 sh -s - server
```
Apply the test service provided in the verification steps in the PR
```
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
spec:
  type: ExternalName
  externalName: test.example.com
```
Upgrade to 
```
curl -fL https://get.k3s.io | INSTALL_K3S_VERSION=v1.24.2-rc1+k3s2 sh -s - server
```
 
**Results:**
No panic is seen. Service was deployed correctly
