### ISSUE TITLE
k3s not started: Containerd panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by T-M-A** [k3s-io/k3s#6673]
**Environmental Info:**
```
K3s Version: 
k3s version v1.26.0+k3s1 (fae88176)
go version go1.19.4

```

on the old version, the same behavior
```
version v1.25.2+k3s1 (53c268d8)
go version go1.19.1
```
Node(s) CPU architecture, OS, and Version: 
`Linux home 5.19.0-26-generic #27-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov 23 20:44:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
Cluster Configuration:

1 server on Ubuntu 22.10

**Describe the bug:**

From some point an error appeared , k3s does not start via systemd

```
systemctl start k3s.service
Job for k3s.service failed because the control process exited with error code.
See "systemctl status k3s.service" and "journalctl -xeu k3s.service" for details.
```
on containerd log:
```
time="2022-12-26T02:56:28.372340078Z" level=info msg="Connect containerd service"
time="2022-12-26T02:56:28.372464580Z" level=info msg="Get image filesystem path \"/var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs\""
time="2022-12-26T02:56:28.376197497Z" level=info msg="Start subscribing containerd event"
time="2022-12-26T02:56:28.376358600Z" level=info msg="Start recovering state"
time="2022-12-26T02:56:28.383997225Z" level=info msg=serving... address=/run/k3s/containerd/containerd.sock.ttrpc
time="2022-12-26T02:56:28.384219941Z" level=info msg=serving... address=/run/k3s/containerd/containerd.sock
time="2022-12-26T02:56:28.384283755Z" level=info msg="containerd successfully booted in 0.083780s"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x76b4b8]

goroutine 74 [running]:
go.etcd.io/bbolt.(*Bucket).Bucket(0x0, {0x37e0fec, 0x6, 0x6})
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/bucket.go:97 +0x38
github.com/containerd/containerd/metadata.isRootRef(0xc0005355c0?)
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/metadata/gc.go:500 +0x2e
github.com/containerd/containerd/metadata.scanRoots.func7.1({0x7f4afaac2791, 0x40, 0x40}, {0x0?, 0x1?, 0x0?})
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/metadata/gc.go:268 +0xaa
go.etcd.io/bbolt.(*Bucket).ForEach(0xc0005355c0, 0xc00065b4d8)
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/bucket.go:390 +0xa4
github.com/containerd/containerd/metadata.scanRoots.func7({0x7f4afaa55020, 0x9, 0x9}, {0x0?, 0x457469?, 0x6?})
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/metadata/gc.go:264 +0xfd
go.etcd.io/bbolt.(*Bucket).ForEach(0xc000535580, 0xc00065b650)
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/bucket.go:390 +0xa4
github.com/containerd/containerd/metadata.scanRoots({0x2702e18, 0xc00054e000}, 0x0?, 0xc0004c5920)
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/metadata/gc.go:258 +0x628
github.com/containerd/containerd/metadata.(*DB).getMarked.func1(0xc00080fc00)
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/metadata/db.go:386 +0x154
go.etcd.io/bbolt.(*DB).View(0x0?, 0xc0000198a0)
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/db.go:772 +0x82
github.com/containerd/containerd/metadata.(*DB).getMarked(0x656863732e31762e?, {0x2702e18?, 0xc000620840?})
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/metadata/db.go:369 +0x70
github.com/containerd/containerd/metadata.(*DB).GarbageCollect(0xc0003c6070, {0x2702e18, 0xc000620840})
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/metadata/db.go:285 +0x8b
github.com/containerd/containerd/gc/scheduler.(*gcScheduler).run(0xc00011f0e0, {0x2702e18, 0xc000620840})
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/gc/scheduler/scheduler.go:310 +0x4df
created by github.com/containerd/containerd/gc/scheduler.init.0.func1
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/gc/scheduler/scheduler.go:132 +0x385
```
**Steps To Reproduce:**

- Installed K3s: 
`
/usr/local/bin/k3s server --disable=traefik
`

**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

```
/usr/local/bin/k3s server --disable=traefik --debug
INFO[0000] Starting k3s v1.26.0+k3s1 (fae88176)
INFO[0000] Configuring sqlite3 database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s
INFO[0000] Configuring database table schema and indexes, this may take a moment...
INFO[0000] Database tables and indexes are up to date
INFO[0000] Kine available at unix://kine.sock
INFO[0000] Reconciling bootstrap data between datastore and disk
DEBU[0000] Reconciling PasswdFile at '/var/lib/rancher/k3s/server/cred/passwd'
DEBU[0000] Reconciling RequestHeaderCA at '/var/lib/rancher/k3s/server/tls/request-header-ca.crt'
DEBU[0000] Reconciling RequestHeaderCAKey at '/var/lib/rancher/k3s/server/tls/request-header-ca.key'
DEBU[0000] Reconciling ClientCA at '/var/lib/rancher/k3s/server/tls/client-ca.crt'
DEBU[0000] Reconciling ETCDPeerCA at '/var/lib/rancher/k3s/server/tls/etcd/peer-ca.crt'
DEBU[0000] Reconciling ETCDPeerCAKey at '/var/lib/rancher/k3s/server/tls/etcd/peer-ca.key'
DEBU[0000] Reconciling ETCDServerCA at '/var/lib/rancher/k3s/server/tls/etcd/server-ca.crt'
DEBU[0000] Reconciling ETCDServerCAKey at '/var/lib/rancher/k3s/server/tls/etcd/server-ca.key'
DEBU[0000] Reconciling ServiceKey at '/var/lib/rancher/k3s/server/tls/service.key'
DEBU[0000] Reconciling ClientCAKey at '/var/lib/rancher/k3s/server/tls/client-ca.key'
DEBU[0000] Reconciling IPSECKey at '/var/lib/rancher/k3s/server/cred/ipsec.psk'
DEBU[0000] Reconciling ServerCA at '/var/lib/rancher/k3s/server/tls/server-ca.crt'
DEBU[0000] Reconciling ServerCAKey at '/var/lib/rancher/k3s/server/tls/server-ca.key'
INFO[0000] Running kube-apiserver --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,k3s --authorization-mode=Node,RBAC --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/k3s/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/k3s/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --etcd-servers=unix://kine.sock --feature-gates=JobTrackingWithFinalizers=true --kubelet-certificate-authority=/var/lib/rancher/k3s/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/k3s/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/k3s/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/k3s/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6444 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-cluster-ip-range=10.43.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.crt --tls-private-key-file=/var/lib/rancher/k3s/server/tls/serving-kube-apiserver.key
INFO[0000] Running kube-scheduler --authentication-kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --authorization-kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --bind-address=127.0.0.1 --kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.kubeconfig --leader-elect=false --profiling=false --secure-port=10259
INFO[0000] Tunnel server egress proxy mode: agent
INFO[0000] Tunnel server egress proxy waiting for runtime core to become available
W1226 02:46:01.697950    1789 feature_gate.go:241] Setting GA feature gate JobTrackingWithFinalizers=true. It will be removed in a future release.
INFO[0000] Waiting for API server to become available
INFO[0000] Running kube-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --authorization-kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --bind-address=127.0.0.1 --cluster-cidr=10.42.0.0/16 --cluster-signing-kube-apiserver-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --cluster-signing-kube-apiserver-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-client-cert-file=/var/lib/rancher/k3s/server/tls/client-ca.crt --cluster-signing-kubelet-client-key-file=/var/lib/rancher/k3s/server/tls/client-ca.key --cluster-signing-kubelet-serving-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --cluster-signing-kubelet-serving-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --cluster-signing-legacy-unknown-cert-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --cluster-signing-legacy-unknown-key-file=/var/lib/rancher/k3s/server/tls/server-ca.key --configure-cloud-routes=false --controllers=*,-service,-route,-cloud-node-lifecycle --feature-gates=JobTrackingWithFinalizers=true --kubeconfig=/var/lib/rancher/k3s/server/cred/controller.kubeconfig --leader-elect=false --profiling=false --root-ca-file=/var/lib/rancher/k3s/server/tls/server-ca.crt --secure-port=10257 --service-account-private-key-file=/var/lib/rancher/k3s/server/tls/service.key --service-cluster-ip-range=10.43.0.0/16 --use-service-account-credentials=true
I1226 02:46:01.699608    1789 server.go:569] external host was not specified, using 192.168.88.128
INFO[0000] Running cloud-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/var/lib/rancher/k3s/server/cred/cloud-controller.kubeconfig --authorization-kubeconfig=/var/lib/rancher/k3s/server/cred/cloud-controller.kubeconfig --bind-address=127.0.0.1 --cloud-config=/var/lib/rancher/k3s/server/etc/cloud-config.yaml --cloud-provider=k3s --cluster-cidr=10.42.0.0/16 --configure-cloud-routes=false --controllers=*,-route --kubeconfig=/var/lib/rancher/k3s/server/cred/cloud-controller.kubeconfig --leader-elect=false --leader-elect-resource-name=k3s-cloud-controller-manager --node-status-update-frequency=1m0s --profiling=false
I1226 02:46:01.701086    1789 server.go:171] Version: v1.26.0+k3s1
I1226 02:46:01.701229    1789 server.go:173] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
INFO[0000] Server node token is available at /var/lib/rancher/k3s/server/token
INFO[0000] To join server node to cluster: k3s server -s https://192.168.88.128:6443 -t ${SERVER_NODE_TOKEN}
INFO[0000] Agent node token is available at /var/lib/rancher/k3s/server/agent-token
INFO[0000] To join agent node to cluster: k3s agent -s https://192.168.88.128:6443 -t ${AGENT_NODE_TOKEN}
INFO[0000] Wrote kubeconfig /etc/rancher/k3s/k3s.yaml
INFO[0000] Run: k3s kubectl
I1226 02:46:01.778692    1789 shared_informer.go:273] Waiting for caches to sync for node_authorizer
I1226 02:46:01.783072    1789 plugins.go:158] Loaded 12 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,NodeRestriction,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,RuntimeClass,DefaultIngressClass,MutatingAdmissionWebhook.
I1226 02:46:01.783412    1789 plugins.go:161] Loaded 12 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,PodSecurity,Priority,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,ValidatingAdmissionPolicy,ValidatingAdmissionWebhook,ResourceQuota.
INFO[0000] Cluster-Http-Server 2022/12/26 02:46:01 http: TLS handshake error from 127.0.0.1:55982: remote error: tls: bad certificate
INFO[0000] Cluster-Http-Server 2022/12/26 02:46:01 http: TLS handshake error from 127.0.0.1:56010: remote error: tls: bad certificate
DEBU[0000] Password verified locally for node 'home'
INFO[0000] certificate CN=home signed by CN=k3s-server-ca@1665311262: notBefore=2022-10-09 10:27:42 +0000 UTC notAfter=2023-12-26 02:46:01 +0000 UTC
W1226 02:46:01.904884    1789 genericapiserver.go:660] Skipping API apiextensions.k8s.io/v1beta1 because it has no resources.
I1226 02:46:01.909630    1789 instance.go:277] Using reconciler: lease
INFO[0000] certificate CN=system:node:home,O=system:nodes signed by CN=k3s-client-ca@1665311262: notBefore=2022-10-09 10:27:42 +0000 UTC notAfter=2023-12-26 02:46:01 +0000 UTC
INFO[0000] Module overlay was already loaded
INFO[0000] Module nf_conntrack was already loaded
INFO[0000] Module br_netfilter was already loaded
INFO[0000] Module iptable_nat was already loaded
INFO[0000] Module iptable_filter was already loaded
DEBU[0000] getConntrackMax: using conntrack-min
DEBU[0000] Creating the CNI conf in directory /var/lib/rancher/k3s/agent/etc/cni/net.d
DEBU[0000] Creating the flannel configuration for backend vxlan in file /var/lib/rancher/k3s/agent/etc/flannel/net-conf.json
DEBU[0000] The flannel configuration is {
	"Network": "10.42.0.0/16",
	"EnableIPv6": false,
	"EnableIPv4": true,
	"IPv6Network": "::/0",
	"Backend": {
	"Type": "vxlan"
}
}
DEBU[0000] Searching for nvidia container runtime at /usr/local/nvidia/toolkit/nvidia-container-runtime
DEBU[0000] nvidia container runtime not found at /usr/local/nvidia/toolkit/nvidia-container-runtime
DEBU[0000] Searching for nvidia container runtime at /usr/bin/nvidia-container-runtime
DEBU[0000] nvidia container runtime not found at /usr/bin/nvidia-container-runtime
DEBU[0000] Searching for nvidia-experimental container runtime at /usr/local/nvidia/toolkit/nvidia-container-runtime-experimental
DEBU[0000] nvidia-experimental container runtime not found at /usr/local/nvidia/toolkit/nvidia-container-runtime-experimental
DEBU[0000] Searching for nvidia-experimental container runtime at /usr/bin/nvidia-container-runtime-experimental
DEBU[0000] nvidia-experimental container runtime not found at /usr/bin/nvidia-container-runtime-experimental
INFO[0000] Running containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd
INFO[2022-12-26T02:46:02.232928934Z] starting containerd                           revision= version=v1.6.12-k3s1
INFO[2022-12-26T02:46:02.300662203Z] loading plugin "io.containerd.content.v1.content"...  type=io.containerd.content.v1
INFO[2022-12-26T02:46:02.301002522Z] loading plugin "io.containerd.snapshotter.v1.aufs"...  type=io.containerd.snapshotter.v1
INFO[2022-12-26T02:46:02.308379147Z] skip loading plugin "io.containerd.snapshotter.v1.aufs"...  error="aufs is not supported (modprobe aufs failed: exit status 1 \"modprobe: FATAL: Module aufs not found in directory /lib/modules/5.19.0-26-generic\\n\"): skip plugin" type=io.containerd.snapshotter.v1
INFO[2022-12-26T02:46:02.308496024Z] loading plugin "io.containerd.snapshotter.v1.btrfs"...  type=io.containerd.snapshotter.v1
INFO[2022-12-26T02:46:02.308948070Z] skip loading plugin "io.containerd.snapshotter.v1.btrfs"...  error="path /var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.btrfs (ext4) must be a btrfs filesystem to be used with the btrfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
INFO[2022-12-26T02:46:02.309061259Z] loading plugin "io.containerd.snapshotter.v1.devmapper"...  type=io.containerd.snapshotter.v1
WARN[2022-12-26T02:46:02.309124623Z] failed to load plugin io.containerd.snapshotter.v1.devmapper  error="devmapper not configured"
INFO[2022-12-26T02:46:02.309168861Z] loading plugin "io.containerd.snapshotter.v1.native"...  type=io.containerd.snapshotter.v1
INFO[2022-12-26T02:46:02.309259100Z] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  type=io.containerd.snapshotter.v1
INFO[2022-12-26T02:46:02.309686808Z] loading plugin "io.containerd.snapshotter.v1.fuse-overlayfs"...  type=io.containerd.snapshotter.v1
INFO[2022-12-26T02:46:02.309801960Z] loading plugin "io.containerd.snapshotter.v1.stargz"...  type=io.containerd.snapshotter.v1
INFO[2022-12-26T02:46:02.311039146Z] loading plugin "io.containerd.snapshotter.v1.zfs"...  type=io.containerd.snapshotter.v1
INFO[2022-12-26T02:46:02.311518067Z] skip loading plugin "io.containerd.snapshotter.v1.zfs"...  error="path /var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin" type=io.containerd.snapshotter.v1
INFO[2022-12-26T02:46:02.311617307Z] loading plugin "io.containerd.metadata.v1.bolt"...  type=io.containerd.metadata.v1
WARN[2022-12-26T02:46:02.311709196Z] could not use snapshotter devmapper in metadata plugin  error="devmapper not configured"
INFO[2022-12-26T02:46:02.311753334Z] metadata content store policy set             policy=shared
INFO[2022-12-26T02:46:02.312167167Z] loading plugin "io.containerd.differ.v1.walking"...  type=io.containerd.differ.v1
INFO[2022-12-26T02:46:02.312251019Z] loading plugin "io.containerd.event.v1.exchange"...  type=io.containerd.event.v1
INFO[2022-12-26T02:46:02.312304245Z] loading plugin "io.containerd.gc.v1.scheduler"...  type=io.containerd.gc.v1
INFO[2022-12-26T02:46:02.312412047Z] loading plugin "io.containerd.service.v1.introspection-service"...  type=io.containerd.service.v1
INFO[2022-12-26T02:46:02.312478798Z] loading plugin "io.containerd.service.v1.containers-service"...  type=io.containerd.service.v1
INFO[2022-12-26T02:46:02.312572987Z] loading plugin "io.containerd.service.v1.content-service"...  type=io.containerd.service.v1
INFO[2022-12-26T02:46:02.312994707Z] loading plugin "io.containerd.service.v1.diff-service"...  type=io.containerd.service.v1
INFO[2022-12-26T02:46:02.313093172Z] loading plugin "io.containerd.service.v1.images-service"...  type=io.containerd.service.v1
INFO[2022-12-26T02:46:02.313146460Z] loading plugin "io.containerd.service.v1.leases-service"...  type=io.containerd.service.v1
INFO[2022-12-26T02:46:02.313199924Z] loading plugin "io.containerd.service.v1.namespaces-service"...  type=io.containerd.service.v1
INFO[2022-12-26T02:46:02.313250637Z] loading plugin "io.containerd.service.v1.snapshots-service"...  type=io.containerd.service.v1
INFO[2022-12-26T02:46:02.313305238Z] loading plugin "io.containerd.runtime.v1.linux"...  type=io.containerd.runtime.v1
INFO[2022-12-26T02:46:02.313476154Z] loading plugin "io.containerd.runtime.v2.task"...  type=io.containerd.runtime.v2
INFO[2022-12-26T02:46:02.313677670Z] loading plugin "io.containerd.monitor.v1.cgroups"...  type=io.containerd.monitor.v1
INFO[2022-12-26T02:46:02.314411946Z] loading plugin "io.containerd.service.v1.tasks-service"...  type=io.containerd.service.v1
INFO[2022-12-26T02:46:02.314512985Z] loading plugin "io.containerd.grpc.v1.introspection"...  type=io.containerd.grpc.v1
INFO[2022-12-26T02:46:02.314603412Z] loading plugin "io.containerd.internal.v1.restart"...  type=io.containerd.internal.v1
INFO[2022-12-26T02:46:02.314755990Z] loading plugin "io.containerd.grpc.v1.containers"...  type=io.containerd.grpc.v1
INFO[2022-12-26T02:46:02.314814866Z] loading plugin "io.containerd.grpc.v1.content"...  type=io.containerd.grpc.v1
INFO[2022-12-26T02:46:02.314865667Z] loading plugin "io.containerd.grpc.v1.diff"...  type=io.containerd.grpc.v1
INFO[2022-12-26T02:46:02.314919743Z] loading plugin "io.containerd.grpc.v1.events"...  type=io.containerd.grpc.v1
INFO[2022-12-26T02:46:02.314971981Z] loading plugin "io.containerd.grpc.v1.healthcheck"...  type=io.containerd.grpc.v1
INFO[2022-12-26T02:46:02.315023520Z] loading plugin "io.containerd.grpc.v1.images"...  type=io.containerd.grpc.v1
INFO[2022-12-26T02:46:02.315104109Z] loading plugin "io.containerd.grpc.v1.leases"...  type=io.containerd.grpc.v1
INFO[2022-12-26T02:46:02.315155897Z] loading plugin "io.containerd.grpc.v1.namespaces"...  type=io.containerd.grpc.v1
INFO[2022-12-26T02:46:02.315213711Z] loading plugin "io.containerd.internal.v1.opt"...  type=io.containerd.internal.v1
INFO[2022-12-26T02:46:02.315494204Z] loading plugin "io.containerd.grpc.v1.snapshots"...  type=io.containerd.grpc.v1
INFO[2022-12-26T02:46:02.315573930Z] loading plugin "io.containerd.grpc.v1.tasks"...  type=io.containerd.grpc.v1
INFO[2022-12-26T02:46:02.315624856Z] loading plugin "io.containerd.grpc.v1.version"...  type=io.containerd.grpc.v1
INFO[2022-12-26T02:46:02.315675557Z] loading plugin "io.containerd.tracing.processor.v1.otlp"...  type=io.containerd.tracing.processor.v1
INFO[2022-12-26T02:46:02.315735971Z] skip loading plugin "io.containerd.tracing.processor.v1.otlp"...  error="no OpenTelemetry endpoint: skip plugin" type=io.containerd.tracing.processor.v1
INFO[2022-12-26T02:46:02.315789984Z] loading plugin "io.containerd.internal.v1.tracing"...  type=io.containerd.internal.v1
ERRO[2022-12-26T02:46:02.315858735Z] failed to initialize a tracing processor "otlp"  error="no OpenTelemetry endpoint: skip plugin"
INFO[2022-12-26T02:46:02.316077214Z] loading plugin "io.containerd.grpc.v1.cri"...  type=io.containerd.grpc.v1
INFO[2022-12-26T02:46:02.316765090Z] Start cri plugin with config {PluginConfig:{ContainerdConfig:{Snapshotter:overlayfs DefaultRuntimeName:runc DefaultRuntime:{Type: Path: Engine: PodAnnotations:[] ContainerAnnotations:[] Root: Options:map[] PrivilegedWithoutHostDevices:false BaseRuntimeSpec: NetworkPluginConfDir: NetworkPluginMaxConfNum:0} UntrustedWorkloadRuntime:{Type: Path: Engine: PodAnnotations:[] ContainerAnnotations:[] Root: Options:map[] PrivilegedWithoutHostDevices:false BaseRuntimeSpec: NetworkPluginConfDir: NetworkPluginMaxConfNum:0} Runtimes:map[runc:{Type:io.containerd.runc.v2 Path: Engine: PodAnnotations:[] ContainerAnnotations:[] Root: Options:map[SystemdCgroup:false] PrivilegedWithoutHostDevices:false BaseRuntimeSpec: NetworkPluginConfDir: NetworkPluginMaxConfNum:0}] NoPivot:false DisableSnapshotAnnotations:true DiscardUnpackedLayers:false IgnoreRdtNotEnabledErrors:false} CniConfig:{NetworkPluginBinDir:/var/lib/rancher/k3s/data/81710a58143cb0c5b20f2a31e88a85b3401f2d407649b5988eacbe3e3ba1a203/bin NetworkPluginConfDir:/var/lib/rancher/k3s/agent/etc/cni/net.d NetworkPluginMaxConfNum:1 NetworkPluginConfTemplate: IPPreference:} Registry:{ConfigPath: Mirrors:map[] Configs:map[] Auths:map[] Headers:map[]} ImageDecryption:{KeyModel:node} DisableTCPService:true StreamServerAddress:127.0.0.1 StreamServerPort:10010 StreamIdleTimeout:4h0m0s EnableSelinux:false SelinuxCategoryRange:1024 SandboxImage:rancher/mirrored-pause:3.6 StatsCollectPeriod:10 SystemdCgroup:false EnableTLSStreaming:false X509KeyPairStreaming:{TLSCertFile: TLSKeyFile:} MaxContainerLogLineSize:16384 DisableCgroup:false DisableApparmor:false RestrictOOMScoreAdj:false MaxConcurrentDownloads:3 DisableProcMount:false UnsetSeccompProfile: TolerateMissingHugetlbController:true DisableHugetlbController:true DeviceOwnershipFromSecurityContext:false IgnoreImageDefinedVolumes:false NetNSMountsUnderStateDir:false EnableUnprivilegedPorts:true EnableUnprivilegedICMP:true} ContainerdRootDir:/var/lib/rancher/k3s/agent/containerd ContainerdEndpoint:/run/k3s/containerd/containerd.sock RootDir:/var/lib/rancher/k3s/agent/containerd/io.containerd.grpc.v1.cri StateDir:/run/k3s/containerd/io.containerd.grpc.v1.cri}
INFO[2022-12-26T02:46:02.316892567Z] Connect containerd service
INFO[2022-12-26T02:46:02.317002557Z] Get image filesystem path "/var/lib/rancher/k3s/agent/containerd/io.containerd.snapshotter.v1.overlayfs"
INFO[2022-12-26T02:46:02.318946880Z] Start subscribing containerd event
INFO[2022-12-26T02:46:02.319137146Z] Start recovering state
I1226 02:46:02.333149    1789 trace.go:219] Trace[608130009]: "List(recursive=true) etcd3" audit-id:,key:/apiextensions.k8s.io/customresourcedefinitions,resourceVersion:,resourceVersionMatch:,limit:10000,continue: (26-Dec-2022 02:46:01.831) (total time: 501ms):
Trace[608130009]: [501.323413ms] [501.323413ms] END
INFO[2022-12-26T02:46:02.351387395Z] serving...                                    address=/run/k3s/containerd/containerd.sock.ttrpc
INFO[2022-12-26T02:46:02.351724913Z] serving...                                    address=/run/k3s/containerd/containerd.sock
INFO[2022-12-26T02:46:02.351805027Z] containerd successfully booted in 0.120558s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x76b4b8]

goroutine 49 [running]:
go.etcd.io/bbolt.(*Bucket).Bucket(0x0, {0x37e0fec, 0x6, 0x6})
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/bucket.go:97 +0x38
github.com/containerd/containerd/metadata.isRootRef(0xc0008bb9c0?)
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/metadata/gc.go:500 +0x2e
github.com/containerd/containerd/metadata.scanRoots.func7.1({0x7f3ca02c2791, 0x40, 0x40}, {0x0?, 0x1?, 0x0?})
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/metadata/gc.go:268 +0xaa
go.etcd.io/bbolt.(*Bucket).ForEach(0xc0008bb9c0, 0xc0009c14d8)
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/bucket.go:390 +0xa4
github.com/containerd/containerd/metadata.scanRoots.func7({0x7f3ca0255020, 0x9, 0x9}, {0x0?, 0x457469?, 0x6?})
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/metadata/gc.go:264 +0xfd
go.etcd.io/bbolt.(*Bucket).ForEach(0xc0008bb980, 0xc0009c1650)
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/bucket.go:390 +0xa4
github.com/containerd/containerd/metadata.scanRoots({0x2702e18, 0xc00093a040}, 0x0?, 0xc0000ce960)
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/metadata/gc.go:258 +0x628
github.com/containerd/containerd/metadata.(*DB).getMarked.func1(0xc0007440e0)
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/metadata/db.go:386 +0x154
go.etcd.io/bbolt.(*DB).View(0x0?, 0xc0006bc8a0)
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/vendor/go.etcd.io/bbolt/db.go:772 +0x82
github.com/containerd/containerd/metadata.(*DB).getMarked(0x0?, {0x2702e18?, 0xc0005e3340?})
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/metadata/db.go:369 +0x70
github.com/containerd/containerd/metadata.(*DB).GarbageCollect(0xc0003f9880, {0x2702e18, 0xc0005e3340})
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/metadata/db.go:285 +0x8b
github.com/containerd/containerd/gc/scheduler.(*gcScheduler).run(0xc0005e5380, {0x2702e18, 0xc0005e3340})
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/gc/scheduler/scheduler.go:310 +0x4df
created by github.com/containerd/containerd/gc/scheduler.init.0.func1
	/go/src/github.com/k3s-io/k3s/build/src/github.com/containerd/containerd/gc/scheduler/scheduler.go:132 +0x385
containerd: exit status 2

```

**Comment by brandond** [comment]
It would appear that you your containerd image store has been corrupted. Was this node shut down unexpectedly at some point? I don't believe there's any way to correct the corruption; you'll have to delete the image store from disk. Once that is done containerd should be able to start without crashing.

**Comment by T-M-A** [comment]
Thank you very much! It could really be so.
