### ISSUE TITLE
K3s fails to start after host IP change

### ISSUE THREAD

**Issue by NunoSav** [k3s-io/k3s#6969]
**Environmental Info:**
K3s Version: v1.25.5+k3s1

Node(s) CPU architecture, OS, and Version: x86_64, Ubuntu 22.04

Cluster Configuration: Single node installed by running `curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644`

**Describe the bug:**
I have a k3s cluster running on a IPC (air gapped solution). One of the services running in it offers the possibility of changing host's (IPC) IP address, this uses `netplan set` commands followed by `reboot now`. Both commands work but after the IPC reboots the cluster is unavailable.

**Steps To Reproduce:**

- Installed K3s: 

**Expected behavior:**
k3s service is able start and be available under the new host IP address.

**Actual behavior:**
k3s service fails to start and is unavailable.

**Additional context / logs:**

`sudo systemctl status k3s` returns:
```
● k3s.service - Lightweight Kubernetes
     Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2023-02-16 11:20:19 UTC; 971ms ago
       Docs: https://k3s.io
    Process: 57664 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=0/SUCCESS)
    Process: 57666 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
    Process: 57667 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
    Process: 57668 ExecStart=/usr/local/bin/k3s server --write-kubeconfig-mode 644 (code=exited, status=2)
   Main PID: 57668 (code=exited, status=2)
        CPU: 21.365s
```

`journalctl -u k3s -S today` has in it some errors:
```
k3s[823]: time="2023-02-16T08:38:09Z" level=info msg="Annotations and labels have already set on node: edc-ipc-1"
k3s[823]: time="2023-02-16T08:38:09Z" level=info msg="Starting flannel with backend vxlan"
k3s[823]: time="2023-02-16T08:38:09Z" level=info msg="Flannel found PodCIDR assigned for node edc-ipc-1"
k3s[823]: time="2023-02-16T08:38:09Z" level=info msg="The interface enp2s0 with ipv6 address 2001:8a0:fffd:3e00:205:b7ff:fef1:4ad0 will be used by flannel"
k3s[823]: I0216 08:38:09.435522     823 kube.go:126] Waiting 10m0s for node controller to sync
k3s[823]: I0216 08:38:09.435561     823 kube.go:431] Starting kube subnet manager
k3s[823]: I0216 08:38:09.444339     823 kube.go:485] Creating the node lease for IPv6. This is the n.Spec.PodCIDRs: [10.42.0.0/24]
k3s[823]: E0216 08:38:09.445403     823 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
k3s[823]: goroutine 28700 [running]:
k3s[823]: k8s.io/apimachinery/pkg/util/runtime.logPanic({0x45fb7a0?, 0x7f6c0e0})
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/runtime/runtime.go:75 +0x99
k3s[823]: k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe?})
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/runtime/runtime.go:49 +0x75
k3s[823]: panic({0x45fb7a0, 0x7f6c0e0})
k3s[823]:         /usr/local/go/src/runtime/panic.go:884 +0x212
k3s[823]: github.com/flannel-io/flannel/pkg/ip.FromIP6Net(0xc00aa12760?)
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/pkg/ip/ip6net.go:158 +0x18
k3s[823]: github.com/flannel-io/flannel/subnet/kube.(*kubeSubnetManager).nodeToLease(_, {{{0x0, 0x0}, {0x0, 0x0}}, {{0xc00aa12620, 0x9}, {0x0, 0x0}, {0x0, ...}, ...}, ...})
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/subnet/kube/kube.go:499 +0x446
k3s[823]: github.com/flannel-io/flannel/subnet/kube.(*kubeSubnetManager).handleAddLeaseEvent(0xc015da69a0, 0x0, {0x4ca5f40?, 0xc01636e400})
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/subnet/kube/kube.go:220 +0x125
k3s[823]: github.com/flannel-io/flannel/subnet/kube.newKubeSubnetManager.func3({0x4ca5f40?, 0xc01636e400?})
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/subnet/kube/kube.go:184 +0x32
k3s[823]: k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.25.5-k3s1/tools/cache/controller.go:232
k3s[823]: k8s.io/client-go/tools/cache.processDeltas({0x57dbdb8, 0xc009008af8}, {0x57f8e20, 0xc009008b10}, 0x0, {0xc01651a360?, 0x1, 0xc016517601?})
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.25.5-k3s1/tools/cache/controller.go:439 +0x2a7
k3s[823]: k8s.io/client-go/tools/cache.newInformer.func1({0x4678c40?, 0xc009034180?})
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.25.5-k3s1/tools/cache/controller.go:489 +0x5b
k3s[823]: k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0164e9d60, 0xc0164ee150)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.25.5-k3s1/tools/cache/delta_fifo.go:554 +0x596
k3s[823]: k8s.io/client-go/tools/cache.(*controller).processLoop(0xc008a47440)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.25.5-k3s1/tools/cache/controller.go:184 +0x36
k3s[823]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40f4df?)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/wait/wait.go:157 +0x3e
k3s[823]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xa830a5?, {0x57a1420, 0xc0164ee1b0}, 0x1, 0x0)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/wait/wait.go:158 +0xb6
k3s[823]: k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc008a474a8?, 0x3b9aca00, 0x0, 0x80?, 0x7fdc9e0a9b20?)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/wait/wait.go:135 +0x89
k3s[823]: k8s.io/apimachinery/pkg/util/wait.Until(...)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/wait/wait.go:92
k3s[823]: k8s.io/client-go/tools/cache.(*controller).Run(0xc008a47440, 0x0)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.25.5-k3s1/tools/cache/controller.go:155 +0x2c6
k3s[823]: github.com/flannel-io/flannel/subnet/kube.(*kubeSubnetManager).Run(0xc015da69a0, {0x57dddb0, 0xc000078030})
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/subnet/kube/kube.go:432 +0x75
k3s[823]: created by github.com/flannel-io/flannel/subnet/kube.NewSubnetManager
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/subnet/kube/kube.go:124 +0x4c5
k3s[823]: E0216 08:38:09.446432     823 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
k3s[823]: goroutine 28700 [running]:
k3s[823]: k8s.io/apimachinery/pkg/util/runtime.logPanic({0x45fb7a0?, 0x7f6c0e0})
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/runtime/runtime.go:75 +0x99
k3s[823]: k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe?})
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/runtime/runtime.go:49 +0x75
k3s[823]: panic({0x45fb7a0, 0x7f6c0e0})
k3s[823]:         /usr/local/go/src/runtime/panic.go:884 +0x212
k3s[823]: k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe?})
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/runtime/runtime.go:56 +0xd7
k3s[823]: panic({0x45fb7a0, 0x7f6c0e0})
k3s[823]:         /usr/local/go/src/runtime/panic.go:884 +0x212
k3s[823]: github.com/flannel-io/flannel/pkg/ip.FromIP6Net(0xc00aa12760?)
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/pkg/ip/ip6net.go:158 +0x18
k3s[823]: github.com/flannel-io/flannel/subnet/kube.(*kubeSubnetManager).nodeToLease(_, {{{0x0, 0x0}, {0x0, 0x0}}, {{0xc00aa12620, 0x9}, {0x0, 0x0}, {0x0, ...}, ...}, ...})
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/subnet/kube/kube.go:499 +0x446
k3s[823]: github.com/flannel-io/flannel/subnet/kube.(*kubeSubnetManager).handleAddLeaseEvent(0xc015da69a0, 0x0, {0x4ca5f40?, 0xc01636e400})
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/subnet/kube/kube.go:220 +0x125
k3s[823]: github.com/flannel-io/flannel/subnet/kube.newKubeSubnetManager.func3({0x4ca5f40?, 0xc01636e400?})
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/subnet/kube/kube.go:184 +0x32
k3s[823]: k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.25.5-k3s1/tools/cache/controller.go:232
k3s[823]: k8s.io/client-go/tools/cache.processDeltas({0x57dbdb8, 0xc009008af8}, {0x57f8e20, 0xc009008b10}, 0x0, {0xc01651a360?, 0x1, 0xc016517601?})
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.25.5-k3s1/tools/cache/controller.go:439 +0x2a7
k3s[823]: k8s.io/client-go/tools/cache.newInformer.func1({0x4678c40?, 0xc009034180?})
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.25.5-k3s1/tools/cache/controller.go:489 +0x5b
k3s[823]: k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0164e9d60, 0xc0164ee150)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.25.5-k3s1/tools/cache/delta_fifo.go:554 +0x596
k3s[823]: k8s.io/client-go/tools/cache.(*controller).processLoop(0xc008a47440)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.25.5-k3s1/tools/cache/controller.go:184 +0x36
k3s[823]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40f4df?)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/wait/wait.go:157 +0x3e
k3s[823]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xa830a5?, {0x57a1420, 0xc0164ee1b0}, 0x1, 0x0)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/wait/wait.go:158 +0xb6
k3s[823]: k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc008a474a8?, 0x3b9aca00, 0x0, 0x80?, 0x7fdc9e0a9b20?)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/wait/wait.go:135 +0x89
k3s[823]: k8s.io/apimachinery/pkg/util/wait.Until(...)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/wait/wait.go:92
k3s[823]: k8s.io/client-go/tools/cache.(*controller).Run(0xc008a47440, 0x0)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.25.5-k3s1/tools/cache/controller.go:155 +0x2c6
k3s[823]: github.com/flannel-io/flannel/subnet/kube.(*kubeSubnetManager).Run(0xc015da69a0, {0x57dddb0, 0xc000078030})
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/subnet/kube/kube.go:432 +0x75
k3s[823]: created by github.com/flannel-io/flannel/subnet/kube.NewSubnetManager
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/subnet/kube/kube.go:124 +0x4c5
k3s[823]: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
k3s[823]:         panic: runtime error: invalid memory address or nil pointer dereference [recovered]
k3s[823]:         panic: runtime error: invalid memory address or nil pointer dereference
k3s[823]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x26b2358]
k3s[823]: goroutine 28700 [running]:
k3s[823]: k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe?})
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/runtime/runtime.go:56 +0xd7
k3s[823]: panic({0x45fb7a0, 0x7f6c0e0})
k3s[823]:         /usr/local/go/src/runtime/panic.go:884 +0x212
k3s[823]: k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe?})
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/runtime/runtime.go:56 +0xd7
k3s[823]: panic({0x45fb7a0, 0x7f6c0e0})
k3s[823]:         /usr/local/go/src/runtime/panic.go:884 +0x212
k3s[823]: github.com/flannel-io/flannel/pkg/ip.FromIP6Net(0xc00aa12760?)
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/pkg/ip/ip6net.go:158 +0x18
k3s[823]: github.com/flannel-io/flannel/subnet/kube.(*kubeSubnetManager).nodeToLease(_, {{{0x0, 0x0}, {0x0, 0x0}}, {{0xc00aa12620, 0x9}, {0x0, 0x0}, {0x0, ...}, ...}, ...})
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/subnet/kube/kube.go:499 +0x446
k3s[823]: github.com/flannel-io/flannel/subnet/kube.(*kubeSubnetManager).handleAddLeaseEvent(0xc015da69a0, 0x0, {0x4ca5f40?, 0xc01636e400})
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/subnet/kube/kube.go:220 +0x125
k3s[823]: github.com/flannel-io/flannel/subnet/kube.newKubeSubnetManager.func3({0x4ca5f40?, 0xc01636e400?})
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/subnet/kube/kube.go:184 +0x32
k3s[823]: k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.25.5-k3s1/tools/cache/controller.go:232
k3s[823]: k8s.io/client-go/tools/cache.processDeltas({0x57dbdb8, 0xc009008af8}, {0x57f8e20, 0xc009008b10}, 0x0, {0xc01651a360?, 0x1, 0xc016517601?})
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.25.5-k3s1/tools/cache/controller.go:439 +0x2a7
k3s[823]: k8s.io/client-go/tools/cache.newInformer.func1({0x4678c40?, 0xc009034180?})
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.25.5-k3s1/tools/cache/controller.go:489 +0x5b
k3s[823]: k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0164e9d60, 0xc0164ee150)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.25.5-k3s1/tools/cache/delta_fifo.go:554 +0x596
k3s[823]: k8s.io/client-go/tools/cache.(*controller).processLoop(0xc008a47440)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.25.5-k3s1/tools/cache/controller.go:184 +0x36
k3s[823]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40f4df?)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/wait/wait.go:157 +0x3e
k3s[823]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xa830a5?, {0x57a1420, 0xc0164ee1b0}, 0x1, 0x0)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/wait/wait.go:158 +0xb6
k3s[823]: k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc008a474a8?, 0x3b9aca00, 0x0, 0x80?, 0x7fdc9e0a9b20?)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/wait/wait.go:135 +0x89
k3s[823]: k8s.io/apimachinery/pkg/util/wait.Until(...)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/wait/wait.go:92
k3s[823]: k8s.io/client-go/tools/cache.(*controller).Run(0xc008a47440, 0x0)
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.25.5-k3s1/tools/cache/controller.go:155 +0x2c6
k3s[823]: github.com/flannel-io/flannel/subnet/kube.(*kubeSubnetManager).Run(0xc015da69a0, {0x57dddb0, 0xc000078030})
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/subnet/kube/kube.go:432 +0x75
k3s[823]: created by github.com/flannel-io/flannel/subnet/kube.NewSubnetManager
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/subnet/kube/kube.go:124 +0x4c5
systemd[1]: k3s.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: k3s.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Lightweight Kubernetes.
systemd[1]: k3s.service: Consumed 12.776s CPU time.
systemd[1]: k3s.service: Scheduled restart job, restart counter is at 1.
systemd[1]: Stopped Lightweight Kubernetes.
```

**Comment by brandond** [comment]
```
k3s[823]: E0216 08:38:09.446432     823 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
k3s[823]: goroutine 28700 [running]:
k3s[823]: k8s.io/apimachinery/pkg/util/runtime.logPanic({0x45fb7a0?, 0x7f6c0e0})
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/runtime/runtime.go:75 +0x99
k3s[823]: k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xfffffffe?})
k3s[823]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.25.5-k3s1/pkg/util/runtime/runtime.go:49 +0x75
k3s[823]: panic({0x45fb7a0, 0x7f6c0e0})
k3s[823]:         /usr/local/go/src/runtime/panic.go:884 +0x212
k3s[823]: github.com/flannel-io/flannel/pkg/ip.FromIP6Net(0xc00aa12760?)
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/pkg/ip/ip6net.go:158 +0x18
k3s[823]: github.com/flannel-io/flannel/subnet/kube.(*kubeSubnetManager).nodeToLease(_, {{{0x0, 0x0}, {0x0, 0x0}}, {{0xc00aa12620, 0x9}, {0x0, 0x0}, {0x0, ...}, ...}, ...})
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/subnet/kube/kube.go:499 +0x446
k3s[823]: github.com/flannel-io/flannel/subnet/kube.(*kubeSubnetManager).handleAddLeaseEvent(0xc015da69a0, 0x0, {0x4ca5f40?, 0xc01636e400})
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/subnet/kube/kube.go:220 +0x125
k3s[823]: github.com/flannel-io/flannel/subnet/kube.newKubeSubnetManager.func3({0x4ca5f40?, 0xc01636e400?})
k3s[823]:         /go/pkg/mod/github.com/flannel-io/flannel@v0.20.2/subnet/kube/kube.go:184 +0x32
```

This appears to be a crash in flannel. I would recommend opening an issue at https://github.com/flannel-io/flannel

cc @rbrtbnfgl @thomasferrandiz @manuelbuil

**Comment by rbrtbnfgl** [comment]
which was the address before the reboot and which is the new address? It seems like K3s  started with an IPv4 PodCIDR and then uses an IPv6 as IP.

**Comment by NunoSav** [comment]
Before: 10.0.0.26/24
After: 10.0.0.28/24

But I think I've found the issue, the new netplan config i created has no gateway and nameservers defined in it. It was looking like:
```yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      dhcp4: false
      addresses:
        - 10.0.0.28/28
```

After i added:
```yaml
      routes:
        - to: default
           via: 10.0.0.1
```
The k3s service was able to start.

Now the coredns doesn't work 🤷

**Comment by rbrtbnfgl** [comment]
Could you attach the logs of the coreDNS pod?

**Comment by NunoSav** [comment]
So i just added:
```yaml
      nameservers:
        addresses:
          - 10.0.0.1
```

To my netplan config, rebooted and now the cluster is running without issues. CoreDNS no longer fails.

I guess that's it, can't go with incomplete netplan config!

Thank you for your time gentleman! Hopefully this will save someone else's time in the future.
