### ISSUE TITLE
k3s docker container selected an incorrect version of iptables on CentOS8

### ISSUE THREAD

**Issue by cho-chem** [k3s-io/k3s#7206]
**Environmental Info:**
K3s Version: 
```
rancher/k3s:v1.24.10-k3s1
```

Node(s) CPU architecture, OS, and Version: 
```
Linux vm2 4.18.0-394.el8.x86_64 #1 SMP Tue May 31 16:19:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
1 server

**Describe the bug:**
k3s docker failed to run. Docker logs:
```
time="2023-04-03T06:48:33Z" level=info msg="Starting the netpol controller version v1.5.2-0.20221026101626-e01045262706, built on 2023-01-26T00:35:57Z, go1.19.5"
I0403 06:48:33.823606      67 network_policy_controller.go:163] Starting network policy controller
F0403 06:48:33.824889      67 network_policy_controller.go:381] failed to run iptables command to create KUBE-ROUTER-INPUT chain due to running [/bin/aux/iptables -t filter -S KUBE-ROUTER-INPUT 1 --wait]: exit status 3: iptables v1.8.8 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
panic: F0403 06:48:33.824889      67 network_policy_controller.go:381] failed to run iptables command to create KUBE-ROUTER-INPUT chain due to running [/bin/aux/iptables -t filter -S KUBE-ROUTER-INPUT 1 --wait]: exit status 3: iptables v1.8.8 (legacy): can't initialize iptables table `filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.


goroutine 27396 [running]:
k8s.io/klog/v2.(*loggingT).output(0x7fb1720, 0x3, 0x0, 0xc006d03340, 0x1, {0x652fab1?, 0x2?}, 0xc00017f000?, 0x0)
	/go/pkg/mod/github.com/k3s-io/klog/v2@v2.60.1-k3s1/klog.go:820 +0x694
k8s.io/klog/v2.(*loggingT).printfDepth(0x7fb1720, 0x11?, 0x0, {0x0, 0x0}, 0x2?, {0x4d5a37d, 0x3b}, {0xc011908940, 0x2, ...})
	/go/pkg/mod/github.com/k3s-io/klog/v2@v2.60.1-k3s1/klog.go:630 +0x1f2
k8s.io/klog/v2.(*loggingT).printf(...)
	/go/pkg/mod/github.com/k3s-io/klog/v2@v2.60.1-k3s1/klog.go:612
k8s.io/klog/v2.Fatalf(...)
	/go/pkg/mod/github.com/k3s-io/klog/v2@v2.60.1-k3s1/klog.go:1496
github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).ensureTopLevelChains(0xc009975500)
	/go/pkg/mod/github.com/k3s-io/kube-router@v1.5.2-0.20221026101626-e01045262706/pkg/controllers/netpol/network_policy_controller.go:381 +0x15a5
github.com/cloudnativelabs/kube-router/pkg/controllers/netpol.(*NetworkPolicyController).Run(0xc009975500, 0xc010d3b380, 0xc000e5e0c0, 0xc00993a6a0)
	/go/pkg/mod/github.com/k3s-io/kube-router@v1.5.2-0.20221026101626-e01045262706/pkg/controllers/netpol/network_policy_controller.go:167 +0x175
created by github.com/k3s-io/k3s/pkg/agent/netpol.Run
	/go/src/github.com/k3s-io/k3s/pkg/agent/netpol/netpol.go:138 +0xb85
```

**Steps To Reproduce:**
- docker run K3s: 
```
docker run \
  --privileged \
  --name k3s-server-1 \
  --hostname k3s-server-1 \
  -p 6443:6443 \
  -d rancher/k3s:v1.24.10-k3s1 \
  server
```

**Expected behavior:**
K3s docker can start successfully.

**Actual behavior:**
k3s docker failed to run.

**Additional context / logs:**
Iptables-nft is available, but iptables-detect.sh has chosen iptables-legacy.
Iptables-detect.sh execution process:
```
$ docker run -it --rm  --privileged --entrypoint /bin/sh rancher/k3s:v1.24.10-k3s1 
# iptables-detect.sh
+ mode=unknown
+ detected_via=unknown
+ containerized=false
+ '[' '!' -z  ]
+ rule_check
+ grep ^-
+ wc -l
+ num_legacy_lines=0
+ '[' 0 -ge 10 ]
+ grep ^-
+ wc -l
+ num_nft_lines=0
+ '[' 0 -gt 0 ]
+ '[' 0 '=' 0 ]
+ mode=unknown
+ '[' unknown '=' unknown ]
+ is_containerized
+ cat /proc/1/cgroup
+ grep cpuset
+ awk -F: '{print $3}'
+ sed 's/\///g'
+ CGT=dockerf59b57aa7ff26c0c8f75393c383e7b3f80780d79ddbeff9bd0a40c4d92a4466e
+ '[' -z dockerf59b57aa7ff26c0c8f75393c383e7b3f80780d79ddbeff9bd0a40c4d92a4466e ]
+ containerized=true
+ '[' true '=' true ]
+ mode=legacy
+ '[' legacy '=' unknown ]
+ basename /bin/aux/iptables-detect.sh
+ '[' iptables-detect.sh '=' iptables-detect.sh ]
+ echo mode is legacy detected via unknown and containerized is true
mode is legacy detected via unknown and containerized is true
+ exit 0
```
run iptables-nft-save:
```
# iptables-nft-save
no output
```

**Comment by brandond** [comment]
K3s still requires iptables kernel modules, even if the host is using nftables. You can run `k3s check-config` to see which modules are required.
