### ISSUE TITLE
kubectl apply throws - runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by guykanyvision** [k3s-io/k3s#738]
**Describe the bug**
When i am creating  GCR registry secret from a file using `kubectl apply -f`,
i am getting to following error:

```
secret/imagepullsecret created
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/yaml.(*YAMLOrJSONDecoder).Decode(0xc000afacf0, 0x32060a0, 0xc000c2e330, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/yaml/decoder.go:241 +0x67b
github.com/rancher/k3s/vendor/k8s.io/cli-runtime/pkg/resource.(*StreamVisitor).Visit(0xc00065fc40, 0xc000abe540, 0x1000, 0xc000acc000)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:550 +0xe0
github.com/rancher/k3s/vendor/k8s.io/cli-runtime/pkg/resource.(*FileVisitor).Visit(0xc000abe440, 0xc000abe540, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:520 +0x204
github.com/rancher/k3s/vendor/k8s.io/cli-runtime/pkg/resource.EagerVisitorList.Visit(0xc000435a20, 0x1, 0x1, 0xc00065fd40, 0xc00065fd01, 0xc00065fd40)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:206 +0xc5
github.com/rancher/k3s/vendor/k8s.io/cli-runtime/pkg/resource.FlattenListVisitor.Visit(0x3b2cf60, 0xc000abe460, 0x3b73de0, 0x5fbfdd8, 0xc000b525d0, 0xc00065fd00, 0xffffffffffffffff, 0xc000afaf08)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:385 +0x86
github.com/rancher/k3s/vendor/k8s.io/cli-runtime/pkg/resource.FlattenListVisitor.Visit(0x3b2cfa0, 0xc000b52600, 0x3b73de0, 0x5fbfdd8, 0xc000b525d0, 0xc000abe500, 0xc000b52690, 0xc000afafb8)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:385 +0x86
github.com/rancher/k3s/vendor/k8s.io/cli-runtime/pkg/resource.ContinueOnErrorVisitor.Visit(0x3b2cfa0, 0xc000b52660, 0xc00065fc80, 0x203001, 0xc00065fc80)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:347 +0xc3
github.com/rancher/k3s/vendor/k8s.io/cli-runtime/pkg/resource.DecoratedVisitor.Visit(0x3b2cf20, 0xc000435a40, 0xc000abe4a0, 0x3, 0x4, 0xc00063c9b0, 0xc00063c9b0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/cli-runtime/pkg/resource/visitor.go:319 +0x86
github.com/rancher/k3s/vendor/k8s.io/cli-runtime/pkg/resource.(*Result).Visit(0xc0007da680, 0xc00063c9b0, 0x0, 0x0)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/cli-runtime/pkg/resource/result.go:99 +0x62
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/apply.(*ApplyOptions).Run(0xc0001bfcc0, 0x0, 0x34f0b38)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/apply/apply.go:344 +0x3b3
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/apply.NewCmdApply.func1(0xc000ac0500, 0xc000ab2fc0, 0x0, 0x2)
	/go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubectl/cmd/apply/apply.go:161 +0x100
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).execute(0xc000ac0500, 0xc000ab2fa0, 0x2, 0x2, 0xc000ac0500, 0xc000ab2fa0)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:760 +0x2ae
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000502780, 0x34ed150, 0xc00004e0c0, 0x4)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:846 +0x2ec
github.com/rancher/k3s/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/rancher/k3s/vendor/github.com/spf13/cobra/command.go:794
github.com/rancher/k3s/pkg/kubectl.main()
	/go/src/github.com/rancher/k3s/pkg/kubectl/main.go:47 +0x1eb
github.com/rancher/k3s/pkg/kubectl.Main()
	/go/src/github.com/rancher/k3s/pkg/kubectl/main.go:30 +0x47
github.com/rancher/k3s/vendor/github.com/docker/docker/pkg/reexec.Init(...)
	/go/src/github.com/rancher/k3s/vendor/github.com/docker/docker/pkg/reexec/reexec.go:26
main.main()
	/go/src/github.com/rancher/k3s/cmd/server/main.go:29 +0x600

```

Looks like it created the manifest, but I'm not sure why I'm getting this error message and what it means?

***Steps to reproduce the behavior:***

Create dockerconfigjson secret using `kubectl apply -f`
```
{
    "apiVersion": "v1",
    "data": {
        ".dockerconfigjson": YOUR_JSON_KEY_STRING
    },
    "kind": "Secret",
    "metadata": {
        "name": "imagepullsecret",
        "namespace": "default"
    },
    "type": "kubernetes.io/dockerconfigjson"
}

```

**Additional context**
I have installed Rancher and added registry through the UI
Then, in order to automate the installation, i Took the secret it created and copied it to a file
then deleted the registry thourgh the UI and trying recreate it with `kubectl apply -f`
but I'm not sure if this bug is related to Rancher

**Comment by tsadoklf** [comment]
@guykanyvision, it seems to me that the JSON manifest is invalid (a comma after "default"). 

```JSON
{
  "apiVersion": "v1",
  "data": {
    ".dockerconfigjson": "YOUR_JSON_KEY_STRING"
  },
  "kind": "Secret",
  "metadata": {
    "name": "imagepullsecret",
    "namespace": "default"
  },
  "type": "kubernetes.io/dockerconfigjson"
}
```
The equivalent YAML is - 
```YAML
---
apiVersion: v1
data:
  ".dockerconfigjson": YOUR_JSON_KEY_STRING
kind: Secret
metadata:
  name: imagepullsecret
  namespace: default
type: kubernetes.io/dockerconfigjson
```
See also [Create a Secret based on existing Docker credentials](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials).

**Comment by guykanyvision** [comment]
@tsadoklf thanks for noticed, copied it wrong.
But it's not the issue, because the resource is created.

With the comma, kubectl throws an error and not creating the manifest.

**Comment by brandond** [comment]
Closing due to age.
