### ISSUE TITLE
k3s server failed to run on OrangePi one plus

### ISSUE THREAD

**Issue by Hokutosei** [k3s-io/k3s#81]
Greetings,

first, thanks for this project, been looking for this to run on bunch of orangepi's. I tried installing it from the instructions on main page of k3s. upon running `k3s server`, unfortunately, it was not successful.. here is the logs.

```
orangepi@OrangePi:~$ sudo k3s server
INFO[2019-02-28T02:49:46.730189319Z] Starting k3s v0.1.0 (91251aa)
INFO[2019-02-28T02:49:46.732501187Z] Running kube-apiserver --watch-cache=false --cert-dir /var/lib/rancher/k3s/server/tls/temporary-certs --allow-privileged=true --authorization-mode Node,RBAC --service-account-signing-key-file /var/lib/rancher/k3s/server/tls/service.key --service-cluster-ip-range 10.43.0.0/16 --advertise-port 6445 --advertise-address 127.0.0.1 --insecure-port 0 --secure-port 6444 --bind-address 127.0.0.1 --tls-cert-file /var/lib/rancher/k3s/server/tls/localhost.crt --tls-private-key-file /var/lib/rancher/k3s/server/tls/localhost.key --service-account-key-file /var/lib/rancher/k3s/server/tls/service.key --service-account-issuer k3s --api-audiences unknown --basic-auth-file /var/lib/rancher/k3s/server/cred/passwd --kubelet-client-certificate /var/lib/rancher/k3s/server/tls/token-node.crt --kubelet-client-key /var/lib/rancher/k3s/server/tls/token-node.key
INFO[2019-02-28T02:49:46.994494527Z] Running kube-scheduler --kubeconfig /var/lib/rancher/k3s/server/cred/kubeconfig-system.yaml --port 0 --secure-port 0 --leader-elect=false
INFO[2019-02-28T02:49:46.996765103Z] Running kube-controller-manager --kubeconfig /var/lib/rancher/k3s/server/cred/kubeconfig-system.yaml --service-account-private-key-file /var/lib/rancher/k3s/server/tls/service.key --allocate-node-cidrs --cluster-cidr 10.42.0.0/16 --root-ca-file /var/lib/rancher/k3s/server/tls/token-ca.crt --port 0 --secure-port 0 --leader-elect=false
INFO[2019-02-28T02:49:47.371194052Z] Listening on :6443
INFO[2019-02-28T02:49:47.487677061Z] Writing manifest: /var/lib/rancher/k3s/server/manifests/coredns.yaml
INFO[2019-02-28T02:49:47.494467706Z] Writing manifest: /var/lib/rancher/k3s/server/manifests/traefik.yaml
INFO[2019-02-28T02:49:48.186973575Z] Node token is available at /var/lib/rancher/k3s/server/node-token
INFO[2019-02-28T02:49:48.187132533Z] To join node to cluster: k3s agent -s https://172.16.80.96:6443 -t ${NODE_TOKEN}
INFO[2019-02-28T02:49:48.502202047Z] Wrote kubeconfig /etc/rancher/k3s/k3s.yaml
INFO[2019-02-28T02:49:48.502312589Z] Run: k3s kubectl
INFO[2019-02-28T02:49:48.502379547Z] k3s is up and running
WARN[2019-02-28T02:49:48.502616254Z] Failed to find cpuset cgroup, you may need to add "cgroup_enable=cpuset" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)
INFO[2019-02-28T02:49:49.642567487Z] Logging containerd to /var/lib/rancher/k3s/agent/containerd/containerd.log
INFO[2019-02-28T02:49:49.643006111Z] Running containerd -c /var/lib/rancher/k3s/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/k3s/agent/containerd
INFO[2019-02-28T02:49:49.643616359Z] Waiting for containerd startup: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /run/k3s/containerd/containerd.sock: connect: connection refused"
WARN[2019-02-28T02:49:50.658833495Z] failed to write value 1 at /proc/sys/net/bridge/bridge-nf-call-iptables: open /proc/sys/net/bridge/bridge-nf-call-iptables: no such file or directory
INFO[2019-02-28T02:49:50.662059235Z] Connecting to wss://localhost:6443/v1-k3s/connect
INFO[2019-02-28T02:49:50.662518192Z] Connecting to proxy                           url="wss://localhost:6443/v1-k3s/connect"
INFO[2019-02-28T02:49:50.682892545Z] Handling backend connection request [OrangePi]
WARN[2019-02-28T02:49:50.686520659Z] Disabling CPU quotas due to missing cpu.cfs_period_us
INFO[2019-02-28T02:49:50.687094574Z] Running kubelet --healthz-bind-address 127.0.0.1 --read-only-port 0 --allow-privileged=true --cluster-domain cluster.local --kubeconfig /var/lib/rancher/k3s/agent/kubeconfig.yaml --eviction-hard imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --cgroup-driver cgroupfs --root-dir /var/lib/rancher/k3s/agent/kubelet --cert-dir /var/lib/rancher/k3s/agent/kubelet/pki --seccomp-profile-root /var/lib/rancher/k3s/agent/kubelet/seccomp --cni-conf-dir /var/lib/rancher/k3s/agent/etc/cni/net.d --cni-bin-dir /var/lib/rancher/k3s/data/d13d901c2b0aca5ab82da684ade2d343ea11285cf335afd743a7fc0a91583d56/bin --cluster-dns 10.43.0.10 --container-runtime remote --container-runtime-endpoint unix:///run/k3s/containerd/containerd.sock --address 127.0.0.1 --anonymous-auth=false --client-ca-file /var/lib/rancher/k3s/agent/client-ca.pem --hostname-override OrangePi --cpu-cfs-quota=false
Flag --allow-privileged has been deprecated, will be removed in a future version
INFO[2019-02-28T02:49:51.938991699Z] waiting for node OrangePi: nodes "OrangePi" not found
F0228 02:49:52.232279    3457 kubelet.go:1305] Failed to start ContainerManager [open /proc/sys/kernel/keys/root_maxkeys: no such file or directory, open /proc/sys/kernel/keys/root_maxbytes: no such file or directory]
goroutine 5803 [running]:
github.com/rancher/k3s/vendor/k8s.io/klog.stacks(0x4000587000, 0x400082e1e0, 0xda, 0x1df)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:828 +0xb8
github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).output(0x4fddce0, 0x4000000003, 0x4002bfabb0, 0x4d4ea3d, 0xa, 0x519, 0x0)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:779 +0x2ec
github.com/rancher/k3s/vendor/k8s.io/klog.(*loggingT).printf(0x4fddce0, 0x3, 0x2a3faea, 0x23, 0x40024e3da0, 0x1, 0x1)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:678 +0x104
github.com/rancher/k3s/vendor/k8s.io/klog.Fatalf(0x2a3faea, 0x23, 0x40024e3da0, 0x1, 0x1)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/klog/klog.go:1207 +0x54
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).initializeRuntimeDependentModules(0x400186db00)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1305 +0x224
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).initializeRuntimeDependentModules-fm()
        /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2113 +0x20
sync.(*Once).Do(0x400186e210, 0x400200fe70)
        /usr/local/go/src/sync/once.go:44 +0xb8
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).updateRuntimeUp(0x400186db00)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2113 +0x2b8
github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).updateRuntimeUp-fm()
        /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1349 +0x20
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0x40028a1110)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x48
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x40028a1110, 0x12a05f200, 0x0, 0x2425001, 0x40004cc180)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0x7c
github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0x40028a1110, 0x12a05f200, 0x40004cc180)
        /go/src/github.com/rancher/k3s/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x40
created by github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run
        /go/src/github.com/rancher/k3s/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1349 +0xfc
```

here are some info about the system.
```
orangepi@OrangePi:~$ uname -a
Linux OrangePi 3.10.65 #35 SMP PREEMPT Tue Jan 23 18:13:02 CST 2018 aarch64 aarch64 aarch64 GNU/Linux
```

any idea on why I am hitting this? also, it may be such a stupid question, do I need to get docker installed/running?

thank you!

**Comment by zoobab** [comment]
Try to add a line in /etc/hosts where OrangePi is 127.0.0.1.

**Comment by ibuildthecloud** [comment]
@Hokutosei it looks like you are missing kernel keyring support, specifically the ability to [change the quota](http://lkml.iu.edu/hypermail/linux/kernel/0803.1/2113.html).

**Comment by Hokutosei** [comment]
@ibuildthecloud thank you for the comment.. do you know how to solve this? or just a clue.. thank you!

**Comment by chopmann** [comment]
@Hokutosei you might want to test against: https://github.com/moby/moby/blob/master/contrib/check-config.sh to see what you are missing on your kernel.
I'm working on a yocto layer for k3s: https://github.com/HamburgChimps/minimal-k3s (as of now it just sets the right kernel flags[0])

I think you might be able to bake your own image:
https://github.com/linux-sunxi

If anyone wants to help that'd be awesome :smile: 

[0] https://github.com/balena-os/meta-balena/blob/master/meta-resin-common/classes/kernel-resin.bbclass
 https://docs.windriver.com/bundle/Wind_River_Linux_Kernel_and_BSP_Developers_Guide_8.0_1/page/1672019.html

**Comment by jypma** [comment]
@Hokutosei What OS are you running on the Orange Pi? I'm running rapbian on an orange pi one, and it comes with kernel 4.19.20, you may want to give it a try (I haven't tried `k3s` myself yet).

**Comment by brandond** [comment]
Closing due to age.
