### ISSUE TITLE
Observed crash in filtercn address controller

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#8267]
Observed in RKE2 v1.28.1-rc1+rke2r1, but lives here in K3s:
```
INFO[0071] Starting /v1, Kind=Node controller
fatal error: bad map state

goroutine 1766 [running]:
runtime.throw({0x3724795?, 0xc0050a2439?})
	/usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0xc002277998 sp=0xc002277968 pc=0x43b63d
runtime.evacuate_faststr(0x31968c0, 0xc001df39e0, 0xc001df8500?)
	/usr/local/go/src/runtime/map_faststr.go:435 +0x3da fp=0xc002277a40 sp=0xc002277998 pc=0x416bba
runtime.growWork_faststr(0x3054c00?, 0xc001df39e0, 0x304f600?)
	/usr/local/go/src/runtime/map_faststr.go:394 +0x4c fp=0xc002277a70 sp=0xc002277a40 pc=0x41678c
runtime.mapassign_faststr(0x31968c0, 0xc001df39e0, {0xc0029784b0, 0x41})
	/usr/local/go/src/runtime/map_faststr.go:227 +0x125 fp=0xc002277ae0 sp=0xc002277a70 pc=0x4160c5
github.com/k3s-io/k3s/pkg/cluster.(*addressesHandler).sync(0xc001df4a08, {0x0?, 0xc002277b88?}, 0xc00247cb00)
	/go/pkg/mod/github.com/k3s-io/k3s@v1.28.1-rc1.0.20230829153345-cba9f0d142bb/pkg/cluster/address_controller.go:56 +0x12b fp=0xc002277b48 sp=0xc002277ae0 pc=0x29bdd8b
github.com/k3s-io/k3s/pkg/cluster.(*addressesHandler).sync-fm({0xc002822650?, 0xc00247cb00?}, 0xc002277bc8?)
	<autogenerated>:1 +0x37 fp=0xc002277b78 sp=0xc002277b48 pc=0x29c8477
github.com/rancher/wrangler/pkg/generic.FromObjectHandlerToHandler[...].func1({0x3c44d28?, 0xc00247cb00?})
	/go/pkg/mod/github.com/rancher/wrangler@v1.1.1-0.20230818201331-3604a6be798d/pkg/generic/controller.go:169 +0x4e fp=0xc002277ba8 sp=0xc002277b78 pc=0x26042ee
github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x36c5a00?, {0xc002822650?, 0x376a474?}, {0x3c44d28?, 0xc00247cb00?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230629200414-8a54b32e6792/pkg/controller/sharedcontroller.go:29 +0x38 fp=0xc002277bd8 sp=0xc002277ba8 pc=0x25dfbf8
github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc001ff6ff0, {0xc002822650, 0xd}, {0x3c44d28, 0xc00247cb00})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230629200414-8a54b32e6792/pkg/controller/sharedhandler.go:75 +0x218 fp=0xc002277d00 sp=0xc002277bd8 pc=0x25e29b8
github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc0050c9080, {0xc002822650, 0xd})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230629200414-8a54b32e6792/pkg/controller/controller.go:232 +0x93 fp=0xc002277d50 sp=0xc002277d00 pc=0x25def73
github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc0050c9080, {0x3054c00?, 0xc0050c2120?})
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230629200414-8a54b32e6792/pkg/controller/controller.go:213 +0x105 fp=0xc002277e28 sp=0xc002277d50 pc=0x25dec25
github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc0050c9080)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230629200414-8a54b32e6792/pkg/controller/controller.go:190 +0x46 fp=0xc002277e70 sp=0xc002277e28 pc=0x25dea26
github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230629200414-8a54b32e6792/pkg/controller/controller.go:179
github.com/rancher/lasso/pkg/controller.(*controller).runWorker-fm()
	<autogenerated>:1 +0x32 fp=0xc002277e90 sp=0xc002277e70 pc=0x25e4ef2
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	/go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.1-k3s1/pkg/util/wait/backoff.go:226 +0x3e fp=0xc002277eb0 sp=0xc002277e90 pc=0xc2a37e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x3177694871516874?, {0x3c37a60, 0xc00297b620}, 0x1, 0xc000c65e00)
	/go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.1-k3s1/pkg/util/wait/backoff.go:227 +0xb6 fp=0xc002277f30 sp=0xc002277eb0 pc=0xc2a236
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x7369653271535936?, 0x3b9aca00, 0x0, 0x76?, 0x4833665752464f6d?)
	/go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.1-k3s1/pkg/util/wait/backoff.go:204 +0x89 fp=0xc002277f80 sp=0xc002277f30 pc=0xc2a129
k8s.io/apimachinery/pkg/util/wait.Until(0x7ee0aa?, 0x5a56444532436547?, 0xc000989550?)
	/go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.1-k3s1/pkg/util/wait/backoff.go:161 +0x25 fp=0xc002277fb8 sp=0xc002277f80 pc=0xc29f85
github.com/rancher/lasso/pkg/controller.(*controller).run.func3()
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230629200414-8a54b32e6792/pkg/controller/controller.go:147 +0x2f fp=0xc002277fe0 sp=0xc002277fb8 pc=0x25de54f
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc002277fe8 sp=0xc002277fe0 pc=0x4731c1
created by github.com/rancher/lasso/pkg/controller.(*controller).run
	/go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230629200414-8a54b32e6792/pkg/controller/controller.go:147 +0x2d5
```

Specifically, this happens when multiple nodes are sync'd same time, and one goroutine is resizing the address map while the other attempts to add an entry.

https://github.com/k3s-io/k3s/blob/cba9f0d142bb2f0062e227f1448c73464bef84c2/pkg/cluster/address_controller.go#L55-L57

Not sure how to reproduce this on demand, but it happened once out of a few test runs when setting up a basic 3-server all-roles cluster.

**Comment by mdrahman-suse** [comment]
## Tested on v1.28.1-rc2+rke2r1

Unable to replicate the original issue on either k3s or rke2. Tried joining 2-5 server nodes at the same time but did not came across the issue. Also tested with upgrades. Can open new issue if observed again

- Version
```
rke2 version v1.28.1-rc2+rke2r1 (4cc154f0e632a399094bb9843175f66670242ad6)
go version go1.20.7 X:boringcrypto
```

```
kgn
NAME      STATUS   ROLES                       AGE   VERSION
server1   Ready    control-plane,etcd,master   25m   v1.28.1+rke2r1
server2   Ready    control-plane,etcd,master   19m   v1.28.1+rke2r1
server3   Ready    control-plane,etcd,master   19m   v1.28.1+rke2r1
server4   Ready    control-plane,etcd,master   19m   v1.28.1+rke2r1
```

```
$ sudo journalctl -eu rke2-server | grep -i -A 10 "Kind=Node Controller"
Sep 05 21:10:37 ip-172-31-43-101 rke2[1593]: time="2023-09-05T21:10:37Z" level=info msg="Starting /v1, Kind=Node controller"
Sep 05 21:10:37 ip-172-31-43-101 rke2[1593]: time="2023-09-05T21:10:37Z" level=info msg="Cluster dns configmap has been set successfully"
Sep 05 21:10:37 ip-172-31-43-101 rke2[1593]: time="2023-09-05T21:10:37Z" level=info msg="Labels and annotations have been set successfully on node: server1"
Sep 05 21:10:37 ip-172-31-43-101 rke2[1593]: time="2023-09-05T21:10:37Z" level=info msg="Starting managed etcd apiserver addresses controller"
Sep 05 21:10:37 ip-172-31-43-101 rke2[1593]: time="2023-09-05T21:10:37Z" level=info msg="Starting managed etcd member removal controller"
Sep 05 21:10:37 ip-172-31-43-101 rke2[1593]: time="2023-09-05T21:10:37Z" level=info msg="Creating helm-controller event broadcaster"
Sep 05 21:10:37 ip-172-31-43-101 rke2[1593]: time="2023-09-05T21:10:37Z" level=info msg="Creating reencrypt-controller event broadcaster"
Sep 05 21:10:37 ip-172-31-43-101 rke2[1593]: time="2023-09-05T21:10:37Z" level=info msg="Starting helm.cattle.io/v1, Kind=HelmChart controller"
Sep 05 21:10:37 ip-172-31-43-101 rke2[1593]: time="2023-09-05T21:10:37Z" level=info msg="Starting helm.cattle.io/v1, Kind=HelmChartConfig controller"
Sep 05 21:10:37 ip-172-31-43-101 rke2[1593]: time="2023-09-05T21:10:37Z" level=info msg="Starting rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding controller"
Sep 05 21:10:37 ip-172-31-43-101 rke2[1593]: time="2023-09-05T21:10:37Z" level=info msg="Starting /v1, Kind=Secret controller"
```
