### ISSUE TITLE
Cannot start control-plane-only server

### ISSUE THREAD

**Issue by brandond** [k3s-io/k3s#8637]
Current git builds of K3s crash when starting on control-plane only nodes. It appears we don't have a test for this anywhere, so it wasn't noticed.

`k3s server --server https://172.17.0.3:6443 --cluster-init --disable-etcd --token token`

```
INFO[0000] Running load balancer k3s-etcd-server-load-balancer 127.0.0.1:2379 -> [172.17.0.3:2379] [default: 172.17.0.3:2379]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3fc6e9a]

goroutine 1 [running]:
github.com/k3s-io/k3s/pkg/etcd.(*ETCD).RemovePeer(0xc00014dc20, {0x628e098?, 0xc0009b6f50?}, {0xc0005a6f30, 0x15}, {0xc0007071b4, 0xa}, 0x1)
	/go/src/github.com/k3s-io/k3s/pkg/etcd/etcd.go:983 +0xba
github.com/k3s-io/k3s/pkg/etcd.(*ETCD).RemoveSelf(0xc00014dc20, {0x628e098?, 0xc0009b6f50?})
	/go/src/github.com/k3s-io/k3s/pkg/etcd/etcd.go:1377 +0x59
github.com/k3s-io/k3s/pkg/cluster.(*Cluster).Start(0xc0009e3590, {0x628e098?, 0xc0009b6f50})
	/go/src/github.com/k3s-io/k3s/pkg/cluster/cluster.go:64 +0x346
github.com/k3s-io/k3s/pkg/daemons/control.prepare({0x628e098, 0xc0009b6f50}, 0xc000a4a008)
	/go/src/github.com/k3s-io/k3s/pkg/daemons/control/server.go:270 +0x305
github.com/k3s-io/k3s/pkg/daemons/control.Server({0x628e098?, 0xc0009b6f50}, 0xc000a4a008)
	/go/src/github.com/k3s-io/k3s/pkg/daemons/control/server.go:33 +0xff
github.com/k3s-io/k3s/pkg/server.StartServer({0x628e098?, 0xc0009b6f50}, 0xc000a4a000, 0x1?)
	/go/src/github.com/k3s-io/k3s/pkg/server/server.go:56 +0x93
github.com/k3s-io/k3s/pkg/cli/server.run(0xc000bb1ce0, 0x91bf3c0, {0xc000a1ca00, 0x0, 0x0?}, {0xc000a1ca00, 0x0, 0x8fc86e0?})
	/go/src/github.com/k3s-io/k3s/pkg/cli/server/server.go:478 +0x350a
github.com/k3s-io/k3s/pkg/cli/server.Run(0xc000bb1ce0?)
	/go/src/github.com/k3s-io/k3s/pkg/cli/server/server.go:41 +0x35
github.com/urfave/cli.HandleAction({0x4cb1a20?, 0x5b7fba8?}, 0x6?)
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:524 +0x50
github.com/urfave/cli.Command.Run({{0x5716d72, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x575d4f8, 0x15}, {0xc0006bbd10, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/command.go:175 +0x67b
github.com/urfave/cli.(*App).Run(0xc000430fc0, {0xc0000743c0, 0xa, 0xa})
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:277 +0xb87
main.main()
	/go/src/github.com/k3s-io/k3s/cmd/server/main.go:81 +0xc1e
```

We should add a test, and fix the crash.

**Comment by VestigeJ** [comment]
##Environment Details
Reproduced using VERSION=v1.28.2+k3s1


*Infrastructure*
- [X] Cloud

*Node(s) CPU architecture, OS, and version:*

Linux 5.14.21-150500.53-default x86_64 GNU/Linux
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP5"

<details><summmary><h4>Reproduction</h4></summary>



```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/90-kubelet.conf
$ sudo cp 90-kubelet.conf /etc/sysctl.d/
$ sudo systemctl restart systemd-sysctl
$ sudo INSTALL_K3S_VERSION=v1.28.2+k3s1 INSTALL_K3S_SKIP_ENABLE=true ./install-k3s.sh
$ k3s -v
$ k3s server --server https://52.14.83.2:6443 --cluster-init --disable-etcd --token YOUR_TOKEN_HERE
$ sudo /usr/local/bin/k3s server --server https://52.14.83.2:6443 --cluster-init --disable-etcd --token YOUR_TOKEN_HERE   //observe failure
$ get_report //generate this template
```

**Results:**

$ k3s -v
```
k3s version v1.28.2+k3s1 (6330a5b4)
go version go1.20.8
```
$ sudo /usr/local/bin/k3s server --server https://52.14.83.2:6443 --cluster-init --disable-etcd --token YOUR_TOKEN_HERE

```
{"level":"info","ts":"2023-10-16T23:17:34.513749Z","caller":"etcdserver/server.go:1465","msg":"skipped leadership transfer for single voting member cluster","local-member-id":"a40a1b00a9c8bb9","current-leader-member-id":"a40a1b00a9c8bb9"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x25a426d]

goroutine 1 [running]:
github.com/k3s-io/k3s/pkg/clientaccess.(*Info).Get(0x0, {0x5963048, 0x8})
	/go/src/github.com/k3s-io/k3s/pkg/clientaccess/token.go:265 +0x2d
github.com/k3s-io/k3s/pkg/etcd.ClientURLs({0xc0005f5a10?, 0x0?}, 0xc000c53270?, {0x0, 0x0})
	/go/src/github.com/k3s-io/k3s/pkg/etcd/etcd.go:1142 +0x72
github.com/k3s-io/k3s/pkg/cluster.(*Cluster).Start(0xc0005f5a10, {0x6537d08?, 0xc000c53270})
	/go/src/github.com/k3s-io/k3s/pkg/cluster/cluster.go:45 +0x117
github.com/k3s-io/k3s/pkg/daemons/control.prepare({0x6537d08, 0xc000c53270}, 0xc0003ed908)
	/go/src/github.com/k3s-io/k3s/pkg/daemons/control/server.go:288 +0x27f
github.com/k3s-io/k3s/pkg/daemons/control.Server({0x6537d08?, 0xc000c53270}, 0xc0003ed908)
	/go/src/github.com/k3s-io/k3s/pkg/daemons/control/server.go:36 +0x10a
github.com/k3s-io/k3s/pkg/server.StartServer({0x6537d08?, 0xc000c53270}, 0xc0003ed900, 0x1?)
	/go/src/github.com/k3s-io/k3s/pkg/server/server.go:56 +0x93
github.com/k3s-io/k3s/pkg/cli/server.run(0xc0009e4b00, 0x95ac4c0, {0xc0009449f8, 0x0, 0x0?}, {0xc0009449f8, 0x0, 0x93a9f20?})
	/go/src/github.com/k3s-io/k3s/pkg/cli/server/server.go:496 +0x35b1
github.com/k3s-io/k3s/pkg/cli/server.Run(0xc0009e4b00?)
	/go/src/github.com/k3s-io/k3s/pkg/cli/server/server.go:41 +0x35
github.com/urfave/cli.HandleAction({0x4ea3f40?, 0x5deb5b8?}, 0x6?)
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:524 +0x50
github.com/urfave/cli.Command.Run({{0x595d364, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x59a5424, 0x15}, {0xc000690750, ...}, ...}, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/command.go:175 +0x67b
github.com/urfave/cli.(*App).Run(0xc00098e380, {0xc000120080, 0x8, 0x8})
	/go/pkg/mod/github.com/urfave/cli@v1.22.14/app.go:277 +0xb87
main.main()
	/go/src/github.com/k3s-io/k3s/cmd/server/main.go:82 +0xc1e
```


</details>

Not yet validated

**Comment by VestigeJ** [comment]
##Environment Details
COMMIT=b8dc95539bfc443f6a79c3140e18ef8d6e9aae1e

tested via config.yaml flags instead of CLI args - there isn't a major difference functionally but it's good to do from time to time. 

*Infrastructure*
- [X] Cloud


*Node(s) CPU architecture, OS, and version:*
```
Linux 5.14.21-150500.53-default x86_64 GNU/Linux
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP5"
```

*Cluster Configuration:*
```
NAME              STATUS   ROLES                       AGE    VERSION
ip-1-3-6-9        Ready    control-plane,master        30s   v1.28.2+k3s-b8dc9553
ip-1-2-3-5        Ready    control-plane,etcd,master   14m   v1.28.2+k3s-b8dc9553
```

*Config.yaml:*
```
server: https://1.2.3.5:6443
debug: true
token: YOUR_TOKEN::server:YOUR_TOKEN
cluster-init: true
disable-etcd: true
node-taint:
  - node-role.kubernetes.io/contral-plane:NoSchedule
```

<details><summmary><h4> YOUR_REPRODUCED_RESULTS_HERE </h4></summary>



```
$ curl https://get.k3s.io --output install-"k3s".sh
$ sudo chmod +x install-"k3s".sh
$ sudo groupadd --system etcd && sudo useradd -s /sbin/nologin --system -g etcd etcd
$ sudo modprobe ip_vs_rr
$ sudo modprobe ip_vs_wrr
$ sudo modprobe ip_vs_sh
$ sudo printf "on_oovm.panic_on_oom=0 \nvm.overcommit_memory=1 \nkernel.panic=10 \nkernel.panic_ps=1 \nkernel.panic_on_oops=1 \n" > ~/60-rke2-cis.conf or ~/90-kubelet.conf
$ sudo cp 60-rke2-cis.conf /etc/sysctl.d/ or 90-kubelet.conf
$ sudo systemctl restart systemd-sysctl
$ sudo INSTALL_K3S_COMMIT=b8dc95539bfc443f6a79c3140e18ef8d6e9aae1e INSTALL_K3S_SKIP_ENABLE=true ./install-k3s.sh
$ sudo systemctl enable k3s --now
$ set_kubefig // export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
$ kgn //kubectl get nodes
$ get_report //generate this template
```

**Results:**
Cluster looks good ✅ 

$ kgp -A 
```
NAMESPACE     NAME                                          READY   STATUS      RESTARTS   AGE
kube-system   pod/coredns-6799fbcd5-z97t9                   1/1     Running     0          14m
kube-system   pod/helm-install-traefik-crd-5thtf            0/1     Completed   0          14m
kube-system   pod/helm-install-traefik-mr5c6                0/1     Completed   1          14m
kube-system   pod/local-path-provisioner-84db5d44d9-vw54w   1/1     Running     0          14m
kube-system   pod/metrics-server-67c658944b-vjfzg           1/1     Running     0          14m
kube-system   pod/svclb-traefik-eb480169-r8mg2              2/2     Running     0          14m
kube-system   pod/traefik-55f65f58b-w2nmq                   1/1     Running     0          14m
```

</details>
