### ISSUE TITLE
K3s crashing with "assignment to entry in nil map" after etcd restore

### ISSUE THREAD

**Issue by Oats87** [k3s-io/k3s#9047]
**Environmental Info:**
```
k3s version v1.27.7+k3s2 (575bce76)
go version go1.20.10
```
Node(s) CPU architecture, OS, and Version: 
```
Linux ck-c7-0 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Cluster Configuration:
1 Server

**Describe the bug:**
While performing an etcd restore, K3s failed after the `k3s.service` unit was restarted with bad logs.

**Steps To Reproduce:**
see: https://github.com/k3s-io/k3s/issues/9047#issuecomment-1853087272

**Expected behavior:**
K3s restarts

**Actual behavior:**
K3s repeatedly crashes

**Additional context / logs:**
```
Dec 12 14:04:06 ck-c7-0 k3s[12709]: I1212 14:04:06.531309   12709 reconciler.go:41] "Reconciler: start to sync state"
Dec 12 14:04:06 ck-c7-0 k3s[12709]: I1212 14:04:06.559730   12709 iptables.go:283] bootstrap done
Dec 12 14:04:06 ck-c7-0 k3s[12709]: I1212 14:04:06.567957   12709 iptables.go:283] bootstrap done
Dec 12 14:04:06 ck-c7-0 k3s[12709]: I1212 14:04:06.591576   12709 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="36c5948f6227094bcc0f64a146484777c422eb11251b110bdbb28c1a791365c2"
Dec 12 14:04:06 ck-c7-0 k3s[12709]: I1212 14:04:06.605120   12709 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="895c07933364be4dad28c37a64f615c8f393f647188704bef7169aa8c62e7b6b"
Dec 12 14:04:06 ck-c7-0 k3s[12709]: I1212 14:04:06.626911   12709 pod_container_deletor.go:80] "Container not found in pod's containers" containerID="125cabcbf0f572a3f304f82016808f00e2e2a42b707d7aa1767fd86bd80e2f14"
Dec 12 14:04:06 ck-c7-0 k3s[12709]: E1212 14:04:06.640333   12709 runtime.go:79] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
Dec 12 14:04:06 ck-c7-0 k3s[12709]: goroutine 8337 [running]:
Dec 12 14:04:06 ck-c7-0 k3s[12709]: k8s.io/apimachinery/pkg/util/runtime.logPanic({0x500d640?, 0x63b9f20})
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.27.7-k3s1/pkg/util/runtime/runtime.go:75 +0x99
Dec 12 14:04:06 ck-c7-0 k3s[12709]: k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00651f2e0?})
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.27.7-k3s1/pkg/util/runtime/runtime.go:49 +0x75
Dec 12 14:04:06 ck-c7-0 k3s[12709]: panic({0x500d640, 0x63b9f20})
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /usr/local/go/src/runtime/panic.go:884 +0x213
Dec 12 14:04:06 ck-c7-0 k3s[12709]: github.com/k3s-io/k3s/pkg/etcd.(*etcdSnapshotHandler).reconcile(0xc002305600)
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/src/github.com/k3s-io/k3s/pkg/etcd/snapshot_controller.go:261 +0xad5
Dec 12 14:04:06 ck-c7-0 k3s[12709]: github.com/k3s-io/k3s/pkg/etcd.(*etcdSnapshotHandler).sync(0xc002305600, {0x5868334, 0xb}, 0x0?)
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/src/github.com/k3s-io/k3s/pkg/etcd/snapshot_controller.go:62 +0x79
Dec 12 14:04:06 ck-c7-0 k3s[12709]: github.com/rancher/wrangler/pkg/generic.FromObjectHandlerToHandler[...].func1({0x0?, 0x0?})
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/rancher/wrangler@v1.1.1-0.20230425173236-39a4707f0689/pkg/generic/controller.go:160 +0x57
Dec 12 14:04:06 ck-c7-0 k3s[12709]: github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00afe0c08?, {0x5868334?, 0x450453?}, {0x0?, 0x0?})
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/sharedcontroller.go:29 +0x38
Dec 12 14:04:06 ck-c7-0 k3s[12709]: github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc010713400, {0x5868334, 0xb}, {0x0, 0x0})
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/sharedhandler.go:75 +0x218
Dec 12 14:04:06 ck-c7-0 k3s[12709]: github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc005f86630, {0x5868334, 0xb})
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:230 +0xbe
Dec 12 14:04:06 ck-c7-0 k3s[12709]: github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc005f86630, {0x4d6e7e0?, 0xc00651f2e0?})
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:214 +0x105
Dec 12 14:04:06 ck-c7-0 k3s[12709]: github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc005f86630)
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:191 +0x46
Dec 12 14:04:06 ck-c7-0 k3s[12709]: github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:180
Dec 12 14:04:06 ck-c7-0 k3s[12709]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.27.7-k3s1/pkg/util/wait/backoff.go:226 +0x3e
Dec 12 14:04:06 ck-c7-0 k3s[12709]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00007f3c0?, {0x63c8060, 0xc0057679b0}, 0x1, 0xc0133864e0)
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.27.7-k3s1/pkg/util/wait/backoff.go:227 +0xb6
Dec 12 14:04:06 ck-c7-0 k3s[12709]: k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00afe0fb0?, 0x3b9aca00, 0x0, 0x0?, 0x447305?)
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.27.7-k3s1/pkg/util/wait/backoff.go:204 +0x89
Dec 12 14:04:06 ck-c7-0 k3s[12709]: k8s.io/apimachinery/pkg/util/wait.Until(0x919cea?, 0x0?, 0x0?)
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.27.7-k3s1/pkg/util/wait/backoff.go:161 +0x25
Dec 12 14:04:06 ck-c7-0 k3s[12709]: created by github.com/rancher/lasso/pkg/controller.(*controller).run
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:148 +0x2d5
Dec 12 14:04:06 ck-c7-0 k3s[12709]: panic: assignment to entry in nil map [recovered]
Dec 12 14:04:06 ck-c7-0 k3s[12709]: panic: assignment to entry in nil map
Dec 12 14:04:06 ck-c7-0 k3s[12709]: goroutine 8337 [running]:
Dec 12 14:04:06 ck-c7-0 k3s[12709]: k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00651f2e0?})
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.27.7-k3s1/pkg/util/runtime/runtime.go:56 +0xd7
Dec 12 14:04:06 ck-c7-0 k3s[12709]: panic({0x500d640, 0x63b9f20})
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /usr/local/go/src/runtime/panic.go:884 +0x213
Dec 12 14:04:06 ck-c7-0 k3s[12709]: github.com/k3s-io/k3s/pkg/etcd.(*etcdSnapshotHandler).reconcile(0xc002305600)
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/src/github.com/k3s-io/k3s/pkg/etcd/snapshot_controller.go:261 +0xad5
Dec 12 14:04:06 ck-c7-0 k3s[12709]: github.com/k3s-io/k3s/pkg/etcd.(*etcdSnapshotHandler).sync(0xc002305600, {0x5868334, 0xb}, 0x0?)
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/src/github.com/k3s-io/k3s/pkg/etcd/snapshot_controller.go:62 +0x79
Dec 12 14:04:06 ck-c7-0 k3s[12709]: github.com/rancher/wrangler/pkg/generic.FromObjectHandlerToHandler[...].func1({0x0?, 0x0?})
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/rancher/wrangler@v1.1.1-0.20230425173236-39a4707f0689/pkg/generic/controller.go:160 +0x57
Dec 12 14:04:06 ck-c7-0 k3s[12709]: github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0xc00afe0c08?, {0x5868334?, 0x450453?}, {0x0?, 0x0?})
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/sharedcontroller.go:29 +0x38
Dec 12 14:04:06 ck-c7-0 k3s[12709]: github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc010713400, {0x5868334, 0xb}, {0x0, 0x0})
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/sharedhandler.go:75 +0x218
Dec 12 14:04:06 ck-c7-0 k3s[12709]: github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc005f86630, {0x5868334, 0xb})
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:230 +0xbe
Dec 12 14:04:06 ck-c7-0 k3s[12709]: github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc005f86630, {0x4d6e7e0?, 0xc00651f2e0?})
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:214 +0x105
Dec 12 14:04:06 ck-c7-0 k3s[12709]: github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc005f86630)
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:191 +0x46
Dec 12 14:04:06 ck-c7-0 k3s[12709]: github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:180
Dec 12 14:04:06 ck-c7-0 k3s[12709]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.27.7-k3s1/pkg/util/wait/backoff.go:226 +0x3e
Dec 12 14:04:06 ck-c7-0 k3s[12709]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00007f3c0?, {0x63c8060, 0xc0057679b0}, 0x1, 0xc0133864e0)
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.27.7-k3s1/pkg/util/wait/backoff.go:227 +0xb6
Dec 12 14:04:06 ck-c7-0 k3s[12709]: k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00afe0fb0?, 0x3b9aca00, 0x0, 0x0?, 0x447305?)
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.27.7-k3s1/pkg/util/wait/backoff.go:204 +0x89
Dec 12 14:04:06 ck-c7-0 k3s[12709]: k8s.io/apimachinery/pkg/util/wait.Until(0x919cea?, 0x0?, 0x0?)
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.27.7-k3s1/pkg/util/wait/backoff.go:161 +0x25
Dec 12 14:04:06 ck-c7-0 k3s[12709]: created by github.com/rancher/lasso/pkg/controller.(*controller).run
Dec 12 14:04:06 ck-c7-0 k3s[12709]: /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20221227210133-6ea88ca2fbcc/pkg/controller/controller.go:148 +0x2d5
Dec 12 14:04:06 ck-c7-0 systemd[1]: k3s.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 12 14:04:06 ck-c7-0 systemd[1]: Unit k3s.service entered failed state.
Dec 12 14:04:06 ck-c7-0 systemd[1]: k3s.service failed.
Dec 12 14:04:11 ck-c7-0 systemd[1]: k3s.service holdoff time over, scheduling restart.
Dec 12 14:04:11 ck-c7-0 systemd[1]: Stopped Lightweight Kubernetes.
```

[k3s-panic.log](https://github.com/k3s-io/k3s/files/13653674/k3s-panic.log)

**Comment by brandond** [comment]
Steps to reproduce:

1. Start k3s with embedded etcd
2. create etcd extra metadata configmap
3. take a snapshot
4. delete the etcd snapshot list configmap
5. restart k3s

Note that k3s will continue crashlooping until all snapshots are delete from disk and/or s3.

**Comment by mdrahman-suse** [comment]
## Validated with master branch (v1.29) on commit 9a70021a

## Environment Details

 
*Infrastructure*
- [ ] Cloud
- [ ] Hosted
 
*Node(s) CPU architecture, OS, and Version:*

```
Ubuntu 22.04
```
 
*Cluster Configuration:*

```
1 server
```
 
*Config.yaml:*

```
write-kubeconfig-mode: 644
cluster-init: true
token: snowstorm
node-name: server1
node-external-ip: <public-ip>
node-ip: <private-ip>
```
 
## Testing Steps

1. Copy config.yaml
```
$ sudo mkdir -p /etc/rancher/k3s && sudo cp config.yaml /etc/rancher/k3s
```
2. Install k3s: `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.29.0+k3s1 sh -`
3. Run the commands as mentioned here: https://github.com/k3s-io/k3s/issues/9047#issuecomment-1853087272 
```
kubectl create configmap -n kube-system k3s-etcd-snapshot-extra-metadata --from-literal=foo=bar
sudo k3s etcd-snapshot save
kubectl delete configmap -n kube-system k3s-etcd-snapshots
sudo systemctl restart k3s
```
 
 
**Replication Results:**
- k3s version used for replication:

```
k3s version v1.29.0+k3s1 (3190a5fa)
go version go1.21.5
```
 

- Observed the error as mentioned 

<details>

<summary> Error from log </summary>

```
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: E0116 19:51:08.359697    4786 runtime.go:79] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: goroutine 10095 [running]:
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: k8s.io/apimachinery/pkg/util/runtime.logPanic({0x4fe6460?, 0x643fd10})
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.29.0-k3s1/pkg/util/runtime/runtime.go:75 +0x85
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00308aeb0?})
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.29.0-k3s1/pkg/util/runtime/runtime.go:49 +0x6b
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: panic({0x4fe6460?, 0x643fd10?})
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /usr/local/go/src/runtime/panic.go:914 +0x21f
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: github.com/k3s-io/k3s/pkg/etcd.(*etcdSnapshotHandler).reconcile(0xc00f639e00)
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/src/github.com/k3s-io/k3s/pkg/etcd/snapshot_controller.go:265 +0xaf5
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: github.com/k3s-io/k3s/pkg/etcd.(*etcdSnapshotHandler).sync(0xc00f639e00, {0x589a6e3, 0xb}, 0x0?)
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/src/github.com/k3s-io/k3s/pkg/etcd/snapshot_controller.go:62 +0x6d
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: github.com/rancher/wrangler/pkg/generic.(*Controller[...].func1({0x0?, 0x0?})
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/rancher/wrangler@v1.1.1-0.20230818201331-3604a6be798d/pkg/generic/controller.go:167 +0x54
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x5b1fbd421?, {0x589a6e3?, 0x0?}, {0x0?, 0x0?})
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/sharedcontroller.go:29 +0x32
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc00097af00, {0x589a6e3, 0xb}, {0x0, 0x0})
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/sharedhandler.go:75 +0x208
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00b1ca420, {0x589a6e3, 0xb})
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:229 +0xb4
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00b1ca420, {0x4cd77a0?, 0xc00308aeb0})
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:213 +0xf7
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00b1ca420)
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:190 +0x45
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:179
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.29.0-k3s1/pkg/util/wait/backoff.go:226 +0x33
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00f964f40?, {0x64657e0, 0xc006e6c210}, 0x1, 0xc00f95efc0)
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.29.0-k3s1/pkg/util/wait/backoff.go:227 +0xaf
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x80?, 0x52?)
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.29.0-k3s1/pkg/util/wait/backoff.go:204 +0x7f
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: k8s.io/apimachinery/pkg/util/wait.Until(0xc00f971218?, 0xc00d72b428?, 0x15?)
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.29.0-k3s1/pkg/util/wait/backoff.go:161 +0x1e
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: created by github.com/rancher/lasso/pkg/controller.(*controller).run in goroutine 10080
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:147 +0x2d0
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: panic: assignment to entry in nil map [recovered]
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         panic: assignment to entry in nil map
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: goroutine 10095 [running]:
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00308aeb0?})
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.29.0-k3s1/pkg/util/runtime/runtime.go:56 +0xcd
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: panic({0x4fe6460?, 0x643fd10?})
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /usr/local/go/src/runtime/panic.go:914 +0x21f
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: github.com/k3s-io/k3s/pkg/etcd.(*etcdSnapshotHandler).reconcile(0xc00f639e00)
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/src/github.com/k3s-io/k3s/pkg/etcd/snapshot_controller.go:265 +0xaf5
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: github.com/k3s-io/k3s/pkg/etcd.(*etcdSnapshotHandler).sync(0xc00f639e00, {0x589a6e3, 0xb}, 0x0?)
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/src/github.com/k3s-io/k3s/pkg/etcd/snapshot_controller.go:62 +0x6d
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: github.com/rancher/wrangler/pkg/generic.(*Controller[...].func1({0x0?, 0x0?})
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/rancher/wrangler@v1.1.1-0.20230818201331-3604a6be798d/pkg/generic/controller.go:167 +0x54
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: github.com/rancher/lasso/pkg/controller.SharedControllerHandlerFunc.OnChange(0x5b1fbd421?, {0x589a6e3?, 0x0?}, {0x0?, 0x0?})
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/sharedcontroller.go:29 +0x32
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: github.com/rancher/lasso/pkg/controller.(*SharedHandler).OnChange(0xc00097af00, {0x589a6e3, 0xb}, {0x0, 0x0})
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/sharedhandler.go:75 +0x208
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: github.com/rancher/lasso/pkg/controller.(*controller).syncHandler(0xc00b1ca420, {0x589a6e3, 0xb})
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:229 +0xb4
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: github.com/rancher/lasso/pkg/controller.(*controller).processSingleItem(0xc00b1ca420, {0x4cd77a0?, 0xc00308aeb0})
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:213 +0xf7
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: github.com/rancher/lasso/pkg/controller.(*controller).processNextWorkItem(0xc00b1ca420)
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:190 +0x45
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: github.com/rancher/lasso/pkg/controller.(*controller).runWorker(...)
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:179
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.29.0-k3s1/pkg/util/wait/backoff.go:226 +0x33
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00f964f40?, {0x64657e0, 0xc006e6c210}, 0x1, 0xc00f95efc0)
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.29.0-k3s1/pkg/util/wait/backoff.go:227 +0xaf
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x80?, 0x52?)
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.29.0-k3s1/pkg/util/wait/backoff.go:204 +0x7f
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: k8s.io/apimachinery/pkg/util/wait.Until(0xc00f971218?, 0xc00d72b428?, 0x15?)
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.29.0-k3s1/pkg/util/wait/backoff.go:161 +0x1e
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]: created by github.com/rancher/lasso/pkg/controller.(*controller).run in goroutine 10080
Jan 16 19:51:08 ip-172-31-29-231 k3s[4786]:         /go/pkg/mod/github.com/rancher/lasso@v0.0.0-20230830164424-d684fdeb6f29/pkg/controller/controller.go:147 +0x2d0
Jan 16 19:51:08 ip-172-31-29-231 systemd[1]: k3s.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 16 19:51:08 ip-172-31-29-231 systemd[1]: k3s.service: Failed with result 'exit-code'.
```
 
</details>
 
**Validation Results:**
- k3s version used for validation:

```
k3s version v1.29.0+k3s-9a70021a (9a70021a)
go version go1.21.5
```
 

- No error or panic is observed
- Cluster is up and running
```
$ kubectl get nodes
NAME      STATUS   ROLES                       AGE   VERSION
server1   Ready    control-plane,etcd,master   11m   v1.29.0+k3s-9a70021a

$ kubectl get pods -A
NAMESPACE     NAME                                      READY   STATUS      RESTARTS   AGE
kube-system   coredns-6799fbcd5-ct44d                   1/1     Running     0          11m
kube-system   helm-install-traefik-crd-lztgx            0/1     Completed   0          11m
kube-system   helm-install-traefik-ggs9p                0/1     Completed   1          11m
kube-system   local-path-provisioner-84db5d44d9-ql7hd   1/1     Running     0          11m
kube-system   metrics-server-67c658944b-gb7gc           1/1     Running     0          11m
kube-system   svclb-traefik-4bff7076-pn6tk              2/2     Running     0          10m
kube-system   traefik-f4564c4f4-6xhjv                   1/1     Running     0          10m
```
