### ISSUE TITLE
dual-stack k3s server fails to start

### ISSUE THREAD

**Issue by Mellonta** [k3s-io/k3s#9569]
**Environmental Info:**
K3s Version:  v1.28.6+k3s2 (c9f49a3b)

Node(s) CPU architecture, OS, and Version: Linux pi 6.1.0-rpi8-rpi-2712 #1 SMP PREEMPT Debian 1:6.1.73-1+rpt1 (2024-01-25) aarch64 GNU/Linux

Cluster Configuration: 1 server

**Describe the bug:**

Panic ("invalid memory address or nil pointer dereference") when starting a k3s server with dual stack.

These lines in the log look concerning:
```
INFO[0003] Using dual-stack mode. The interface wlan0 with ipv4 address 192.168.1.67 and ipv6 address 2600:4040:7a9a:5d00:3e72:ee9c:5a46:fe82 will be used by flannel
I0225 17:57:51.327365   22814 kube.go:510] Creating the node lease for IPv4. This is the n.Spec.PodCIDRs: [10.42.0.0/24]
I0225 17:57:51.327416   22814 kube.go:543] Creating the node lease for IPv6. This is the n.Spec.PodCIDRs: [10.42.0.0/24]
```

**Steps To Reproduce:**

- Installed K3s: 
```
# copied from doc
sudo /usr/local/bin/k3s server --flannel-ipv6-masq --cluster-cidr=10.42.0.0/16,2001:cafe:42::/56 --service-cidr=10.43.0.0/16,2001:cafe:43::/112
```
**Expected behavior:**

**Actual behavior:**

**Additional context / logs:**

```
INFO[0003] Flannel found PodCIDR assigned for node pi
INFO[0003] Using dual-stack mode. The interface wlan0 with ipv4 address 192.168.1.67 and ipv6 address 2600:4040:7a9a:5d00:3e72:ee9c:5a46:fe82 will be used by flannel
I0225 17:57:51.285469   22814 server.go:162] "Starting to listen" address="0.0.0.0" port=10250
I0225 17:57:51.287198   22814 server.go:462] "Adding debug handlers to kubelet server"
I0225 17:57:51.290166   22814 ratelimit.go:65] "Setting rate limiting for podresources endpoint" qps=100 burstTokens=10
I0225 17:57:51.290548   22814 server.go:233] "Starting to serve the podresources API" endpoint="unix:/var/lib/kubelet/pod-resources/kubelet.sock"
I0225 17:57:51.293655   22814 volume_manager.go:291] "Starting Kubelet Volume Manager"
I0225 17:57:51.296431   22814 kube.go:145] Waiting 10m0s for node controller to sync
I0225 17:57:51.296864   22814 desired_state_of_world_populator.go:151] "Desired state populator starts to run"
I0225 17:57:51.299659   22814 kube.go:489] Starting kube subnet manager
I0225 17:57:51.299926   22814 reconciler_new.go:29] "Reconciler: start to sync state"
I0225 17:57:51.309466   22814 kubelet_network_linux.go:50] "Initialized iptables rules." protocol="IPv4"
I0225 17:57:51.311979   22814 kubelet_network_linux.go:50] "Initialized iptables rules." protocol="IPv6"
I0225 17:57:51.312035   22814 status_manager.go:217] "Starting to sync pod status with apiserver"
I0225 17:57:51.312076   22814 kubelet.go:2303] "Starting kubelet main sync loop"
E0225 17:57:51.312190   22814 kubelet.go:2327] "Skipping pod synchronization" err="[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]"
I0225 17:57:51.327365   22814 kube.go:510] Creating the node lease for IPv4. This is the n.Spec.PodCIDRs: [10.42.0.0/24]
I0225 17:57:51.327416   22814 kube.go:543] Creating the node lease for IPv6. This is the n.Spec.PodCIDRs: [10.42.0.0/24]
E0225 17:57:51.327761   22814 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 9541 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x50971e0?, 0x9bd5740})
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.6-k3s1/pkg/util/runtime/runtime.go:75 +0x7c
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x40003b8e60?})
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.6-k3s1/pkg/util/runtime/runtime.go:49 +0x78
panic({0x50971e0, 0x9bd5740})
        /usr/local/go/src/runtime/panic.go:884 +0x1f4
github.com/flannel-io/flannel/pkg/ip.FromIP6Net(0x4009d957b0?)
        /go/pkg/mod/github.com/flannel-io/flannel@v0.22.2/pkg/ip/ip6net.go:166 +0x18
github.com/flannel-io/flannel/pkg/subnet/kube.(*kubeSubnetManager).nodeToLease(_, {{{0x0, 0x0}, {0x0, 0x0}}, {{0x4009d956c8, 0x2}, {0x0, 0x0}, {0x0, ...}, ...}, ...})
        /go/pkg/mod/github.com/flannel-io/flannel@v0.22.2/pkg/subnet/kube/kube.go:557 +0x3c4
github.com/flannel-io/flannel/pkg/subnet/kube.(*kubeSubnetManager).handleAddLeaseEvent(0x4009cae400, 0x0, {0x5979ce0?, 0x4009db4dc0})
        /go/pkg/mod/github.com/flannel-io/flannel@v0.22.2/pkg/subnet/kube/kube.go:264 +0xe4
github.com/flannel-io/flannel/pkg/subnet/kube.newKubeSubnetManager.func3({0x5979ce0?, 0x4009db4dc0?})
        /go/pkg/mod/github.com/flannel-io/flannel@v0.22.2/pkg/subnet/kube/kube.go:203 +0x38
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.28.6-k3s1/tools/cache/controller.go:239
k8s.io/client-go/tools/cache.processDeltas({0x6938d40, 0x4009cb03c0}, {0x6961be0, 0x4009cb03d8}, {0x4009dda600?, 0x1, 0x4009376401?}, 0xa0?)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.28.6-k3s1/tools/cache/controller.go:458 +0x1f4
k8s.io/client-go/tools/cache.newInformer.func1({0x513d860?, 0x4009dd7500?}, 0x1?)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.28.6-k3s1/tools/cache/controller.go:509 +0x60
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0x40093764d0, 0x4009cbd6e0)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.28.6-k3s1/tools/cache/delta_fifo.go:603 +0x4ec
k8s.io/client-go/tools/cache.(*controller).processLoop(0x4009cc2e60)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.28.6-k3s1/tools/cache/controller.go:188 +0x3c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7ffe0e8f03a8?)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.6-k3s1/pkg/util/wait/backoff.go:226 +0x40
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4005627101?, {0x68f1320, 0x4009ccdb90}, 0x1, 0x0)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.6-k3s1/pkg/util/wait/backoff.go:227 +0x90
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4009cc2ed8?, 0x3b9aca00, 0x0, 0x80?, 0x7ffe0e82b618?)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.6-k3s1/pkg/util/wait/backoff.go:204 +0x80
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.6-k3s1/pkg/util/wait/backoff.go:161
k8s.io/client-go/tools/cache.(*controller).Run(0x4009cc2e60, 0x0)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.28.6-k3s1/tools/cache/controller.go:159 +0x290
github.com/flannel-io/flannel/pkg/subnet/kube.(*kubeSubnetManager).Run(0x4009cae400, {0x693aee0, 0x40000740a0})
        /go/pkg/mod/github.com/flannel-io/flannel@v0.22.2/pkg/subnet/kube/kube.go:490 +0x98
created by github.com/flannel-io/flannel/pkg/subnet/kube.NewSubnetManager
        /go/pkg/mod/github.com/flannel-io/flannel@v0.22.2/pkg/subnet/kube/kube.go:143 +0x4a4
E0225 17:57:51.328111   22814 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 9541 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x50971e0?, 0x9bd5740})
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.6-k3s1/pkg/util/runtime/runtime.go:75 +0x7c
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x40003b8d70?})
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.6-k3s1/pkg/util/runtime/runtime.go:49 +0x78
panic({0x50971e0, 0x9bd5740})
        /usr/local/go/src/runtime/panic.go:884 +0x1f4
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x40003b8e60?})
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.6-k3s1/pkg/util/runtime/runtime.go:56 +0xe0
panic({0x50971e0, 0x9bd5740})
        /usr/local/go/src/runtime/panic.go:884 +0x1f4
github.com/flannel-io/flannel/pkg/ip.FromIP6Net(0x4009d957b0?)
        /go/pkg/mod/github.com/flannel-io/flannel@v0.22.2/pkg/ip/ip6net.go:166 +0x18
github.com/flannel-io/flannel/pkg/subnet/kube.(*kubeSubnetManager).nodeToLease(_, {{{0x0, 0x0}, {0x0, 0x0}}, {{0x4009d956c8, 0x2}, {0x0, 0x0}, {0x0, ...}, ...}, ...})
        /go/pkg/mod/github.com/flannel-io/flannel@v0.22.2/pkg/subnet/kube/kube.go:557 +0x3c4
github.com/flannel-io/flannel/pkg/subnet/kube.(*kubeSubnetManager).handleAddLeaseEvent(0x4009cae400, 0x0, {0x5979ce0?, 0x4009db4dc0})
        /go/pkg/mod/github.com/flannel-io/flannel@v0.22.2/pkg/subnet/kube/kube.go:264 +0xe4
github.com/flannel-io/flannel/pkg/subnet/kube.newKubeSubnetManager.func3({0x5979ce0?, 0x4009db4dc0?})
        /go/pkg/mod/github.com/flannel-io/flannel@v0.22.2/pkg/subnet/kube/kube.go:203 +0x38
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.28.6-k3s1/tools/cache/controller.go:239
k8s.io/client-go/tools/cache.processDeltas({0x6938d40, 0x4009cb03c0}, {0x6961be0, 0x4009cb03d8}, {0x4009dda600?, 0x1, 0x4009376401?}, 0xa0?)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.28.6-k3s1/tools/cache/controller.go:458 +0x1f4
k8s.io/client-go/tools/cache.newInformer.func1({0x513d860?, 0x4009dd7500?}, 0x1?)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.28.6-k3s1/tools/cache/controller.go:509 +0x60
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0x40093764d0, 0x4009cbd6e0)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.28.6-k3s1/tools/cache/delta_fifo.go:603 +0x4ec
k8s.io/client-go/tools/cache.(*controller).processLoop(0x4009cc2e60)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.28.6-k3s1/tools/cache/controller.go:188 +0x3c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7ffe0e8f03a8?)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.6-k3s1/pkg/util/wait/backoff.go:226 +0x40
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4005627101?, {0x68f1320, 0x4009ccdb90}, 0x1, 0x0)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.6-k3s1/pkg/util/wait/backoff.go:227 +0x90
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4009cc2ed8?, 0x3b9aca00, 0x0, 0x80?, 0x7ffe0e82b618?)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.6-k3s1/pkg/util/wait/backoff.go:204 +0x80
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.6-k3s1/pkg/util/wait/backoff.go:161
k8s.io/client-go/tools/cache.(*controller).Run(0x4009cc2e60, 0x0)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.28.6-k3s1/tools/cache/controller.go:159 +0x290
github.com/flannel-io/flannel/pkg/subnet/kube.(*kubeSubnetManager).Run(0x4009cae400, {0x693aee0, 0x40000740a0})
        /go/pkg/mod/github.com/flannel-io/flannel@v0.22.2/pkg/subnet/kube/kube.go:490 +0x98
created by github.com/flannel-io/flannel/pkg/subnet/kube.NewSubnetManager
        /go/pkg/mod/github.com/flannel-io/flannel@v0.22.2/pkg/subnet/kube/kube.go:143 +0x4a4
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x3113c38]

goroutine 9541 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x40003b8d70?})
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.6-k3s1/pkg/util/runtime/runtime.go:56 +0xe0
panic({0x50971e0, 0x9bd5740})
        /usr/local/go/src/runtime/panic.go:884 +0x1f4
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x40003b8e60?})
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.6-k3s1/pkg/util/runtime/runtime.go:56 +0xe0
panic({0x50971e0, 0x9bd5740})
        /usr/local/go/src/runtime/panic.go:884 +0x1f4
github.com/flannel-io/flannel/pkg/ip.FromIP6Net(0x4009d957b0?)
        /go/pkg/mod/github.com/flannel-io/flannel@v0.22.2/pkg/ip/ip6net.go:166 +0x18
github.com/flannel-io/flannel/pkg/subnet/kube.(*kubeSubnetManager).nodeToLease(_, {{{0x0, 0x0}, {0x0, 0x0}}, {{0x4009d956c8, 0x2}, {0x0, 0x0}, {0x0, ...}, ...}, ...})
        /go/pkg/mod/github.com/flannel-io/flannel@v0.22.2/pkg/subnet/kube/kube.go:557 +0x3c4
github.com/flannel-io/flannel/pkg/subnet/kube.(*kubeSubnetManager).handleAddLeaseEvent(0x4009cae400, 0x0, {0x5979ce0?, 0x4009db4dc0})
        /go/pkg/mod/github.com/flannel-io/flannel@v0.22.2/pkg/subnet/kube/kube.go:264 +0xe4
github.com/flannel-io/flannel/pkg/subnet/kube.newKubeSubnetManager.func3({0x5979ce0?, 0x4009db4dc0?})
        /go/pkg/mod/github.com/flannel-io/flannel@v0.22.2/pkg/subnet/kube/kube.go:203 +0x38
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.28.6-k3s1/tools/cache/controller.go:239
k8s.io/client-go/tools/cache.processDeltas({0x6938d40, 0x4009cb03c0}, {0x6961be0, 0x4009cb03d8}, {0x4009dda600?, 0x1, 0x4009376401?}, 0xa0?)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.28.6-k3s1/tools/cache/controller.go:458 +0x1f4
k8s.io/client-go/tools/cache.newInformer.func1({0x513d860?, 0x4009dd7500?}, 0x1?)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.28.6-k3s1/tools/cache/controller.go:509 +0x60
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0x40093764d0, 0x4009cbd6e0)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.28.6-k3s1/tools/cache/delta_fifo.go:603 +0x4ec
k8s.io/client-go/tools/cache.(*controller).processLoop(0x4009cc2e60)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.28.6-k3s1/tools/cache/controller.go:188 +0x3c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7ffe0e8f03a8?)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.6-k3s1/pkg/util/wait/backoff.go:226 +0x40
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x4005627101?, {0x68f1320, 0x4009ccdb90}, 0x1, 0x0)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.6-k3s1/pkg/util/wait/backoff.go:227 +0x90
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4009cc2ed8?, 0x3b9aca00, 0x0, 0x80?, 0x7ffe0e82b618?)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.6-k3s1/pkg/util/wait/backoff.go:204 +0x80
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/apimachinery@v1.28.6-k3s1/pkg/util/wait/backoff.go:161
k8s.io/client-go/tools/cache.(*controller).Run(0x4009cc2e60, 0x0)
        /go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.28.6-k3s1/tools/cache/controller.go:159 +0x290
github.com/flannel-io/flannel/pkg/subnet/kube.(*kubeSubnetManager).Run(0x4009cae400, {0x693aee0, 0x40000740a0})
        /go/pkg/mod/github.com/flannel-io/flannel@v0.22.2/pkg/subnet/kube/kube.go:490 +0x98
created by github.com/flannel-io/flannel/pkg/subnet/kube.NewSubnetManager
        /go/pkg/mod/github.com/flannel-io/flannel@v0.22.2/pkg/subnet/kube/kube.go:143 +0x4a4
```

[log.txt](https://github.com/k3s-io/k3s/files/14398164/log.txt)

**Comment by Mellonta** [comment]
no idea why but reinstalling and rebooting solve the issue.

**Comment by brandond** [comment]
@manuelbuil is there anything interesting in the stack traces here?

**Comment by manuelbuil** [comment]
@rbrtbnfgl can you have a look? Since you were looking at dualStack code, you will probably be faster :P

**Comment by rbrtbnfgl** [comment]
it seems related to the environment that wasn't fully cleaned before the execution the node podCIDR configured on the node is only the IPv4. We could add more checks on flannel to avoid the panic on the code but an error for sure.
